/* VÉRITAS — catalogue des jeux éducatifs (chargé à la demande).
   47 Ko, ouvert uniquement depuis la page Jeux & Œuvres. Le module REMPLIT
   le tableau déjà déclaré dans app.js (push) au lieu de le remplacer : les
   44 points de lecture du code restent inchangés. */
Array.prototype.push.apply(window.JEUX_CATALOGUE, [
  {id:"j1",titre:"Calcul Mental",emoji:"🔢",matiere:"Maths",niveau:"6eme-3eme",
   desc:"Additions, soustractions, multiplications et divisions chronometrees",gratuit:true,
   action:"lancerCalculMental"},
  {id:"j2",titre:"Devinette Personnages",emoji:"🧩",matiere:"Histoire-Geo",niveau:"3eme-Tle",
   desc:"Retrouvez les grands personnages de l'histoire africaine et mondiale",gratuit:true,
   action:"lancerDevinette"},
  {id:"j3",titre:"Orthographe Challenge",emoji:"✍️",matiere:"Francais",niveau:"6eme-3eme",
   desc:"Ecrivez correctement les mots difficiles du programme camerounais",gratuit:true,
   action:"lancerOrthographe"},
  {id:"j4",titre:"Geographie Cameroun",emoji:"🗺️",matiere:"Geographie",niveau:"5eme-3eme",
   desc:"Situez les regions, villes et fleuves du Cameroun sur la carte",gratuit:true,
   action:"lancerCarteGeo"},
  {id:"j5",titre:"Conjugaison Express",emoji:"📝",matiere:"Francais",niveau:"6eme-Tle",
   desc:"Conjuguez rapidement les verbes irreguliers et les temps composes",gratuit:false,plan:"Premium",
   action:"lancerConjugaison"},
  {id:"j6",titre:"Figures de Rhetorique",emoji:"📖",matiere:"Litterature",niveau:"2nde-Tle",
   desc:"Identifiez metaphores, allegories et autres figures de style",gratuit:false,plan:"Premium",
   action:"lancerFigures"},
  {id:"j7",titre:"Tableau Periodique",emoji:"⚗️",matiere:"Physique-Chimie",niveau:"2nde-Tle",
   desc:"Retrouvez les elements chimiques par leur symbole et numero atomique",gratuit:true,
   action:"lancerTableauPeriodique"},
  {id:"j8",titre:"Mots Caches Scientifiques",emoji:"🔬",matiere:"SVT",niveau:"4eme-1ere",
   desc:"Retrouvez les termes scientifiques caches dans la grille",gratuit:true,
   action:"lancerMotsCaches"},
  // ── OEUVRES LITTERAIRES 3ème ──
  {id:"j_3e_enfant_noir_qcm",titre:"L'Enfant Noir — Quiz 3ème",emoji:"📚",matiere:"Litterature",niveau:"3eme",
   desc:"QCM sur l'œuvre de Camara Laye au programme de 3ème",gratuit:true,type:"qcm",action:"lancerJLitL3e_enfant_noir",
   questions:[
    {q:"Qui est l'auteur de 'L'Enfant Noir' ?",opts:["Mongo Beti","Ferdinand Oyono","Camara Laye","Sembène Ousmane"],ans:2,exp:"Camara Laye (1928-1980), auteur guinéen. Roman autobiographique publié en 1953."},
    {q:"Dans quelle ville de Guinée est né le narrateur de 'L'Enfant Noir' ?",opts:["Conakry","Kouroussa","Kankan","Kindia"],ans:1,exp:"Le narrateur est né à Kouroussa, ville de Haute-Guinée."},
    {q:"Quel est le métier du père dans 'L'Enfant Noir' ?",opts:["Cultivateur","Forgeron","Pêcheur","Enseignant"],ans:1,exp:"Le père est forgeron et travaille l'or. Il a un don mystique lié à son totem : un serpent noir."},
    {q:"Quel animal symbolise le don mystique du père ?",opts:["Le lion","Le serpent noir","L'aigle","Le crocodile"],ans:1,exp:"Un petit serpent noir se glisse dans l'atelier du père — c'est son génie protecteur."},
    {q:"Où le narrateur est-il envoyé pour poursuivre ses études ?",opts:["Abidjan","Dakar","Paris","Conakry"],ans:2,exp:"Le roman se termine par le départ du narrateur pour Paris, symbole du déchirement culturel."},
    {q:"Quel thème central traverse 'L'Enfant Noir' ?",opts:["La guerre coloniale","Le conflit tradition/modernité","L'amour romantique","La révolte politique"],ans:1,exp:"Le roman explore la tension entre les traditions africaines et l'éducation occidentale imposée par la colonisation."},
    {q:"Quel est le prénom du narrateur ?",opts:["Kofi","Laye","Amadou","Toundi"],ans:1,exp:"Le narrateur se prénomme Laye, comme l'auteur lui-même — confirmant le caractère autobiographique."},
    {q:"Comment s'appelle l'ami d'enfance du narrateur ?",opts:["Kouyaté","Fanta","Check","Sidafa"],ans:3,exp:"Sidafa est le meilleur ami de Laye, avec qui il partage les jeux et les aventures du village."},
   ]},
  {id:"j_3e_enfant_noir_pendu",titre:"L'Enfant Noir — Pendu",emoji:"✏️",matiere:"Litterature",niveau:"3eme",
   desc:"Retrouvez les mots-clés de l'œuvre de Camara Laye",gratuit:true,type:"pendu",action:"lancerJLitP3e_enfant_noir",
   questions:[
    {mot:"KOUROUSSA",ind:"Ville natale du narrateur en Guinée"},
    {mot:"FORGERON",ind:"Métier du père dans l'œuvre"},
    {mot:"TOTEM",ind:"Animal spirituel protecteur"},
    {mot:"GUINEE",ind:"Pays d'origine de Camara Laye"},
    {mot:"AUTOBIOGRAPHIQUE",ind:"Genre de ce roman"},
    {mot:"TRADITION",ind:"Valeur défendue face à la modernité"},
    {mot:"PARIS",ind:"Destination finale du narrateur"},
   ]},
  {id:"j_3e_vieux_negre_qcm",titre:"Le Vieux Nègre et la Médaille — Quiz 3ème",emoji:"🏅",matiere:"Litterature",niveau:"3eme",
   desc:"QCM sur l'œuvre de Ferdinand Oyono",gratuit:true,type:"qcm",action:"lancerJLitL3e_vieux_negre",
   questions:[
    {q:"Qui est l'auteur du 'Vieux Nègre et la Médaille' ?",opts:["Camara Laye","Mongo Beti","Ferdinand Oyono","Cheikh Hamidou Kane"],ans:2,exp:"Ferdinand Oyono (1929-2010), écrivain camerounais né à Ebolowa. Roman publié en 1956, satire du colonialisme."},
    {q:"Quel est le nom du personnage principal ?",opts:["Toundi","Meka","Medza","Samba Diallo"],ans:1,exp:"Meka est le vieux paysan catholique du village de Doum, personnage central dont la naïveté révèle le cynisme colonial."},
    {q:"Pourquoi Meka reçoit-il une médaille ?",opts:["Pour ses exploits militaires","Pour avoir donné ses fils à la guerre et ses terres aux missionnaires","Pour être le chef du village","Pour son travail à l'administration"],ans:1,exp:"Meka a perdu ses deux fils à la guerre et cédé ses terres aux missionnaires — des sacrifices colossaux que la médaille coloniale compense dérisoi­rement."},
    {q:"Comment s'appelle la femme de Meka ?",opts:["Mami Titi","Amalia","Kelara","Doumba"],ans:2,exp:"Kelara est la femme aimante et fidèle de Meka, qui partage ses espoirs et leur désillusion commune après la cérémonie."},
    {q:"Dans quel village vivent Meka et sa femme ?",opts:["Ebolowa","Tanga","Doum","Mbalmayo"],ans:2,exp:"Meka habite le village de Doum, communauté rurale camerounaise dont la vie simple contraste avec l'absurdité du pouvoir colonial."},
    {q:"Qui est Mami Titi dans le roman ?",opts:["La femme du gouverneur","La fille de Meka","Une distillatrice d'arki du village","La cuisinière de l'administration coloniale"],ans:2,exp:"Mami Titi est une femme de Doum qui distille l'arki (eau-de-vie locale) — figure pittoresque et vivante de la communauté africaine."},
    {q:"Quelle mésaventure Meka vit-il la nuit de la remise de médaille ?",opts:["Il est félicité par le gouverneur","Il est arrêté et mis en prison par erreur","Il perd sa médaille dans la foule","Il rencontre le roi de France"],ans:1,exp:"Meka est arrêté par erreur par la police coloniale et passe la nuit en prison — cruelle ironie du sort pour celui qu'on vient de décorer."},
    {q:"Quelle est la tonalité dominante de ce roman ?",opts:["Tragique et épique","Ironique et satirique","Romantique et lyrique","Didactique et moralisatrice"],ans:1,exp:"Oyono use d'une ironie mordante pour critiquer l'administration coloniale et dénoncer l'hypocrisie de ses valeurs affichées."},
    {q:"Que symbolise la médaille dans le roman ?",opts:["La gloire africaine","La duperie et l'humiliation coloniale","Une récompense méritée","Le progrès social"],ans:1,exp:"La médaille symbolise le mensonge colonial : elle ne compense ni les sacrifices de Meka, ni la perte de ses fils et de ses terres."},
   ]},
  {id:"j_3e_vf_lit",titre:"Littérature 3ème — Vrai / Faux",emoji:"✅",matiere:"Litterature",niveau:"3eme",
   desc:"Vrai ou Faux sur les œuvres au programme de 3ème",gratuit:true,type:"vf",action:"lancerJLitVF3e",
   questions:[
    {q:"Camara Laye est un auteur camerounais.",opts:["Vrai","Faux"],ans:1,exp:"Faux. Camara Laye est guinéen, né à Kouroussa en 1928."},
    {q:"Dans 'L'Enfant Noir', le père du narrateur est forgeron.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Il travaille l'or et possède un don mystique symbolisé par le serpent noir."},
    {q:"'Le Vieux Nègre et la Médaille' est une œuvre de Mongo Beti.",opts:["Vrai","Faux"],ans:1,exp:"Faux. C'est Ferdinand Oyono qui est l'auteur (1956)."},
    {q:"'Mission Terminée' est l'œuvre de Mongo Beti.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Mongo Beti (Alexandre Biyidi) a publié 'Mission Terminée' en 1957."},
    {q:"Le narrateur de 'L'Enfant Noir' finit par rester en Guinée.",opts:["Vrai","Faux"],ans:1,exp:"Faux. Il part pour Paris poursuivre ses études, illustrant le déracinement culturel."},
   ]},
  // ── OEUVRES LITTERAIRES 1ère ──
  {id:"j_1e_antigone_qcm",titre:"Antigone (Anouilh) — Quiz 1ère",emoji:"🎭",matiere:"Litterature",niveau:"1ere",
   desc:"QCM sur Antigone de Jean Anouilh au programme de 1ère",gratuit:true,type:"qcm",action:"lancerJLitL1e_antigone",
   questions:[
    {q:"Qui est l'auteur de la pièce 'Antigone' au programme de 1ère ?",opts:["Sophocle","Jean Anouilh","Albert Camus","Jean Racine"],ans:1,exp:"Jean Anouilh (1910-1987) adapte le mythe grec de Sophocle dans une version moderne, créée en 1944 sous l'Occupation."},
    {q:"Contre quel décret Antigone se révolte-t-elle ?",opts:["L'interdiction du mariage","L'interdiction d'enterrer son frère Polynice","L'ordre de quitter Thèbes","La condamnation à mort de Créon"],ans:1,exp:"Créon interdit d'enterrer Polynice, considéré comme traître. Antigone transgresse ce décret par devoir filial et religieux."},
    {q:"Qui est Créon dans la pièce ?",opts:["Le père d'Antigone","L'amant d'Antigone","Le roi de Thèbes et oncle d'Antigone","Le frère d'Antigone"],ans:2,exp:"Créon est le roi de Thèbes, oncle d'Antigone. Il incarne le réalisme politique face à l'idéalisme d'Antigone."},
    {q:"Quel est le fiancé d'Antigone ?",opts:["Étéocle","Polynice","Hémon","Tirésias"],ans:2,exp:"Hémon, fils de Créon, est le fiancé d'Antigone. Il se suicidera après sa mort."},
    {q:"Comment Antigone meurt-elle ?",opts:["Décapitée","Empoisonnée","Emmurée vivante","Noyée"],ans:2,exp:"Créon la condamne à être emmurée vivante dans une caverne. Elle se suicide avant."},
    {q:"Quel thème oppose Antigone à Créon ?",opts:["La guerre et la paix","La loi divine vs la loi des hommes","L'amour et la haine","La richesse et la pauvreté"],ans:1,exp:"Antigone représente la loi divine (les dieux exigent l'enterrement) face à Créon et la raison d'État."},
    {q:"En quelle année Jean Anouilh crée-t-il sa version d'Antigone ?",opts:["1938","1944","1950","1962"],ans:1,exp:"Créée en 1944, sous l'Occupation allemande, la pièce résonne comme une allégorie de la résistance."},
   ]},
  {id:"j_1e_bouts_de_bois_qcm",titre:"Les Bouts de Bois de Dieu — Quiz 1ère",emoji:"🚂",matiere:"Litterature",niveau:"1ere",
   desc:"QCM sur l'œuvre de Sembène Ousmane",gratuit:true,type:"qcm",action:"lancerJLitL1e_bouts_bois",
   questions:[
    {q:"Qui a écrit 'Les Bouts de Bois de Dieu' ?",opts:["Mongo Beti","Ferdinand Oyono","Camara Laye","Sembène Ousmane"],ans:3,exp:"Sembène Ousmane (1923-2007), écrivain et cinéaste sénégalais. Roman publié en 1960."},
    {q:"Quel événement historique est au cœur du roman ?",opts:["La Première Guerre mondiale","La grève du chemin de fer Dakar-Niger (1947-1948)","L'indépendance du Sénégal","La Seconde Guerre mondiale"],ans:1,exp:"Le roman s'inspire de la grande grève des cheminots africains (oct. 1947 - mars 1948) sur la ligne Dakar-Niger."},
    {q:"Quel est le thème dominant du roman ?",opts:["L'amour romantique","La lutte collective ouvrière contre le colonialisme","La tradition africaine","La vie scolaire"],ans:1,exp:"La solidarité et la lutte collective face à l'exploitation coloniale : les travailleurs africains réclament l'égalité des droits."},
    {q:"Quel rôle jouent les femmes dans ce roman ?",opts:["Elles restent passives","Elles trahissent la grève","Elles sont actrices essentielles de la résistance","Elles sont absentes"],ans:2,exp:"Les femmes (Penda, Ramatoulaye, N'Deye Touti) jouent un rôle moteur : marche des femmes de Thiès à Dakar."},
    {q:"D'où vient le titre 'Les Bouts de Bois de Dieu' ?",opts:["D'une expression française","D'un proverbe wolof désignant les hommes","Du nom d'une locomotive","D'un conte peul"],ans:1,exp:"Expression wolof : 'les bouts de bois de Dieu' = les hommes, créés par Dieu, égaux en dignité."},
   ]},
  {id:"j_1e_vf_lit",titre:"Littérature 1ère — Vrai / Faux",emoji:"✅",matiere:"Litterature",niveau:"1ere",
   desc:"Vrai ou Faux sur les œuvres au programme de 1ère",gratuit:true,type:"vf",action:"lancerJLitVF1e",
   questions:[
    {q:"Jean Anouilh a écrit 'Antigone' en s'inspirant de Sophocle.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Anouilh reprend le mythe grec de Sophocle et le modernise (1944)."},
    {q:"'Les Bouts de Bois de Dieu' raconte la grève des enseignants.",opts:["Vrai","Faux"],ans:1,exp:"Faux. C'est la grève des cheminots sur la ligne Dakar-Niger (1947-1948)."},
    {q:"Dans Antigone, Hémon est le frère d'Antigone.",opts:["Vrai","Faux"],ans:1,exp:"Faux. Hémon est son fiancé, fils du roi Créon."},
    {q:"Sembène Ousmane est également cinéaste.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Il est considéré comme le père du cinéma africain."},
    {q:"Créon laisse finalement Antigone en vie.",opts:["Vrai","Faux"],ans:1,exp:"Faux. Créon la condamne à être emmurée vivante. Elle se suicide avant l'exécution."},
   ]},
  {id:"j_1e_antigone_trous",titre:"Antigone — Texte à trous",emoji:"✍️",matiere:"Litterature",niveau:"1ere",
   desc:"Complétez les phrases sur Antigone d'Anouilh",gratuit:true,type:"trous",action:"lancerJLitT1e_antigone",
   questions:[
    {q:"L'auteur de la pièce 'Antigone' adaptée en 1944 est Jean ___.",ans:"Anouilh",exp:"Jean Anouilh, dramaturge français (1910-1987)."},
    {q:"Antigone transgresse le décret de ___ en enterrant son frère.",ans:"Créon",exp:"Créon est le roi de Thèbes qui a interdit d'enterrer Polynice."},
    {q:"Le fiancé d'Antigone s'appelle ___.",ans:"Hémon",exp:"Hémon, fils de Créon, se suicide après la mort d'Antigone."},
    {q:"Antigone est condamnée à être ___ vivante.",ans:"emmurée",exp:"Elle sera emmurée dans une caverne — peine qu'elle devance en se suicidant."},
    {q:"La pièce d'Anouilh oppose la loi ___ à la loi des hommes.",ans:"divine",exp:"Antigone revendique une loi supérieure, divine et naturelle, contre la loi politique de Créon."},
   ]},
  // ── OEUVRES LITTERAIRES Terminale ──
  {id:"j_tle_huis_clos_qcm",titre:"Huis Clos (Sartre) — Quiz Tle",emoji:"🔐",matiere:"Litterature",niveau:"Terminale",
   desc:"QCM sur Huis Clos de Jean-Paul Sartre",gratuit:true,type:"qcm",action:"lancerJLitLTle_huis_clos",
   questions:[
    {q:"Qui est l'auteur de 'Huis Clos' ?",opts:["Albert Camus","Jean Anouilh","Jean-Paul Sartre","Simone de Beauvoir"],ans:2,exp:"Jean-Paul Sartre (1905-1980), philosophe existentialiste et dramaturge français. Pièce créée en 1944."},
    {q:"Quelle est la célèbre formule de 'Huis Clos' ?",opts:["'Je pense donc je suis'","'L'enfer, c'est les Autres'","'L'existence précède l'essence'","'Dieu est mort'"],ans:1,exp:"'L'enfer, c'est les Autres' : les personnages se torturent mutuellement pour l'éternité."},
    {q:"Combien de personnages principaux y a-t-il dans 'Huis Clos' ?",opts:["2","3","4","5"],ans:1,exp:"Trois personnages : Garcin, Inès et Estelle, enfermés dans un salon d'hôtel — leur enfer."},
    {q:"Qu'est-ce que le lieu de 'Huis Clos' représente ?",opts:["Une prison ordinaire","Un hôpital psychiatrique","L'enfer sous forme d'un salon d'hôtel","Le paradis"],ans:2,exp:"L'enfer est représenté comme un salon bourgeois banal — ni flammes ni torture physique, seulement la présence des autres."},
    {q:"Quel courant philosophique 'Huis Clos' illustre-t-il ?",opts:["Le structuralisme","L'existentialisme","Le marxisme","Le surréalisme"],ans:1,exp:"L'existentialisme sartrien : l'existence précède l'essence, l'homme est condamné à être libre et défini par ses actes."},
    {q:"Pourquoi les personnages ne peuvent-ils pas dormir ?",opts:["La lumière ne s'éteint jamais","Ils ont peur","Le bruit les empêche","La pièce est trop froide"],ans:0,exp:"La lumière électrique est constamment allumée — pas de sommeil, pas de répit, pas de fuite dans l'inconscience."},
   ]},
  {id:"j_tle_bouts_bois_qcm",titre:"Les Bouts de Bois de Dieu — Quiz Tle",emoji:"✊",matiere:"Litterature",niveau:"Terminale",
   desc:"Quiz approfondi sur Sembène Ousmane pour la Terminale",gratuit:true,type:"qcm",action:"lancerJLitLTle_bouts_bois",
   questions:[
    {q:"Quelle ville est le point de départ de la marche des femmes ?",opts:["Dakar","Saint-Louis","Thiès","Bamako"],ans:2,exp:"Les femmes partent de Thiès pour rejoindre Dakar à pied, symbole de résistance collective."},
    {q:"Qui est Penda dans le roman ?",opts:["La femme du chef syndicaliste","Une femme courageuse qui mène la marche","La secrétaire de l'administration","Une institutrice"],ans:1,exp:"Penda est une figure féminine centrale : rebelle, forte, elle dirige la marche des femmes de Thiès à Dakar."},
    {q:"Que signifie l'expression wolof 'Bouts de Bois de Dieu' ?",opts:["Les locomotives","Les rails du chemin de fer","Les êtres humains, créés égaux par Dieu","Les bâtons des policiers"],ans:2,exp:"Proverbe wolof : tous les hommes sont des 'bouts de bois de Dieu' — égaux en dignité devant le Créateur."},
    {q:"Quel personnage représente la jeunesse tiraillée entre tradition et modernité ?",opts:["Bakayoko","N'Deye Touti","Ramatoulaye","Lahbib"],ans:1,exp:"N'Deye Touti est instruite, admiratrice de la culture française, mais finit par rejoindre la lutte collective."},
    {q:"Comment se termine la grève ?",opts:["Par un échec total","Par une victoire partielle des grévistes","Par l'arrestation de tous les leaders","Par une répression militaire définitive"],ans:1,exp:"Les cheminots obtiennent des avancées (alignement des salaires) — victoire symbolique qui préfigure l'indépendance."},
   ]},
  {id:"j_tle_ville_cruelle_qcm",titre:"Ville Cruelle (Mongo Beti) — Quiz Tle",emoji:"🌆",matiere:"Litterature",niveau:"Terminale",
   desc:"QCM sur Ville Cruelle de Mongo Beti au programme Terminale",gratuit:true,type:"qcm",action:"lancerJLitLTle_ville_cruelle",
   questions:[
    {q:"Quel est le vrai nom de Mongo Beti ?",opts:["Ferdinand Oyono","Alexandre Biyidi-Awala","Rene Philombe","Patrice Ndedi Penda"],ans:1,exp:"Alexandre Biyidi-Awala, né à Mbalmayo (Cameroun) en 1932. Mongo Beti est son pseudonyme littéraire."},
    {q:"De quel pays est originaire Mongo Beti ?",opts:["Sénégal","Guinée","Cameroun","Congo"],ans:2,exp:"Mongo Beti est camerounais. Il est considéré comme l'un des pères de la littérature africaine francophone."},
    {q:"Quel est le thème central de 'Ville Cruelle' ?",opts:["L'amour impossible","L'exploitation coloniale et la corruption","La tradition orale africaine","La guerre de libération"],ans:1,exp:"Le roman dénonce l'exploitation économique coloniale, la corruption et la violence de la ville africaine colonisée."},
    {q:"Quel est le nom du personnage principal de 'Ville Cruelle' ?",opts:["Meka","Banda","Laye","Medza"],ans:1,exp:"Banda est un jeune paysan camerounais qui affronte la brutalité du système colonial pour vendre son cacao."},
    {q:"'Ville Cruelle' a d'abord été publié sous quel pseudonyme ?",opts:["Mongo Beti","Eza Boto","Alexandre Biyidi","Ferdinand Oyono"],ans:1,exp:"Publié en 1954 sous le pseudonyme 'Eza Boto' avant que Mongo Beti ne soit définitivement adopté."},
   ]},
  {id:"j_tle_vf_lit",titre:"Littérature Terminale — Vrai / Faux",emoji:"✅",matiere:"Litterature",niveau:"Terminale",
   desc:"Vrai ou Faux sur les œuvres littéraires au programme de Terminale",gratuit:true,type:"vf",action:"lancerJLitVFTle",
   questions:[
    {q:"'Huis Clos' de Sartre illustre le courant existentialiste.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. La formule 'L'enfer, c'est les Autres' résume la vision existentialiste sartriennes de la liberté et de l'altérité."},
    {q:"Mongo Beti est sénégalais.",opts:["Vrai","Faux"],ans:1,exp:"Faux. Mongo Beti (Alexandre Biyidi) est camerounais, né à Mbalmayo en 1932."},
    {q:"Dans 'Huis Clos', les personnages peuvent dormir pour s'échapper.",opts:["Vrai","Faux"],ans:1,exp:"Faux. La lumière reste allumée en permanence — aucun répit possible."},
    {q:"'Ville Cruelle' dénonce l'exploitation coloniale au Cameroun.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Banda, le héros, subit la violence économique et morale du système colonial dans la ville."},
    {q:"Sembène Ousmane est à la fois romancier et cinéaste.",opts:["Vrai","Faux"],ans:0,exp:"Vrai. Il est le père du cinéma africain, auteur de films comme 'Xala' et 'Mandabi'."},
   ]},
  {id:"j_tle_lit_trous",titre:"Littérature Terminale — Texte à trous",emoji:"✍️",matiere:"Litterature",niveau:"Terminale",
   desc:"Complétez les phrases sur les œuvres de Terminale",gratuit:true,type:"trous",action:"lancerJLitTTle",
   questions:[
    {q:"L'auteur de 'Huis Clos' est Jean-Paul ___.",ans:"Sartre",exp:"Sartre (1905-1980), philosophe et dramaturge existentialiste."},
    {q:"La célèbre formule de Huis Clos est : 'L'enfer, c'est les ___'.",ans:"Autres",exp:"Cette formule résume l'idée que le regard des autres nous objectifie et nous emprisonne."},
    {q:"Le personnage principal de 'Ville Cruelle' se nomme ___.",ans:"Banda",exp:"Banda est un jeune paysan qui tente de vendre son cacao dans la ville coloniale."},
    {q:"'Les Bouts de Bois de Dieu' est une expression ___ qui signifie 'les hommes'.",ans:"wolof",exp:"Proverbe wolof : tous les êtres humains sont des 'bouts de bois de Dieu', égaux en dignité."},
    {q:"Mongo Beti a d'abord publié sous le pseudonyme Eza ___.",ans:"Boto",exp:"'Ville Cruelle' fut publié en 1954 sous 'Eza Boto', avant l'adoption définitive de 'Mongo Beti'."},
   ]},
  // ══════════════════════════════════════════════════════════════
  // ── NOUVEAUX JEUX v1.0 ── (Mathématiques, Sciences, Langues, Histoire du Cameroun)
  // ══════════════════════════════════════════════════════════════
  {id:"j_verbes_ang",titre:"Verbes Irréguliers Anglais",emoji:"🇬🇧",matiere:"Anglais",niveau:"6eme-Tle",
   desc:"Trouvez le prétérit et le participe passé des verbes irréguliers fréquents",gratuit:true,type:"qcm",action:"lancerJVerbesAng",
   questions:[
    {q:"Prétérit et participe passé de 'to be' ?",opts:["was/were - been","is - is","were - been","am - being"],ans:0,exp:"was/were (prétérit selon sujet) — been (participe passé). Ex: I was, you were, I have been."},
    {q:"Prétérit et participe passé de 'to go' ?",opts:["goed - goed","went - gone","gone - went","goes - going"],ans:1,exp:"went (prétérit irrégulier) — gone (participe passé). Ex: I went yesterday, I have gone home."},
    {q:"Prétérit de 'to buy' ?",opts:["buyed","bought","buied","bougt"],ans:1,exp:"bought. Se prononce /bɔːt/. Même forme au participe passé."},
    {q:"Participe passé de 'to write' ?",opts:["writed","wrote","written","writing"],ans:2,exp:"written. Prétérit = wrote, participe passé = written. Ex: I have written a letter."},
    {q:"Prétérit de 'to eat' ?",opts:["eated","ate","eaten","eat"],ans:1,exp:"ate (prétérit). Le participe passé est eaten. I ate an apple. I have eaten."},
    {q:"Participe passé de 'to take' ?",opts:["took","taked","taken","taking"],ans:2,exp:"taken. Prétérit = took, participe passé = taken. Ex: She has taken the book."},
    {q:"Prétérit de 'to see' ?",opts:["seed","seen","saw","see"],ans:2,exp:"saw (prétérit) — seen (participe passé). I saw a lion. I have seen it."},
    {q:"Prétérit et participe passé de 'to put' ?",opts:["put - put","putted - putted","puted - puted","put - putted"],ans:0,exp:"put — put — put (3 formes identiques). Autres verbes similaires : cut, hit, let, set."},
   ]},
  {id:"j_capitales_afrique",titre:"Capitales d'Afrique",emoji:"🌍",matiere:"Histoire-Geo",niveau:"6eme-Tle",
   desc:"Retrouvez les capitales des pays africains",gratuit:true,type:"qcm",action:"lancerJCapitalesAfr",
   questions:[
    {q:"Capitale du Cameroun ?",opts:["Douala","Yaoundé","Bafoussam","Garoua"],ans:1,exp:"Yaoundé est la capitale politique. Douala est la capitale économique et le principal port."},
    {q:"Capitale du Sénégal ?",opts:["Thiès","Saint-Louis","Dakar","Kaolack"],ans:2,exp:"Dakar, située sur la presqu'île du Cap-Vert, est la capitale et principale ville du Sénégal."},
    {q:"Capitale de la Côte d'Ivoire ?",opts:["Abidjan","Yamoussoukro","Bouaké","San-Pedro"],ans:1,exp:"Yamoussoukro est la capitale politique depuis 1983. Abidjan reste la capitale économique."},
    {q:"Capitale du Nigeria ?",opts:["Lagos","Kano","Abuja","Ibadan"],ans:2,exp:"Abuja est la capitale depuis 1991. Lagos reste la plus grande ville du pays (et d'Afrique)."},
    {q:"Capitale de l'Éthiopie ?",opts:["Addis-Abeba","Asmara","Djibouti","Mogadiscio"],ans:0,exp:"Addis-Abeba, siège de l'Union Africaine, située sur un plateau à 2400m d'altitude."},
    {q:"Capitale du Gabon ?",opts:["Port-Gentil","Libreville","Franceville","Oyem"],ans:1,exp:"Libreville, fondée en 1849 par des esclaves libérés (d'où son nom)."},
    {q:"Capitale du Tchad ?",opts:["Moundou","N'Djamena","Sarh","Abéché"],ans:1,exp:"N'Djamena, située au confluent du Chari et du Logone, à la frontière avec le Cameroun."},
    {q:"Capitale de la République Démocratique du Congo ?",opts:["Brazzaville","Kinshasa","Lubumbashi","Kisangani"],ans:1,exp:"Kinshasa (RDC). Ne pas confondre avec Brazzaville (République du Congo), situées face à face sur le fleuve Congo."},
    {q:"Capitale du Rwanda ?",opts:["Bujumbura","Kigali","Kampala","Nairobi"],ans:1,exp:"Kigali, située au centre du pays, bâtie sur plusieurs collines."},
    {q:"Capitale du Maroc ?",opts:["Casablanca","Marrakech","Fès","Rabat"],ans:3,exp:"Rabat est la capitale politique. Casablanca est la capitale économique et plus grande ville."},
   ]},
  {id:"j_histoire_cmr",titre:"Histoire du Cameroun — Dates-clés",emoji:"🇨🇲",matiere:"Histoire-Geo",niveau:"3eme-Tle",
   desc:"Testez vos connaissances sur l'histoire du Cameroun",gratuit:true,type:"qcm",action:"lancerJHistCmr",
   questions:[
    {q:"En quelle année le Cameroun obtient-il son indépendance ?",opts:["1958","1960","1961","1972"],ans:1,exp:"1er janvier 1960 : indépendance du Cameroun sous tutelle française. Ahmadou Ahidjo devient le premier président."},
    {q:"Qui fut le premier président du Cameroun indépendant ?",opts:["Paul Biya","Ahmadou Ahidjo","Ruben Um Nyobé","John Ngu Foncha"],ans:1,exp:"Ahmadou Ahidjo (1960-1982), premier président de la République du Cameroun."},
    {q:"En quelle année Paul Biya accède-t-il au pouvoir ?",opts:["1975","1982","1984","1990"],ans:1,exp:"6 novembre 1982 : Paul Biya succède à Ahmadou Ahidjo qui démissionne."},
    {q:"Qui était le leader de l'UPC assassiné en 1958 ?",opts:["Félix Moumié","Ruben Um Nyobé","Ernest Ouandié","Osendé Afana"],ans:1,exp:"Ruben Um Nyobé, fondateur et secrétaire général de l'UPC, assassiné le 13 septembre 1958 dans le maquis."},
    {q:"En quelle année a eu lieu la réunification du Cameroun français et anglais ?",opts:["1960","1961","1972","1984"],ans:1,exp:"1er octobre 1961 : réunification avec le Southern Cameroons (partie anglaise) suite au référendum du 11 février 1961."},
    {q:"Quel était le nom du Cameroun sous la République Unie ?",opts:["Kamerun","République Fédérale","République Unie du Cameroun","État du Cameroun"],ans:2,exp:"De 1972 à 1984 : République Unie du Cameroun. En 1984, elle devient la République du Cameroun."},
    {q:"Quel fleuve sépare traditionnellement le Grand Nord du Grand Sud ?",opts:["La Sanaga","Le Mbam","Le Wouri","Le Nyong"],ans:0,exp:"La Sanaga, plus long fleuve du Cameroun (918 km), sépare symboliquement les grandes régions."},
    {q:"En quelle année le multipartisme est-il rétabli au Cameroun ?",opts:["1990","1991","1992","1996"],ans:0,exp:"Loi du 19 décembre 1990 sur la liberté d'association, permettant la création de partis politiques."},
   ]},
  {id:"j_formules_phys",titre:"Formules de Physique",emoji:"⚡",matiere:"Physique-Chimie",niveau:"3eme-Tle",
   desc:"Retrouvez les formules fondamentales de physique",gratuit:true,type:"qcm",action:"lancerJFormulesPhys",
   questions:[
    {q:"Formule de la vitesse (mouvement rectiligne uniforme) ?",opts:["v = m/V","v = d × t","v = d / t","v = F × a"],ans:2,exp:"v = d/t où d = distance (m), t = temps (s), v = vitesse (m/s). Unités SI : mètres par seconde."},
    {q:"Loi d'Ohm ?",opts:["U = R × I","U = R + I","U = R / I","U = I / R"],ans:0,exp:"U = R × I où U = tension (V), R = résistance (Ω), I = intensité (A). Georg Simon Ohm, 1827."},
    {q:"Formule de l'énergie cinétique ?",opts:["Ec = m × v","Ec = m × g × h","Ec = (1/2) × m × v²","Ec = m × a²"],ans:2,exp:"Ec = ½ m v² où m = masse (kg), v = vitesse (m/s). Unité : joule (J)."},
    {q:"Formule de l'énergie potentielle de pesanteur ?",opts:["Ep = m × v²","Ep = m × g × h","Ep = F × d","Ep = (1/2) × k × x²"],ans:1,exp:"Ep = mgh où m = masse (kg), g ≈ 9,81 m/s² (Cameroun), h = hauteur (m)."},
    {q:"Deuxième loi de Newton ?",opts:["F = m + a","F = m / a","F = m × a","F = m × v²"],ans:2,exp:"F = m × a (Principe Fondamental de la Dynamique). F en Newton, m en kg, a en m/s²."},
    {q:"Formule de la puissance électrique ?",opts:["P = U / I","P = U × I","P = U + I","P = U² × I"],ans:1,exp:"P = U × I en Watts. Pour une résistance pure : P = RI² = U²/R."},
    {q:"Formule de la force de gravitation universelle ?",opts:["F = G × m × m'","F = G × (m × m') / r²","F = m × g","F = G / r²"],ans:1,exp:"F = G × m × m' / r² (loi de Newton). G = 6,67×10⁻¹¹ N·m²/kg²."},
    {q:"Quantité de mouvement ?",opts:["p = m × v","p = m × a","p = (1/2) × m × v²","p = F × t"],ans:0,exp:"p = mv (vecteur). En mécanique relativiste : p = γmv."},
   ]},
  {id:"j_equations",titre:"Équations du 2nd degré",emoji:"📐",matiere:"Maths",niveau:"1ere-Tle",
   desc:"Résolvez des équations du second degré ax² + bx + c = 0",gratuit:true,type:"qcm",action:"lancerJEquations",
   questions:[
    {q:"Solutions de x² - 5x + 6 = 0 ?",opts:["x = 1 ou x = 6","x = 2 ou x = 3","x = -2 ou x = -3","x = 0 ou x = 5"],ans:1,exp:"Δ = 25 - 24 = 1. x = (5±1)/2 donc x=3 ou x=2. Vérification : 2×3=6 et 2+3=5 ✓"},
    {q:"Discriminant de 2x² + 3x - 5 = 0 ?",opts:["Δ = 9 - 40 = -31","Δ = 9 + 40 = 49","Δ = 9 - 20 = -11","Δ = 9 + 10 = 19"],ans:1,exp:"Δ = b² - 4ac = 9 - 4(2)(-5) = 9 + 40 = 49. Δ > 0 donc 2 solutions réelles."},
    {q:"Combien de solutions a x² + 4x + 4 = 0 ?",opts:["0","1 (double)","2","Infini"],ans:1,exp:"Δ = 16 - 16 = 0. Solution double x = -2. C'est (x+2)² = 0, racine double."},
    {q:"Si Δ < 0, combien de solutions réelles ?",opts:["0","1","2","Ça dépend"],ans:0,exp:"Δ < 0 : aucune solution réelle. Mais 2 solutions complexes conjuguées (hors programme Tle D)."},
    {q:"Somme des racines de x² - 7x + 12 = 0 ?",opts:["5","7","12","-7"],ans:1,exp:"Somme = -b/a = 7. Produit = c/a = 12. Les racines sont 3 et 4 (3+4=7 ✓)."},
    {q:"Produit des racines de 2x² - 10x + 8 = 0 ?",opts:["5","4","8","-4"],ans:1,exp:"Produit = c/a = 8/2 = 4. Somme = -b/a = 10/2 = 5. Racines : 1 et 4."},
    {q:"Racine de x² = 49 ?",opts:["7 seulement","-7 seulement","7 ou -7","14"],ans:2,exp:"x² = 49 équivaut à |x| = 7, donc x = 7 ou x = -7. Toujours les deux signes !"},
   ]},
  {id:"j_svt_anatomie",titre:"Anatomie Humaine",emoji:"🫀",matiere:"SVT",niveau:"4eme-Tle",
   desc:"Testez vos connaissances sur le corps humain",gratuit:true,type:"qcm",action:"lancerJAnatomie",
   questions:[
    {q:"Combien d'os compte le squelette humain adulte ?",opts:["186","206","256","306"],ans:1,exp:"206 os chez l'adulte. Le nouveau-né en a ~270, certains fusionnent avec la croissance."},
    {q:"Quel est le plus grand os du corps humain ?",opts:["Le tibia","L'humérus","Le fémur","La colonne vertébrale"],ans:2,exp:"Le fémur (os de la cuisse) : environ 45 cm chez l'adulte. Il représente ~¼ de la taille."},
    {q:"Combien de chambres compte le cœur humain ?",opts:["2","3","4","5"],ans:2,exp:"4 chambres : 2 oreillettes (en haut) et 2 ventricules (en bas). Séparation gauche/droite."},
    {q:"Quel organe produit l'insuline ?",opts:["Le foie","Le pancréas","La rate","Les reins"],ans:1,exp:"Le pancréas (cellules β des îlots de Langerhans). L'insuline régule la glycémie."},
    {q:"Combien de paires de chromosomes chez l'humain ?",opts:["21","22","23","46"],ans:2,exp:"23 paires = 46 chromosomes au total. 22 paires autosomes + 1 paire sexuelle (XX ou XY)."},
    {q:"Quel est le plus grand organe du corps humain ?",opts:["Le foie","Les poumons","La peau","Le cerveau"],ans:2,exp:"La peau ! Surface d'environ 2 m² chez l'adulte, poids ~4-5 kg. Organe sensoriel et protecteur."},
    {q:"Quelle partie du cerveau contrôle l'équilibre ?",opts:["Le cortex","Le cervelet","Le bulbe rachidien","L'hypothalamus"],ans:1,exp:"Le cervelet coordonne les mouvements et l'équilibre. Situé à l'arrière du crâne, sous le cortex."},
    {q:"Combien de globules rouges produit-on par seconde ?",opts:["~2 000","~200 000","~2 000 000","~20 000 000"],ans:2,exp:"~2 millions par seconde (moelle osseuse). Ils vivent ~120 jours avant destruction dans la rate."},
   ]},
  {id:"j_participe_passe",titre:"Accord du Participe Passé",emoji:"✏️",matiere:"Francais",niveau:"3eme-Tle",
   desc:"Règles d'accord du participe passé avec avoir et être",gratuit:true,type:"qcm",action:"lancerJParticipePasse",
   questions:[
    {q:"'Les pommes que j'ai ___ sont mûres.' (manger)",opts:["mangé","mangés","mangées","manger"],ans:2,exp:"mangées. Avec 'avoir' : accord avec le COD s'il est placé avant. 'que' = COD féminin pluriel (les pommes)."},
    {q:"'Elle est ___ hier.' (venir)",opts:["venu","venue","venues","venir"],ans:1,exp:"venue. Avec 'être' : accord avec le sujet. 'Elle' = féminin singulier."},
    {q:"'Ils se sont ___ la main.' (serrer)",opts:["serré","serrés","serrées","serrer"],ans:0,exp:"serré. Verbe pronominal : 'la main' est COD placé après → pas d'accord. 'se' est ici COI (à eux-mêmes)."},
    {q:"'Les enfants ont ___ dehors.' (courir)",opts:["courus","couru","courues","couri"],ans:1,exp:"couru. Avec 'avoir' sans COD placé avant → pas d'accord. Le verbe 'courir' (sans objet) ne s'accorde pas."},
    {q:"'Quelle belle robe tu as ___ !' (choisir)",opts:["choisi","choisie","choisis","choisir"],ans:1,exp:"choisie. COD ('quelle robe', féminin singulier) placé avant l'auxiliaire 'avoir' → accord obligatoire."},
    {q:"'Elles se sont ___ de bonne heure.' (lever)",opts:["levé","levées","levés","lever"],ans:1,exp:"levées. Verbe pronominal réfléchi : 'se' est COD (elles ont levé elles-mêmes) → accord avec le sujet féminin pluriel."},
    {q:"'Les lettres ont été ___ ce matin.' (envoyer)",opts:["envoyé","envoyés","envoyées","envoyer"],ans:2,exp:"envoyées. Voix passive (être) → accord avec le sujet 'les lettres' (féminin pluriel)."},
   ]},
  {id:"j_tables_multi",titre:"Tables de Multiplication Express",emoji:"✖️",matiere:"Maths",niveau:"6eme-3eme",
   desc:"Révisez vos tables de multiplication en vitesse",gratuit:true,type:"qcm",action:"lancerJTablesMulti",
   questions:[
    {q:"7 × 8 = ?",opts:["54","56","58","63"],ans:1,exp:"56. Astuce : 7×8 = 7×(10-2) = 70-14 = 56."},
    {q:"9 × 6 = ?",opts:["54","56","58","64"],ans:0,exp:"54. Astuce 9 : 9×6 = 10×6 - 6 = 60-6 = 54."},
    {q:"12 × 7 = ?",opts:["74","84","94","104"],ans:1,exp:"84. 12×7 = 10×7 + 2×7 = 70+14 = 84."},
    {q:"8 × 9 = ?",opts:["71","72","81","89"],ans:1,exp:"72. 8×9 = 72. Vérifier : 72/8 = 9 ✓"},
    {q:"11 × 11 = ?",opts:["111","121","122","131"],ans:1,exp:"121 = 11². À retenir : 11×11=121, 12×12=144, 13×13=169."},
    {q:"25 × 4 = ?",opts:["75","90","100","125"],ans:2,exp:"100. Astuce : 25 × 4 = 100 (un quart de cent × 4 = cent entier)."},
    {q:"15 × 6 = ?",opts:["80","85","90","95"],ans:2,exp:"90. 15×6 = 10×6 + 5×6 = 60 + 30 = 90."},
    {q:"13 × 7 = ?",opts:["81","91","93","97"],ans:1,exp:"91. 13×7 = 13×7. Astuce : (10+3)×7 = 70+21 = 91."},
   ]},
  {id:"j_auteurs_cmr",titre:"Auteurs Camerounais & Africains",emoji:"✒️",matiere:"Litterature",niveau:"3eme-Tle",
   desc:"Qui a écrit quoi ? Les grands auteurs d'Afrique francophone",gratuit:true,type:"qcm",action:"lancerJAuteursCmr",
   questions:[
    {q:"Qui a écrit 'Une vie de boy' ?",opts:["Mongo Beti","Ferdinand Oyono","Camara Laye","Sembène Ousmane"],ans:1,exp:"Ferdinand Oyono (1956). Satire mordante du colonialisme à travers Toundi, jeune 'boy' camerounais."},
    {q:"Auteur de 'Le Vieux Nègre et la Médaille' ?",opts:["Mongo Beti","Ferdinand Oyono","René Philombe","Francis Bebey"],ans:1,exp:"Ferdinand Oyono (1956). Publié la même année qu'Une vie de boy."},
    {q:"Qui a écrit 'L'Enfant Noir' ?",opts:["Camara Laye","Cheikh Hamidou Kane","Ahmadou Kourouma","Mongo Beti"],ans:0,exp:"Camara Laye (1953). Roman autobiographique, écrivain guinéen."},
    {q:"Auteur de 'L'Aventure ambiguë' ?",opts:["Léopold Senghor","Cheikh Hamidou Kane","Birago Diop","Aminata Sow Fall"],ans:1,exp:"Cheikh Hamidou Kane (1961), sénégalais. Prix littéraire d'Afrique noire."},
    {q:"'Les Soleils des indépendances' est de...",opts:["Sembène Ousmane","Ahmadou Kourouma","Léopold Senghor","Ken Bugul"],ans:1,exp:"Ahmadou Kourouma (1968), ivoirien. Dénonce les régimes postcoloniaux africains."},
    {q:"Qui a écrit 'Ville Cruelle' sous le pseudo Eza Boto ?",opts:["Mongo Beti","Ferdinand Oyono","René Philombe","Francis Bebey"],ans:0,exp:"Mongo Beti (1954). Son vrai nom : Alexandre Biyidi-Awala, camerounais."},
    {q:"Auteur de 'Les Bouts de Bois de Dieu' ?",opts:["Sembène Ousmane","Aminata Sow Fall","Ousmane Soce","Birago Diop"],ans:0,exp:"Sembène Ousmane (1960), sénégalais. Récit de la grève des cheminots Dakar-Niger (1947-48)."},
    {q:"Qui a écrit 'Rencontres essentielles', premier roman d'une femme camerounaise ?",opts:["Calixthe Beyala","Werewere Liking","Thérèse Kuoh-Moukoury","Léonora Miano"],ans:2,exp:"Thérèse Kuoh-Moukoury (1969), pionnière de la littérature féminine camerounaise."},
   ]},
  {id:"j_voc_svt",titre:"Vocabulaire Scientifique SVT",emoji:"🔬",matiere:"SVT",niveau:"4eme-Tle",
   desc:"Définitions et termes techniques en biologie",gratuit:true,type:"qcm",action:"lancerJVocSVT",
   questions:[
    {q:"Qu'est-ce que la photosynthèse ?",opts:["Respiration des plantes","Fabrication de matière organique à partir de lumière","Absorption d'eau par les racines","Chute des feuilles"],ans:1,exp:"Transformation de CO₂ + H₂O en glucose + O₂ grâce à la lumière (chlorophylle). 6CO₂+6H₂O → C₆H₁₂O₆+6O₂."},
    {q:"Les mitochondries sont responsables de...",opts:["La photosynthèse","La digestion","La production d'ATP (énergie)","La duplication de l'ADN"],ans:2,exp:"Mitochondries = 'centrales énergétiques' de la cellule. Elles produisent l'ATP par respiration cellulaire."},
    {q:"Que signifie ADN ?",opts:["Acide Désoxyribonucléique","Acide DiNucléique","Adénosine Di-Nitrate","Alcool Désodorisant Naturel"],ans:0,exp:"Acide Désoxyribonucléique. Double hélice découverte par Watson & Crick en 1953. Porte l'information génétique."},
    {q:"Un écosystème, c'est...",opts:["Un ensemble d'espèces","Un milieu et les êtres vivants qui l'habitent","Une forêt uniquement","Une population animale"],ans:1,exp:"Biotope (milieu physique) + biocénose (êtres vivants) = écosystème. Ex : mangrove du Wouri, forêt du Dja."},
    {q:"La méiose produit...",opts:["Des cellules identiques","Des gamètes (cellules sexuelles)","Des globules rouges","Des neurones"],ans:1,exp:"Méiose : division réductionnelle produisant 4 gamètes haploïdes (n=23) à partir d'une cellule diploïde (2n=46)."},
    {q:"L'homéostasie, c'est...",opts:["La reproduction","Le maintien de l'équilibre interne","La mort cellulaire","La croissance"],ans:1,exp:"Homéostasie = capacité d'un organisme à maintenir ses constantes internes (température, pH, glycémie...)."},
    {q:"Que sont les enzymes ?",opts:["Des hormones","Des protéines catalyseurs","Des vitamines","Des sucres"],ans:1,exp:"Protéines qui accélèrent les réactions chimiques sans être consommées. Ex : amylase (digestion amidon)."},
    {q:"Les neurones communiquent par...",opts:["Les synapses","Les muscles","Les os","Le sang"],ans:0,exp:"Synapses : zones de contact entre neurones où sont libérés les neurotransmetteurs (dopamine, sérotonine...)."},
   ]},
  {id:'j_lois_physique',titre:'Lois de Physique-Chimie',emoji:'⚡',matiere:'Physique-Chimie',niveau:'2nde-Tle',type:'qcm',acces:1,
    questions:[
      {q:'Quelle est la loi d\'Ohm ?',opts:['U = R × I','U = I / R','I = U × R','R = U × I²'],ans:0,exp:'La loi d\'Ohm : U = R × I, où U est la tension (V), R la résistance (Ω) et I l\'intensité (A).'},
      {q:'Quelle est la 2ème loi de Newton ?',opts:['F = m × a','F = m / a','a = F / m²','F = m + a'],ans:0,exp:'La 2ème loi de Newton : F = m × a. La force (N) = masse (kg) × accélération (m/s²).'},
      {q:'Formule de la vitesse',opts:['v = d / t','v = d × t','v = t / d','v = d + t'],ans:0,exp:'Vitesse = distance / temps. En m/s ou km/h.'},
      {q:'Formule de l\'énergie cinétique',opts:['Ec = ½mv²','Ec = mv²','Ec = ½mv','Ec = mv/2²'],ans:0,exp:'Énergie cinétique : Ec = ½mv². m en kg, v en m/s, Ec en joules.'},
      {q:'Formule de la puissance électrique',opts:['P = U × I','P = U / I','P = I / U','P = U + I'],ans:0,exp:'Puissance électrique P = U × I, exprimée en watts (W).'},
      {q:'La réaction acido-basique met en jeu',opts:['Un transfert de proton H⁺','Un transfert d\'électron','Une fusion nucléaire','Un changement d\'état'],ans:0,exp:'La réaction acido-basique est un transfert de proton (H⁺) d\'un acide vers une base.'},
      {q:'Formule de la chaleur reçue (calorimétrie)',opts:['Q = m × c × ΔT','Q = m / c × ΔT','Q = m × c / ΔT','Q = c × ΔT²'],ans:0,exp:'Q = m × c × ΔT. m : masse (kg), c : capacité thermique massique, ΔT : variation de température.'},
      {q:'Qu\'est-ce que la période T d\'un phénomène périodique ?',opts:['La durée d\'un cycle','La fréquence en Hz','L\'amplitude','La longueur d\'onde'],ans:0,exp:'La période T est la durée d\'un cycle complet, exprimée en secondes.'}
    ]},
  {id:'j_regions_cmr',titre:'Régions du Cameroun',emoji:'🗺️',matiere:'Géographie',niveau:'6ème-Tle',type:'qcm',acces:1,
    questions:[
      {q:'Combien de régions compte le Cameroun ?',opts:['10','8','12','9'],ans:0,exp:'Le Cameroun est divisé en 10 régions depuis la réforme administrative.'},
      {q:'Quelle est la capitale de la région du Centre ?',opts:['Yaoundé','Bertoua','Bafoussam','Ngaoundéré'],ans:0,exp:'Yaoundé est la capitale politique du Cameroun et le chef-lieu de la région du Centre.'},
      {q:'Quelle région est traversée par le fleuve Sanaga ?',opts:['Centre et Littoral','Nord et Extrême-Nord','Est et Sud','Adamaoua et Nord-Ouest'],ans:0,exp:'Le Sanaga, plus long fleuve du Cameroun, traverse les régions du Centre et du Littoral.'},
      {q:'La région du Littoral a pour chef-lieu',opts:['Douala','Kribi','Edéa','Nkongsamba'],ans:0,exp:'Douala, capitale économique du Cameroun, est le chef-lieu de la région du Littoral.'},
      {q:'Quelle région partage une frontière avec le Nigeria au nord-ouest ?',opts:['Nord-Ouest','Adamaoua','Nord','Centre'],ans:0,exp:'La région du Nord-Ouest est frontalière avec le Nigeria.'},
      {q:'La région de l\'Est a pour chef-lieu',opts:['Bertoua','Abong-Mbang','Batouri','Yokadouma'],ans:0,exp:'Bertoua est le chef-lieu de la région de l\'Est.'},
      {q:'Le mont Cameroun se trouve dans quelle région ?',opts:['Sud-Ouest','Littoral','Nord-Ouest','Centre'],ans:0,exp:'Le mont Cameroun (4 095 m), plus haut sommet d\'Afrique centrale, est situé dans la région du Sud-Ouest.'},
      {q:'Quelle région est la plus grande du Cameroun ?',opts:['Est','Nord','Adamaoua','Centre'],ans:0,exp:'La région de l\'Est est la plus grande région du Cameroun avec environ 109 000 km².'}
    ]},
  {id:'j_maths_fonctions',titre:'Fonctions & Dérivées — Maths Tle',emoji:'📐',matiere:'Mathématiques',niveau:'Tle',type:'qcm',acces:1,
    questions:[
      {q:'La dérivée de f(x) = x² est',opts:['f\'(x) = 2x','f\'(x) = x','f\'(x) = 2','f\'(x) = x²'],ans:0,exp:'Règle de dérivation : si f(x) = xⁿ alors f\'(x) = n·xⁿ⁻¹. Donc (x²)\' = 2x.'},
      {q:'La dérivée de f(x) = sin(x) est',opts:['f\'(x) = cos(x)','f\'(x) = -cos(x)','f\'(x) = -sin(x)','f\'(x) = tan(x)'],ans:0,exp:'(sin x)\' = cos x. Règle fondamentale à mémoriser.'},
      {q:'La dérivée de f(x) = eˣ est',opts:['f\'(x) = eˣ','f\'(x) = x·eˣ','f\'(x) = e','f\'(x) = eˣ⁻¹'],ans:0,exp:'La fonction exponentielle est sa propre dérivée : (eˣ)\' = eˣ.'},
      {q:'La dérivée de f(x) = ln(x) est',opts:['f\'(x) = 1/x','f\'(x) = 1/x²','f\'(x) = ln(x)/x','f\'(x) = x·ln(x)'],ans:0,exp:'(ln x)\' = 1/x pour x > 0.'},
      {q:'Si f\'(x) > 0 sur un intervalle, f est',opts:['Croissante','Décroissante','Constante','Nulle'],ans:0,exp:'Si la dérivée est positive, la fonction est croissante sur cet intervalle.'},
      {q:'∫x dx = ?',opts:['x²/2 + C','x² + C','2x + C','x/2 + C'],ans:0,exp:'Primitive de x : ∫x dx = x²/2 + C, où C est la constante d\'intégration.'},
      {q:'La dérivée de f(x) = cos(x) est',opts:['f\'(x) = -sin(x)','f\'(x) = sin(x)','f\'(x) = -cos(x)','f\'(x) = tan(x)'],ans:0,exp:'(cos x)\' = -sin x. Attention au signe !'},
      {q:'Le nombre dérivé f\'(a) représente',opts:['La pente de la tangente en a','La valeur de f en a','L\'ordonnée à l\'origine','La limite de f en +∞'],ans:0,exp:'f\'(a) est la pente (coefficient directeur) de la tangente à la courbe de f au point d\'abscisse a.'}
    ]},
  {id:'j_svt_genetique',titre:'Génétique & Hérédité — SVT',emoji:'🧬',matiere:'SVT',niveau:'1ère-Tle',type:'qcm',acces:1,
    questions:[
      {q:'Quel scientifique est le fondateur de la génétique ?',opts:['Gregor Mendel','Charles Darwin','Louis Pasteur','Robert Koch'],ans:0,exp:'Gregor Mendel (1822-1884), moine botaniste autrichien, a établi les lois de l\'hérédité après ses expériences sur les petits pois.'},
      {q:'Combien de chromosomes contient une cellule somatique humaine ?',opts:['46','23','48','44'],ans:0,exp:'Les cellules somatiques humaines contiennent 46 chromosomes (23 paires), dont 22 paires d\'autosomes et 1 paire de chromosomes sexuels.'},
      {q:'Un individu de génotype Aa est dit',opts:['Hétérozygote','Homozygote dominant','Homozygote récessif','Haploïde'],ans:0,exp:'Un individu avec deux allèles différents (Aa) est hétérozygote. AA est homozygote dominant, aa est homozygote récessif.'},
      {q:'La méiose produit des cellules',opts:['Haploïdes (n chromosomes)','Diploïdes (2n chromosomes)','Triploïdes','Sans chromosomes'],ans:0,exp:'La méiose est une division qui réduit de moitié le nombre de chromosomes pour produire des gamètes haploïdes (n).'},
      {q:'L\'ADN est composé de',opts:['Nucléotides','Acides aminés','Glucides','Lipides'],ans:0,exp:'L\'ADN est un polynucléotide formé de nucléotides, chacun composé d\'un sucre (désoxyribose), d\'un groupement phosphate et d\'une base azotée (A, T, G, C).'},
      {q:'Les chromosomes sexuels chez la femme sont',opts:['XX','XY','YY','X seulement'],ans:0,exp:'La femme possède deux chromosomes X (XX) ; l\'homme possède un X et un Y (XY).'},
      {q:'L\'ARN messager est synthétisé lors de',opts:['La transcription','La traduction','La réplication','La mitose'],ans:0,exp:'La transcription est la synthèse d\'ARNm à partir de l\'ADN, dans le noyau cellulaire.'},
      {q:'Une mutation est',opts:['Une modification permanente de l\'ADN','Une division cellulaire','Une protéine défectueuse','Un type de mitose'],ans:0,exp:'Une mutation est une modification permanente de la séquence d\'ADN qui peut être héréditaire si elle touche les cellules germinales.'}
    ]}
]);
window._VRT_JEUX_OK = true;
