/* VÉRITAS — base des laboratoires virtuels (chargée à la demande).
   88 Ko qu'un visiteur venu lire un corrigé n'ouvrira jamais. Chargée par
   _lazyChunk('labo') depuis showLabosVirtuels() et les écrans qui en
   dépendent. Extraite d'app.js le 04/08/2026. */
window.LABO_DB=[
  // ─ PHYSIQUE ─
  {id:"lv1",titre:"Circuit Électrique Interactif",matiere:"Physique",cat:"physique",
   classe:"4ème-3ème-2nde",ico:"⚡",color:"#0891B2",gratuit:true,
   desc:"Construis et teste des circuits en série et parallèle. Calcule tension, intensité, résistance et puissance.",
   theorie:"⚡ Loi d'Ohm : U = R × I (U=Volts, R=Ohms, I=Ampères).\n\n🔴 Série : I identique partout. U_total = U₁+U₂. R_eq = R₁+R₂.\n🔵 Parallèle : U identique partout. I_total = I₁+I₂. 1/R_eq = 1/R₁+1/R₂.\n\n⚙️ Puissance : P = U×I = R×I² = U²/R (Watts).\nÉnergie : E = P×t (Joules). 1 kWh = 3 600 000 J.\n\nLois de Kirchhoff : ΣU = 0 dans une maille ; ΣI = 0 dans un nœud.",
   experience:[
     "1️⃣ MATÉRIEL : pile plate (4,5V), 2 ampoules, fils, interrupteur, ampèremètre, voltmètre. Branche l'interrupteur et observe : circuit ouvert → ampoule éteinte ; circuit fermé → ampoule allumée.",
     "2️⃣ CIRCUIT EN SÉRIE : branche 2 ampoules l'une après l'autre. Observe : les deux s'allument avec la même intensité. Débranche l'une → l'autre s'éteint aussi. Conclusion : en série, I identique et la panne d'une coupe tout.",
     "3️⃣ CIRCUIT EN PARALLÈLE : branche 2 ampoules côte à côte (en dérivation). Observe : chacune a la même tension. Débranche l'une → l'autre reste allumée. Conclusion : en parallèle, les appareils fonctionnent indépendamment.",
     "4️⃣ AMPÈREMÈTRE (mesure I) : branche-le EN SÉRIE dans le circuit. Il doit être traversé par le courant. Si la valeur est négative, inverse les bornes + et −.",
     "5️⃣ VOLTMÈTRE (mesure U) : branche-le EN PARALLÈLE aux bornes de l'ampoule. Il ne doit pas modifier le circuit. Relève la tension et vérifie U = R×I.",
     "6️⃣ LOI D'OHM (vérification) : mesure U aux bornes d'une résistance connue (ex. 100Ω) et I dans le circuit. Calcule R=U/I. Compare avec la valeur inscrite sur la résistance.",
     "7️⃣ SCHÉMA ÉLECTRIQUE : dessine le schéma normalisé du circuit (symboles : pile = ⏃, résistance = ▭, ampoule = ⊗, interrupteur = / ). Utilise une règle et des symboles normalisés (norme française).",
   ],
   quiz:[
     {q:"Si U=12V et R=400Ω, quelle est l'intensité ?",opts:["0,02 A","0,03 A","0,06 A","0,12 A"],ans:1,exp:"I = U/R = 12/400 = 0,03 A. Loi d'Ohm : I = U/R."},
     {q:"R₁=100Ω et R₂=150Ω en série. Résistance équivalente :",opts:["50 Ω","75 Ω","250 Ω","15 000 Ω"],ans:2,exp:"Série : R_eq = R₁+R₂ = 100+150 = 250 Ω."},
     {q:"En parallèle, la tension aux bornes de chaque branche est :",opts:["Différente","La même","Nulle","Double"],ans:1,exp:"En parallèle, U est identique à chaque branche — c'est pourquoi les appareils domestiques sont montés en parallèle."},
     {q:"U=220V, R=1100Ω. Puissance dissipée :",opts:["0,2 W","44 W","200 W","2420 W"],ans:1,exp:"P = U²/R = 220²/1100 = 48400/1100 = 44 W."},
     {q:"R₁=R₂=200Ω en parallèle. R_eq = ?",opts:["400 Ω","200 Ω","100 Ω","50 Ω"],ans:2,exp:"1/R_eq = 1/200+1/200 = 2/200 → R_eq = 100 Ω. En parallèle, R_eq < plus petite résistance."},
     {q:"3 résistances identiques en série, générateur 9V. Tension aux bornes de chacune :",opts:["9V","6V","3V","1V"],ans:2,exp:"En série la tension se divise : U_chacune = 9/3 = 3V."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv2",titre:"Les Forces et le Mouvement",matiere:"Physique",cat:"physique",
   classe:"2nde-1ère",ico:"🚀",color:"#1E3A8A",gratuit:true,
   desc:"Lois de Newton, poids, chute libre, énergie mécanique et forces de frottement. Programme 2nde–1ère.",
   theorie:"📌 1ère loi (inertie) : si les forces se compensent, l'objet est immobile ou en MRU.\n📌 2ème loi : ΣF = m×a (F en Newtons, m en kg, a en m/s²).\n📌 3ème loi : action = réaction (forces égales et opposées sur deux corps différents).\n\n⬇️ Chute libre (sans frottement) : h = ½gt² ; v = gt (g = 10 m/s² en 2nde).\n🔴 Poids : P = mg. ATTENTION : masse (kg) ≠ poids (Newton) !\n\n2nde : identifier les forces, calculer résultante, MRU/MRUV.\n1ère : énergie cinétique Ec = ½mv² ; énergie potentielle Ep = mgh ; conservation Ec+Ep = cste (sans frottement).\nConservation : Ec + Ep = constante (sans frottement).",
   experience:[
     "1️⃣ Bilan des forces sur un objet posé sur une table : Poids P = mg vers le bas ; Réaction N vers le haut. Résultante = 0 (immobile).",
     "2️⃣ Chariot 2kg tiré par F=8N, frottement f=4N : a = (8-4)/2 = 2 m/s². Vitesse après 5s : v = at = 10 m/s.",
     "3️⃣ Chute libre h=20m : t = √(2×20/10) = 2 s ; vitesse à l'impact = g×t = 20 m/s.",
     "4️⃣ Poids d'un élève de 60kg : P = 60×10 = 600 N. Sur la Lune (g=1,6) : P_lune = 96 N.",
     "5️⃣ Énergie (1ère) : balle 0,5kg lâchée de h=5m. Ep = 0,5×10×5 = 25 J. Au sol : Ec = 25 J → v = √(2×25/0,5) = 10 m/s.",
     "6️⃣ 3ème loi : toi tu pousses le mur avec 50N → le mur te pousse avec 50N en sens inverse (réaction).",
     "7️⃣ Frottements : glissement d'un livre sur une table. Sans frottement, MRU. Avec, le livre ralentit (décélération).",
   ],
   quiz:[
     {q:"Un objet de 4kg soumis à F=20N. Son accélération :",opts:["0,2 m/s²","5 m/s²","80 m/s²","16 m/s²"],ans:1,exp:"a = F/m = 20/4 = 5 m/s². 2ème loi de Newton : ΣF = ma."},
     {q:"Poids d'un objet de 5kg (g=10) :",opts:["5 N","10 N","50 N","500 N"],ans:2,exp:"P = mg = 5×10 = 50 N. La masse est en kg, le poids en Newtons."},
     {q:"Chute libre h=45m (g=10). Durée :",opts:["2 s","3 s","4 s","9 s"],ans:1,exp:"h = ½gt² → t² = 2h/g = 90/10 = 9 → t = 3 s."},
     {q:"La 3ème loi de Newton (action-réaction) :",opts:["S'applique uniquement aux corps en mouvement","Les forces s'exercent sur le même corps","Deux corps exercent sur l'autre des forces égales et opposées","N'est valable qu'en chute libre"],ans:2,exp:"Si A exerce F sur B, alors B exerce -F sur A. Forces égales, opposées, corps différents."},
     {q:"Objet en MRU (mouvement rectiligne uniforme). La résultante des forces est :",opts:["Maximale","Égale à ma","Nulle","Vers le bas"],ans:2,exp:"1ère loi : résultante nulle → immobile ou MRU. Pas de force nette = pas d'accélération."},
     {q:"Énergie cinétique d'un objet 2kg à 6 m/s :",opts:["12 J","24 J","36 J","72 J"],ans:2,exp:"Ec = ½mv² = ½×2×36 = 36 J."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Premium"},

  {id:"lv9",titre:"Optique & Propagation de la Lumière",matiere:"Physique",cat:"physique",
   classe:"2nde-1ère-Tle",ico:"🔭",color:"#0E7490",gratuit:true,
   desc:"Réflexion, réfraction, lentilles convergentes/divergentes, formation d'images et applications.",
   theorie:"🌟 Lumière : se propage en ligne droite à c = 3×10⁸ m/s dans le vide.\n\n🪞 Réflexion : angle incidence = angle réflexion (loi de Descartes).\n\n🔎 Réfraction : n₁×sin(i₁) = n₂×sin(i₂). Milieu plus dense → rayon se rapproche de la normale. n_eau≈1,33 ; n_verre≈1,5.\n\n🔬 Lentille convergente : f'>0. Vergence V=1/f' (dioptries).\nRelation conjugaison : 1/OA' - 1/OA = 1/f'.\nGrandissement : γ = OA'/OA.",
   experience:[
     "1️⃣ RÉFLEXION SUR MIROIR PLAN : pointe une lampe de poche vers un miroir dans une salle sombre. Mesure l'angle d'incidence (entre rayon et normale) et l'angle de réflexion. Vérifie : angle_i = angle_r. Dessine le schéma.",
     "2️⃣ RÉFRACTION — PAILLE DANS L'EAU : plonge une paille dans un verre d'eau. Observe : la paille paraît cassée à la surface. Le rayon change de direction en passant de l'air à l'eau (n_eau > n_air).",
     "3️⃣ DÉCOMPOSITION DE LA LUMIÈRE : dirige un rayon de lumière blanche (soleil ou lampe) sur un prisme ou un CD. Observe le spectre : rouge, orange, jaune, vert, bleu, indigo, violet. Chaque couleur est réfractée différemment.",
     "4️⃣ LENTILLE CONVERGENTE — CONSTRUCTION : trace 3 rayons pour un objet à OA=-30cm, f'=+10cm. Rayon parallèle → passe par F'. Rayon par le centre → ne dévie pas. Rayon par F → ressort parallèle. L'image est au croisement.",
     "5️⃣ LOUPE (lentille convergente) : place un objet ENTRE F et O (à moins de f'). Les rayons divergent après la lentille → pas d'image réelle. Regarde à travers : image virtuelle, droite, agrandie. C'est la loupe.",
     "6️⃣ MODÈLE DE L'ŒIL : le cristallin = lentille convergente convergente. Image réelle renversée sur la rétine. Myopie (œil trop long) → image se forme AVANT la rétine → correction par lentille divergente.",
     "7️⃣ VÉRIFICATION de la relation conjugaison : avec une lentille de f'=10cm connue, place un objet à OA=-20cm. Cherche la position de l'image en déplaçant un écran. Mesure OA'. Vérifie : 1/OA' - 1/OA = 1/f'.",
   ],
   quiz:[
     {q:"Vitesse de la lumière dans le vide :",opts:["3×10⁶ m/s","3×10⁸ m/s","3×10¹⁰ m/s","300 m/s"],ans:1,exp:"c = 3×10⁸ m/s ≈ 300 000 km/s."},
     {q:"Vergence = 5 dioptries → distance focale :",opts:["5 m","0,5 m","0,2 m","20 m"],ans:2,exp:"f' = 1/V = 1/5 = 0,2 m = 20 cm."},
     {q:"Lumière passant de l'air (n=1) vers l'eau (n=1,33) :",opts:["Accélère","Se rapproche de la normale","S'éloigne de la normale","Ne change pas"],ans:1,exp:"Milieu plus dense → n plus grand → rayon se rapproche de la normale."},
     {q:"Objet placé à 2f d'une lentille convergente. L'image est :",opts:["Virtuelle et droite","Réelle à f","Réelle à 2f, même taille","À l'infini"],ans:2,exp:"OA = -2f → OA' = +2f. γ = -1 : image réelle, renversée, même taille."},
     {q:"La décomposition de la lumière blanche par un prisme produit :",opts:["Lumière noire","Spectre de couleurs","Lumière plus intense","Uniquement rouge et bleu"],ans:1,exp:"Chaque couleur a une longueur d'onde et est réfractée différemment → spectre (arc-en-ciel)."},
     {q:"La réflexion totale interne est le principe de :",opts:["L'arc-en-ciel","La fibre optique","La loupe","Le miroir plan"],ans:1,exp:"Au-delà de l'angle limite, toute la lumière est réfléchie dans le milieu → guide d'ondes = fibre optique."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv10",titre:"Thermodynamique & Calorimétrie",matiere:"Physique",cat:"physique",
   classe:"1ère-Tle",ico:"🌡️",color:"#AE5353",gratuit:false,plan:"Sciences",
   desc:"Transferts de chaleur, capacité calorifique, changements d'état et lois des gaz parfaits.",
   theorie:"🌡️ Q = m×c×ΔT (Q en J, m en kg, c = capacité thermique massique).\nc_eau = 4180 J/kg·K ; c_fer = 450 J/kg·K.\n\n🧊 Changement d'état : Q = m×L (L = chaleur latente). L_fusion_glace = 334 kJ/kg.\n\n⚖️ Mélange : Q_cédée + Q_reçue = 0 (système isolé).\n\n⚗️ Gaz parfaits : PV = nRT (R = 8,314 J/mol·K ; T en Kelvin = °C + 273).\nBoyle : PV = cste (T fixe). Gay-Lussac : P/T = cste (V fixe).",
   experience:[
     "1️⃣ CALORIMÈTRE — MESURE DE C : verse 200g d'eau à 20°C dans un calorimètre. Chauffe un bloc de métal à 100°C, plonge-le dans l'eau. Mesure la température finale T_éq. Applique : m_métal×c_métal×(100-T_éq) = m_eau×4180×(T_éq-20). Déduis c_métal.",
     "2️⃣ CHANGEMENT D'ÉTAT — PALIER : mets des glaçons dans un bécher. Chauffe à puissance constante. Relève T toutes les minutes. Trace la courbe. Observe : pendant la fonte (0°C), T ne change pas malgré le chauffage → énergie absorbée = chaleur latente L.",
     "3️⃣ MÉLANGE D'EAU : mesure 100g d'eau chaude (T₁=80°C) dans un bécher, 100g d'eau froide (T₂=20°C) dans un autre. Mélange. Mesure T_eq. Compare avec la prévision : T_eq = (T₁+T₂)/2 = 50°C. Pourquoi l'écart ?",
     "4️⃣ SERINGUE ET GAZ (loi de Boyle) : bouche une seringue avec le doigt (V constant). Essaie de comprimer. Ressens la pression augmenter. Avec une seringue + manomètre : comprime le volume de moitié → la pression double.",
     "5️⃣ DILATATION THERMIQUE : chauffe un ballon en caoutchouc partiellement gonflé. Observe : il gonfle davantage (gaz se dilate). Refroidis : il se dégonfle. La pression à volume constant augmente avec T.",
     "6️⃣ ISOLATION THERMIQUE : mets de l'eau chaude (60°C) dans deux récipients : l'un bien isolé (coton, polystyrène), l'autre nu. Mesure la température toutes les 5 minutes pendant 30 min. Compare les courbes de refroidissement.",
     "7️⃣ COMBUSTION ET CALORIMÉTRIE : brûle une noix ou un morceau de biscuit sous un bécher d'eau. Mesure ΔT de l'eau. Calcule Q = m×4180×ΔT. Estime l'énergie (kJ/g) contenue dans l'aliment.",
   ],
   quiz:[
     {q:"On chauffe 1kg d'eau (c=4180) de 20°C à 70°C :",opts:["4 180 J","41 800 J","209 000 J","418 000 J"],ans:2,exp:"Q = 1×4180×50 = 209 000 J."},
     {q:"27°C en Kelvin :",opts:["27 K","127 K","300 K","327 K"],ans:2,exp:"T(K) = T(°C) + 273 = 300 K."},
     {q:"La chaleur latente correspond à :",opts:["L'énergie pour chauffer","L'énergie pour changer d'état à T constante","La capacité thermique","La conduction"],ans:1,exp:"Chaleur latente = énergie de changement d'état sans variation de température (fusion, vaporisation)."},
     {q:"Gaz à 200kPa et 400K, chauffé à 800K (V=cste). Nouvelle pression :",opts:["100 kPa","200 kPa","400 kPa","800 kPa"],ans:2,exp:"Gay-Lussac : P/T = cste → P₂ = 200×800/400 = 400 kPa."},
     {q:"L'eau a une capacité thermique plus élevée que le fer. Donc :",opts:["L'eau chauffe plus vite","L'eau nécessite plus d'énergie pour la même ΔT","L'eau conduit mieux","L'eau bout plus vite"],ans:1,exp:"c_eau=4180 >> c_fer=450 → l'eau stocke beaucoup d'énergie (régulateur thermique : océans, radiateurs)."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  // ─ CHIMIE ─
  {id:"lv3",titre:"Réactions Acide-Base",matiere:"Physique-Chimie",cat:"chimie",
   classe:"2nde-1ère-Tle C",ico:"⚗️",color:"#6C56A6",gratuit:true,
   desc:"pH, indicateurs colorés, neutralisations, dosage acido-basique et calculs de concentration.",
   theorie:"⚗️ Acide : libère H⁺ (H₃O⁺). Base : libère OH⁻.\npH < 7 = acide ; pH = 7 = neutre ; pH > 7 = basique.\n\n⚖️ Neutralisation : Acide + Base → Sel + Eau. Ex: HCl + NaOH → NaCl + H₂O.\n\nIndicateurs : phénolphtaléine (incolore/acide → rose/basique) ; BBT (jaune/acide, vert/neutre, bleu/basique).\n\n📈 Titrage : à l'équivalence Ca×Va = Cb×Vb (monoprotique).",
   experience:[
     "1️⃣ MATÉRIEL : béchers, pipette, burette, pH-mètre (ou papier pH), indicateurs colorés (BBT, phénolphtaléine). Prépare ta paillasse.",
     "2️⃣ TEST DES INDICATEURS : verse quelques gouttes de BBT dans 3 tubes : solution acide (vinaigre), eau distillée, solution basique (eau savonneuse). Observe les couleurs : jaune / vert / bleu.",
     "3️⃣ MESURE DU pH : plonge le papier pH dans : jus de citron, eau minérale, solution de lessive. Compare les couleurs au nuancier. Note les valeurs. pH < 7 = acide, = 7 = neutre, > 7 = basique.",
     "4️⃣ TITRAGE — PRÉPARATION : verse 10 mL d'acide chlorhydrique (HCl) dans un bécher. Ajoute 3 gouttes de phénolphtaléine → solution incolore (milieu acide).",
     "5️⃣ TITRAGE — AJOUT DE BASE : remplis la burette de NaOH. Verse goutte à goutte dans le bécher. Agite après chaque ajout. La solution reste incolore tant que l'acide est en excès.",
     "6️⃣ POINT D'ÉQUIVALENCE : au bout d'un certain volume de NaOH, la solution devient rose persistant : c'est le point d'équivalence. Lis le volume versé sur la burette. Calcule la concentration : Ca×Va = Cb×Vb.",
     "7️⃣ COURBE DE TITRAGE : reporte sur un graphe le pH en fonction du volume de NaOH versé. La courbe a une forme en S avec un saut brusque au point d'équivalence (entre pH 3 et pH 11 pour HCl/NaOH).",
   ],
   quiz:[
     {q:"Jus de citron pH=2. Il est :",opts:["Très basique","Neutre","Légèrement acide","Très acide"],ans:3,exp:"pH 2 est très acide (proche de 0). Acide citrique + acide ascorbique."},
     {q:"HCl + NaOH produit :",opts:["HNaCl + O₂","NaCl + H₂O","NaHCl₂","NaCl₂ + H₂"],ans:1,exp:"Neutralisation acide fort / base forte → sel (NaCl) + eau."},
     {q:"Phénolphtaléine en milieu basique :",opts:["Jaune","Bleue","Rose/Violette","Incolore"],ans:2,exp:"Phénolphtaléine : incolore (acide/neutre) → rose/violette (basique, pH > 8,2)."},
     {q:"Au point d'équivalence HCl/NaOH, pH = :",opts:["0","7","10","14"],ans:1,exp:"Acide fort + base forte → pH = 7 à l'équivalence (NaCl + H₂O, neutres)."},
     {q:"Un acide fort vs un acide faible :",opts:["A un pH plus élevé","Se dissocie totalement dans l'eau","Réagit uniquement avec métaux","A une couleur plus intense"],ans:1,exp:"Acide fort (HCl, H₂SO₄) : dissociation totale. Acide faible (CH₃COOH) : dissociation partielle."},
     {q:"Dosage : 20mL acide + 25mL NaOH 0,1mol/L. Concentration de l'acide :",opts:["0,08 mol/L","0,125 mol/L","0,1 mol/L","0,5 mol/L"],ans:1,exp:"Ca×Va = Cb×Vb → Ca = 0,1×25/20 = 0,125 mol/L."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv11",titre:"Oxydoréduction & Combustion",matiere:"Chimie",cat:"chimie",
   classe:"Tle C/D",ico:"🔥",color:"#EA580C",gratuit:false,plan:"Sciences",
   desc:"Réactions redox, nombres d'oxydation, piles électrochimiques, corrosion et combustions.",
   theorie:"🔥 OIL RIG : Oxidation Is Loss (d'électrons) ; Reduction Is Gain.\nCouple redox : forme oxydée / forme réduite. Ex: Cu²⁺/Cu ; Zn²⁺/Zn.\n\n🔋 Pile : réaction redox spontanée → courant. Anode = oxydation ; Cathode = réduction.\n\n⚙️ Électrolyse : courant forcé → réaction non-spontanée.\n\n🔥 Combustion complète du méthane : CH₄ + 2O₂ → CO₂ + 2H₂O.\nIncomplète : CH₄ + 3/2 O₂ → CO + 2H₂O (CO = dangereux !).",
   experience:[
     "1️⃣ RÉACTION Zn/CuSO₄ : plonge une lame de zinc dans une solution bleue de sulfate de cuivre (CuSO₄). Observe sur 5 minutes : dépôt rougeâtre sur la lame (cuivre métallique) et décoloration progressive de la solution.",
     "2️⃣ RÉACTION Cu/ZnSO₄ : plonge une lame de cuivre dans une solution de sulfate de zinc (ZnSO₄). Observe : aucune réaction. Conclusion : Zn est meilleur réducteur que Cu. Ordre de réactivité.",
     "3️⃣ CONSTRUCTION DE LA PILE Zn/Cu : prépare 2 béchers (ZnSO₄ + lame Zn ; CuSO₄ + lame Cu). Relie par un pont salin (papier filtre trempé dans KNO₃). Branche un voltmètre : lis ≈ 1,1 V.",
     "4️⃣ COMBUSTION DU MAGNÉSIUM : brûle un ruban de Mg dans l'air avec une pince. Observe : flamme blanche éblouissante (NE PAS REGARDER DIRECTEMENT). Résidu blanc = MgO. Équation : 2Mg + O₂ → 2MgO.",
     "5️⃣ ÉQUILIBRAGE D'ÉQUATION (procédure) : pour C₃H₈ + O₂ → CO₂ + H₂O, compte les atomes avant et après. Ajoute des coefficients pour égaliser : C₃H₈ + 5O₂ → 3CO₂ + 4H₂O. Vérifie chaque élément.",
     "6️⃣ CORROSION DU FER : observe des clous dans 3 tubes (eau + air, eau seule, air sec). Après 1 semaine : rouille dans le tube avec eau + air uniquement. Rôle de l'eau ET de l'oxygène confirmé.",
     "7️⃣ ÉLECTROLYSE DÉMONSTRATION : place deux électrodes en carbone dans de l'eau salée. Branche une pile 9V. Observe : bulles aux deux électrodes (H₂ à la cathode, O₂ à l'anode). L'eau se décompose !",
   ],
   quiz:[
     {q:"Zn + Cu²⁺ → Zn²⁺ + Cu. Quel élément est oxydé ?",opts:["Cu²⁺","Cu","Zn²⁺","Zn"],ans:3,exp:"Zn perd 2 électrons (0→+2) = oxydé (OIL). Cu²⁺ gagne 2e⁻ (+2→0) = réduit (RIG)."},
     {q:"N.o. de l'oxygène dans H₂O :",opts:["+2","+1","-1","-2"],ans:3,exp:"O très électronégatif → n.o. = -2 dans la plupart des composés."},
     {q:"Dans une pile, l'oxydation a lieu :",opts:["À la cathode","Au pont salin","À l'anode","Dans les deux"],ans:2,exp:"ANODE = Oxydation (A-O). Cathode = Réduction (C-R)."},
     {q:"Combustion complète de CH₄ donne :",opts:["CO + H₂O","CO₂ + H₂","CO₂ + H₂O","CH₃OH + O"],ans:2,exp:"CH₄ + 2O₂ → CO₂ + 2H₂O. Complète = CO₂. Incomplète = CO (toxique)."},
     {q:"La galvanisation protège le fer en le couvrant de :",opts:["Chrome","Cuivre","Zinc","Étain"],ans:2,exp:"Zinc plus réducteur que fer → se sacrifie en premier (protection cathodique)."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  // ─ SVT ─
  {id:"lv4",titre:"La Mitose — Division Cellulaire",matiere:"SVT",cat:"svt",
   classe:"1ère D-Tle D",ico:"🧬",color:"#059669",gratuit:true,
   desc:"Visualise les 4 phases de la mitose. Comprends la réplication, la division et la différence avec la méiose.",
   theorie:"🔬 Mitose : division cellulaire → 2 cellules filles IDENTIQUES à la mère (même 2n chromosomes).\n\n4 phases — PMAT :\n📌 Prophase : chromosomes se condensent, fuseau se forme.\n📌 Métaphase : chromosomes alignés sur la plaque équatoriale.\n📌 Anaphase : chromatides sœurs séparées, migrent aux pôles.\n📌 Télophase : 2 noyaux formés, cytocinèse → 2 cellules.\n\nInterphase (avant mitose) : réplication ADN (phase S). 46 chromosomes chez l'homme.",
   experience:[
     "1️⃣ PRÉPARATION DE LA LAME : coupe 2-3 mm d'une racine d'oignon (méristème = zone de croissance en pointe). Étale sur lame, ajoute colorant carmin acéto-orcéine ou violet de gentiane. Pose la lamelle, écrase légèrement.",
     "2️⃣ OBSERVATION AU MICROSCOPE (objectif ×10 puis ×40) : cherche des cellules dont le noyau est visible et coloré. Repère des cellules avec des chromosomes visibles (distinctes des cellules en interphase).",
     "3️⃣ IDENTIFIER LA PROPHASE : cherche une cellule dont les chromosomes sont condensés en bâtonnets épais mais encore désorganisés. L'enveloppe nucléaire disparaît.",
     "4️⃣ IDENTIFIER LA MÉTAPHASE : cherche une cellule dont les chromosomes sont alignés EN FILE au centre (plaque équatoriale). C'est la phase la plus facile à observer.",
     "5️⃣ IDENTIFIER L'ANAPHASE : cherche une cellule dont les chromosomes se séparent vers les deux pôles (forme en V ou Y). Les deux groupes de chromatides migrent en sens opposé.",
     "6️⃣ IDENTIFIER LA TÉLOPHASE : cherche deux masses de chromosomes aux pôles. La cellule commence à se diviser en deux (étranglement visible = cytocinèse).",
     "7️⃣ SCHÉMA BILAN : dessine les 4 phases en ordre (PMAT) avec une légende : chromosomes, fuseau, plaque équatoriale, noyau. Note que la mitose conserve 2n=46 chromosomes dans chaque cellule fille.",
   ],
   quiz:[
     {q:"La mitose produit combien de cellules filles identiques ?",opts:["1","2","4","8"],ans:1,exp:"Mitose → 2 cellules filles génétiquement identiques à la mère (2n chromosomes)."},
     {q:"À quelle phase les chromosomes s'alignent-ils au centre ?",opts:["Prophase","Métaphase","Anaphase","Télophase"],ans:1,exp:"MÉTAPHASE : alignement sur la plaque équatoriale. PMAT → M = aligneMent au Milieu."},
     {q:"Qu'est-ce qu'une chromatide ?",opts:["Un chromosome entier","La moitié d'un chromosome répliqué","Une molécule d'ARN","Un gène isolé"],ans:1,exp:"Après réplication, chaque chromosome = 2 chromatides sœurs identiques reliées au centromère."},
     {q:"La mitose est précédée de :",opts:["La méiose","La prophase directement","L'interphase (réplication ADN)","La télophase"],ans:2,exp:"L'interphase (G1+S+G2) précède la mitose. La phase S = réplication de l'ADN."},
     {q:"Différence principale mitose vs méiose :",opts:["Mitose produit 4 cellules","Méiose produit des cellules identiques","Méiose produit 4 cellules haploïdes (n)","Mitose ne concerne que les plantes"],ans:2,exp:"Méiose → 4 cellules haploïdes (n) = gamètes. Mitose → 2 cellules diploïdes (2n) identiques."},
     {q:"Un humain a 2n=46. Après mitose, chaque cellule fille a :",opts:["23","46","92","12"],ans:1,exp:"La mitose conserve 2n→2n. Chaque cellule fille a bien 46 chromosomes."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv5",titre:"La Nutrition chez les Plantes",matiere:"SVT",cat:"svt",
   classe:"5ème-4ème",ico:"🌱",color:"#16A34A",gratuit:true,
   desc:"Photosynthèse, absorption des sels minéraux, circulation de la sève et rôle des stomates.",
   theorie:"🌿 Photosynthèse : 6CO₂ + 6H₂O + lumière → C₆H₁₂O₆ + 6O₂.\nLieu : CHLOROPLASTES (grains verts dans les cellules des feuilles). Nécessite : lumière + CO₂ + eau.\n\n🔬 3 conditions indispensables à la photosynthèse :\n• Lumière (vérifiable avec une cloche noire)\n• CO₂ (vérifiable avec de la chaux sodée ou du KOH)\n• Eau (vérifiable par déshydratation)\n\n💧 Sève brute : eau + sels minéraux (racines → poils absorbants → XYLÈME → feuilles).\n🍃 Transpiration : les stomates (pores) libèrent la vapeur d'eau.\n🍬 Sève élaborée : glucose fabriqué dans feuilles → PHLOÈME → toute la plante.",
   experience:[
     "1️⃣ Plante au soleil 2h et une plante à l'obscurité 2h. Prélève une feuille de chacune.",
     "2️⃣ Décoloration : trempe les feuilles dans l'alcool chaud (bain-marie) → feuilles deviennent blanc-crème.",
     "3️⃣ Test au Lugol (eau iodée) : feuille éclairée → BLEU-NOIR (amidon présent = photosynthèse a eu lieu).",
     "4️⃣ Feuille à l'obscurité + test Lugol → beige (pas d'amidon = pas de photosynthèse sans lumière).",
     "5️⃣ Transpiration : couvre une plante d'un sac plastique transparent → vapeur d'eau visible sur les parois.",
     "6️⃣ Trajet de l'eau : place une fleur blanche dans de l'eau colorée au bleu de méthylène → tige et pétales bleutés.",
     "7️⃣ Bilan : la plante fabrique ses propres aliments (autotrophe). Elle absorbe CO₂ et rejette O₂ = source d'oxygène vital.",
   ],
   quiz:[
     {q:"La photosynthèse se déroule dans :",opts:["Les mitochondries","Les chloroplastes","Le noyau","Les vacuoles"],ans:1,exp:"Les chloroplastes contiennent la chlorophylle (verte) qui capte la lumière et permet la photosynthèse."},
     {q:"La photosynthèse libère quel gaz utile à la respiration ?",opts:["CO₂","N₂","O₂","H₂"],ans:2,exp:"6CO₂ + 6H₂O + lumière → C₆H₁₂O₆ + 6O₂. L'oxygène libéré est utilisé par tous les êtres vivants."},
     {q:"Test au Lugol sur une feuille exposée à la lumière :",opts:["Rouge","Jaune","Bleu-noir","Aucune réaction"],ans:2,exp:"Lugol (eau iodée) colore l'amidon en bleu-noir. La photosynthèse produit du glucose transformé en amidon."},
     {q:"Quel organe de la racine absorbe l'eau ?",opts:["La tige","Les stomates","Les fleurs","Les poils absorbants"],ans:3,exp:"Les poils absorbants se trouvent à l'extrémité des racines et absorbent eau + sels minéraux du sol."},
     {q:"La sève élaborée (sucrée) circule :",opts:["Des racines vers les feuilles par le xylème","Des feuilles vers toute la plante par le phloème","Uniquement dans les racines","Des fleurs vers les feuilles"],ans:1,exp:"Sève élaborée (glucose) → fabriquée dans les feuilles → descend par le phloème vers les autres organes."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv12",titre:"La Digestion Humaine",matiere:"SVT",cat:"svt",
   classe:"5ème-4ème",ico:"🍽️",color:"#B04E64",gratuit:true,
   desc:"Trajet des aliments, enzymes digestives, absorption des nutriments et rôle du foie.",
   theorie:"🍽️ Tube digestif : bouche → œsophage → estomac → intestin grêle → gros intestin → anus.\n\n⚗️ Enzymes :\n• Bouche : amylase salivaire (amidon → maltose)\n• Estomac : pepsine + HCl (pH≈2) (protéines → peptides)\n• Intestin grêle : lipase, protéases, amylase pancréatique ; bile du foie (émulsification graisses)\n\n🩸 Absorption : villosités intestinales (≈200 m² de surface). Glucose, acides aminés → sang. Lipides → lymphe.\nFoie : stockage glycogène, filtration, production bile.",
   experience:[
     "1️⃣ Amylase salivaire : amidon + salive à 37°C → 5min → test Lugol = jaune/brun (amidon dégradé !).",
     "2️⃣ Froid : même test à 0°C → Lugol bleu-noir (enzyme inactive par le froid).",
     "3️⃣ Acide : amylase à pH=2 → pas de digestion (enzyme dénaturée, comme dans l'estomac).",
     "4️⃣ Trajet du steak : bouche (mastication) → estomac (pepsine, 4h) → duodénum (bile+enzymes pancréas).",
     "5️⃣ Villosités intestinales : 200 m² de surface absorbante ! Glucose + acides aminés → sang portal → foie.",
     "6️⃣ Gros intestin : absorption de l'eau, flore bactérienne (microbiote), formation des fèces.",
     "7️⃣ IMC : poids(kg)/taille²(m). < 18,5 = sous-poids ; 18,5-25 = normal ; > 30 = obésité.",
   ],
   quiz:[
     {q:"Quel organe produit la bile ?",opts:["Pancréas","Estomac","Foie","Intestin grêle"],ans:2,exp:"Le foie produit la bile (stockée dans la vésicule biliaire) qui émulsionne les lipides."},
     {q:"L'amylase salivaire dégrade :",opts:["Les protéines","Les lipides","L'amidon","Les vitamines"],ans:2,exp:"L'amylase (bouche + pancréas) dégrade l'amidon → maltose → glucose."},
     {q:"pH de l'estomac ≈ :",opts:["7","2","8","5"],ans:1,exp:"L'estomac sécrète HCl → pH ≈ 2. Active la pepsine et détruit les bactéries."},
     {q:"L'absorption des nutriments a lieu principalement dans :",opts:["L'estomac","Le gros intestin","L'intestin grêle","La bouche"],ans:2,exp:"Intestin grêle (6-7m + villosités = 200m²) : site principal d'absorption."},
     {q:"Les lipides digérés sont absorbés par :",opts:["Le sang directement","La voie lymphatique","L'urine","Les poumons"],ans:1,exp:"Acides gras + glycérol → chylomicrons → vaisseaux lymphatiques (chylifères) → sang."},
     {q:"Rôle principal du gros intestin :",opts:["Produire les enzymes","Absorber les protéines","Absorber l'eau et former les fèces","Produire la bile"],ans:2,exp:"Gros intestin : absorption de l'eau + fermentation bactérienne → formation des matières fécales."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv13",titre:"Circulation Sanguine & Respiration",matiere:"SVT",cat:"svt",
   classe:"4ème-3ème",ico:"❤️",color:"#AE5353",gratuit:true,
   desc:"Le cœur, la grande et petite circulation, échanges gazeux dans les poumons et rôle de l'hémoglobine.",
   theorie:"❤️ Cœur = pompe double à 4 cavités : 2 oreillettes + 2 ventricules.\n\n🔴 Grande circulation : cœur gauche → aorte → organes → veines caves → oreillette droite.\n🔵 Petite circulation : cœur droit → artères pulmonaires → poumons → veines pulmonaires → oreillette gauche.\n\n🫁 Hématose (alvéoles) : O₂ passe dans le sang par diffusion ; CO₂ en sort. Surface ≈ 70 m².\n\nHémoglobine (globules rouges) : fixe 4 O₂ → oxyhémoglobine (rouge vif) ; libère O₂ aux tissus.",
   experience:[
     "1️⃣ Dissection virtuelle cœur de mouton : identifie 4 cavités, valves (mitrale, tricuspide, sigmoïdes).",
     "2️⃣ Trajet d'une hématie : oreillette D → ventricule D → artère pulmonaire → poumon (charge O₂) → oreillette G → ventricule G → aorte → muscles.",
     "3️⃣ Mesure ton pouls (artère radiale, 15s × 4). Normal : 60-80/min. Après 30 squats : mesure de nouveau.",
     "4️⃣ Spiromètre virtuel : volume courant (0,5L), capacité vitale (3,5-5L), volume résiduel.",
     "5️⃣ Échanges gazeux alvéolaires : PO₂ alvéolaire > PO₂ sang veineux → diffusion O₂ vers sang.",
     "6️⃣ Hémoglobine : à faible PO₂ (tissus) elle libère O₂. À forte PO₂ (poumons) elle le capte.",
     "7️⃣ Athérosclérose : plaques de cholestérol → sténose artérielle → risque infarctus. Prévention : sport + alimentation.",
   ],
   quiz:[
     {q:"Le cœur humain a combien de cavités ?",opts:["2","3","4","6"],ans:2,exp:"4 cavités : oreillette D, ventricule D (circulation pulmonaire) + oreillette G, ventricule G (circulation systémique)."},
     {q:"Les artères pulmonaires transportent :",opts:["Sang oxygéné vers les poumons","Sang désoxygéné vers les poumons","Sang oxygéné vers le cœur","Sang désoxygéné vers le cœur"],ans:1,exp:"Exception ! Artères pulmonaires = sang DÉSOXYGÉNÉ du cœur droit vers les poumons."},
     {q:"Les échanges O₂/CO₂ ont lieu dans :",opts:["La trachée","Les bronches","Les alvéoles pulmonaires","Les capillaires coronaires"],ans:2,exp:"Alvéoles (300 millions, paroi ultra-fine) : diffusion O₂ → sang, CO₂ → air. Surface ≈ 70 m²."},
     {q:"L'hémoglobine se trouve dans :",opts:["Les leucocytes","Les plaquettes","Les globules rouges","Le plasma"],ans:2,exp:"Hémoglobine = protéine des érythrocytes (globules rouges). Transporte O₂ des poumons aux organes."},
     {q:"Pression artérielle '120/80' :",opts:["120=diastolique, 80=systolique","120=systolique, 80=diastolique","120 battements/min","Les deux ventricules"],ans:1,exp:"120 mmHg = systolique (contraction VG) ; 80 mmHg = diastolique (relâchement). Valeurs normales."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv14",titre:"Génétique & Hérédité",matiere:"SVT",cat:"svt",
   classe:"Tle D",ico:"🔬",color:"#6C56A6",gratuit:false,plan:"Sciences",
   desc:"Lois de Mendel, croisements, dominance, codominance et génétique des groupes sanguins.",
   theorie:"🧬 Gène : portion d'ADN. Allèles : différentes formes d'un gène.\nGénotype (AA, Aa, aa) → Phénotype (caractère observable).\n\n📌 1ère loi Mendel : uniformité F1 (AA × aa → 100% Aa).\n📌 2ème loi : F1×F1 → ratio 3:1 phénotypique, 1:2:1 génotypique.\n📌 3ème loi : assortiment indépendant des gènes de chromosomes différents.\n\nGroupes ABO : IA et IB codominants ; i récessif.\nDaltonisme : lié à X (garçons surtout touchés).\nDrépanocytose : HbS/HbS = malade ; HbA/HbS = porteur sain.",
   experience:[
     "1️⃣ Mendel : VV (violette) × vv (blanche) → F1 : 100% Vv (violettes). V dominant.",
     "2️⃣ Tableau de Punnett Vv×Vv : VV + 2Vv + vv = 3 violettes : 1 blanche (ratio 3:1).",
     "3️⃣ Dihybridisme AABB × aabb → F1 : AaBb. F1×F1 → F2 : 9 A_B_ : 3 A_bb : 3 aaB_ : 1 aabb.",
     "4️⃣ Groupes sanguins : père IAi (A) × mère IBi (B) → IAIB (AB), IAi (A), IBi (B), ii (O). 4 groupes possibles !",
     "5️⃣ Daltonisme (lié X) : mère XᴰX (porteuse) × père XᴰY → 50% fils daltoniens.",
     "6️⃣ Drépanocytose : HbA/HbS × HbA/HbS → 25% risque enfant malade (HbS/HbS).",
     "7️⃣ Arbre généalogique : détermine le mode de transmission d'une maladie (dominant/récessif/lié X).",
   ],
   quiz:[
     {q:"Croisement Vv × Vv (V dominant). Ratio phénotypique F2 :",opts:["1:1:1:1","1:2:1","3:1","1:1"],ans:2,exp:"Vv×Vv → 1VV + 2Vv + 1vv = 3 phénotype V_ (violette) : 1 vv (blanche)."},
     {q:"Le phénotype est :",opts:["Le matériel génétique","L'ensemble des allèles","Le caractère observable","La séquence ADN complète"],ans:2,exp:"Phénotype = caractère observable (couleur yeux, taille, groupe sanguin). Génotype = constitution allélique."},
     {q:"IA et IB pour les groupes sanguins ABO sont :",opts:["IA dominant sur IB","IB dominant sur IA","Codominants","Les deux récessifs"],ans:2,exp:"IA et IB codominants → individu IAIB exprime les DEUX antigènes → groupe AB."},
     {q:"Le daltonisme (lié à X) touche surtout :",opts:["Les filles","Les garçons","Les deux sexes","Uniquement les homozygotes"],ans:1,exp:"Garçons XY : un seul allèle X → si défectueux, maladie exprimée. Filles XX : peuvent être porteuses."},
     {q:"Croisement AA × aa. F1 est :",opts:["AA","aa","100% Aa","1/2 AA + 1/2 aa"],ans:2,exp:"1ère loi (uniformité) : P1 AA × P2 aa → F1 : 100% Aa."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  // ─ MATHS ─
  {id:"lv6",titre:"Géométrie dans l'Espace",matiere:"Maths",cat:"maths",
   classe:"2nde-1ère-Tle",ico:"📐",color:"#AE5353",gratuit:true,
   desc:"Volumes, aires et diagonales des solides : cube, sphère, cylindre, pyramide, cône.",
   theorie:"📦 Cube : V=a³ ; Aire=6a² ; Diagonale=a√3.\n🔵 Sphère : V=(4/3)πr³ ; Aire=4πr².\n🥫 Cylindre : V=πr²h ; Aire totale=2πr(h+r).\n🔺 Pyramide : V=(B×h)/3 (B=aire base).\n🍦 Cône : V=(πr²h)/3 ; Apothème l=√(r²+h²).\n\nDistance 3D : AB=√[(x₂-x₁)²+(y₂-y₁)²+(z₂-z₁)²].\nSection d'un cube par plan diagonal → rectangle.",
   experience:[
     "1️⃣ RECONNAÎTRE LES SOLIDES : cube (6 faces carrées), pavé droit (6 faces rectangulaires), cylindre (2 cercles + 1 rectangle enroulé), cône (1 cercle + 1 secteur), pyramide (base + triangles). Dessine chaque solide.",
     "2️⃣ DÉVELOPPEMENT DU CUBE : découpe un cube en carton. Déplie-le. Observe : 6 carrés disposés en croix. Retrace le patron sur papier, découpe et reforme le cube. Aide-toi du patron pour calculer l'aire totale = 6a².",
     "3️⃣ VOLUME DU CUBE : remplis d'eau un cube de côté a=5cm jusqu'au bord. Verse dans une éprouvette graduée. Mesure : V = 125 cm³ (= a³). Vérifie la formule.",
     "4️⃣ CYLINDRE : mesure le rayon r et la hauteur h d'une boîte de conserve. Calcule V = πr²h. Compare avec la contenance indiquée sur l'étiquette (en mL = cm³). Écart dû aux parois ?",
     "5️⃣ PYRAMIDE vs PRISME : prends une pyramide et un prisme de même base et même hauteur. Pour remplir le prisme, il faut exactement 3 fois la pyramide d'eau. → V_pyramide = (1/3) × V_prisme.",
     "6️⃣ PROBLÈME CONCRET (cône) : une tente conique a r=3m et h=4m. Calcule la toile nécessaire (aire latérale = πrl où l=√(r²+h²)=5m) → πrl = 3π×5 ≈ 47,1 m².",
     "7️⃣ CALCUL DU VOLUME D'UN CHÂTEAU D'EAU : observe le château d'eau de ton quartier. Estime r et h. Applique V=πr²h. Convertis en litres (1 m³ = 1000 L). Combien de familles peut-il alimenter ?",
   ],
   quiz:[
     {q:"Cube d'arête 4cm. Volume :",opts:["16 cm³","48 cm³","64 cm³","96 cm³"],ans:2,exp:"V = a³ = 4³ = 64 cm³."},
     {q:"Volume d'une sphère :",opts:["V=πr²h","V=(4/3)πr³","V=πr³","V=2πr²"],ans:1,exp:"V=(4/3)πr³. Pour r=3 : V≈113cm³."},
     {q:"Cône r=3cm, h=4cm. Volume :",opts:["12π cm³","4π cm³","36π cm³","18π cm³"],ans:0,exp:"V=(1/3)πr²h=(1/3)π×9×4=12π≈37,7cm³."},
     {q:"Diagonale d'un cube d'arête a :",opts:["a√2","a√3","2a","a√6"],ans:1,exp:"d=√(a²+a²+a²)=a√3."},
     {q:"Cylindre r=5cm, h=10cm. Aire totale :",opts:["50π cm²","100π cm²","150π cm²","200π cm²"],ans:2,exp:"Aire=2πrh+2πr²=100π+50π=150π cm²."},
     {q:"Pyramide base 3×3cm, h=4cm. Volume :",opts:["12 cm³","18 cm³","36 cm³","48 cm³"],ans:0,exp:"V=(9×4)/3=12 cm³."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv15",titre:"Probabilités & Statistiques",matiere:"Maths",cat:"maths",
   classe:"1ère-Tle",ico:"🎲",color:"#D97706",gratuit:true,
   desc:"Probabilités classiques et conditionnelles, statistiques descriptives. 1ère : loi binomiale.",
   theorie:"🎲 P(A) = cas favorables / cas totaux. 0 ≤ P(A) ≤ 1.\nP(Ā) = 1-P(A) ; P(A∪B) = P(A)+P(B)-P(A∩B).\nIndépendants : P(A∩B) = P(A)×P(B).\n\n📊 Statistiques :\n• Moyenne : μ = Σ(xi×ni)/N\n• Médiane : valeur centrale de la série ordonnée\n• Mode : valeur la plus fréquente\n• Étendue = valeur max − valeur min\n• Écart interquartile = Q3 − Q1\n\n📐 1ère (Tle) — Loi binomiale B(n,p) :\nP(X=k) = C(n,k)×pᵏ×(1-p)ⁿ⁻ᵏ ; E(X)=np ; σ=√[np(1-p)].",
   experience:[
     "1️⃣ EXPÉRIENCE CONCRÈTE : lance un dé 30 fois. Note le résultat de chaque lancer dans un tableau. Calcule la fréquence de chaque face. Compare avec la probabilité théorique 1/6 ≈ 0,167.",
     "2️⃣ TABLEAU DE DONNÉES : relève les notes de contrôle de ta classe (ou utilise : 5, 7, 8, 9, 10, 10, 12, 13, 14, 15, 16, 18). Organise-les dans l'ordre croissant.",
     "3️⃣ CALCUL DES INDICATEURS : sur ta série ordonnée → calcule μ (moyenne) ; identifie la médiane (valeur centrale) ; identifie le mode (valeur la plus répétée) ; calcule l'étendue = max − min.",
     "4️⃣ HISTOGRAMME : regroupe les notes par tranches (0-5, 6-9, 10-12, 13-15, 16-20). Trace le diagramme en barres. Quelle tranche regroupe le plus d'élèves ?",
     "5️⃣ DIAGRAMME CIRCULAIRE : pour un sondage (ex. 40% aiment le foot, 30% la musique, 30% la lecture), calcule les angles (×360°) et trace le camembert.",
     "6️⃣ PROBABILITÉ CLASSIQUE : une urne a 3 boules rouges, 4 bleues, 3 vertes. Calcule : P(rouge), P(non rouge), P(rouge ou bleue). Vérifie que la somme des probabilités = 1.",
     "7️⃣ ARBRE DE PROBABILITÉ : un sac a 2 billes noires, 3 blanches. On tire 2 billes successivement sans remise. Construis l'arbre et calcule P(2 noires), P(1 noire + 1 blanche), P(2 blanches).",
   ],
   quiz:[
     {q:"Urne : 3 rouges + 7 bleues. P(rouge) = ?",opts:["3/7","7/10","3/10","1/3"],ans:2,exp:"P = 3/(3+7) = 3/10 = 0,3 = 30%."},
     {q:"Moyenne de la série {4, 6, 8, 10, 12} :",opts:["6","8","10","40"],ans:1,exp:"μ = (4+6+8+10+12)/5 = 40/5 = 8."},
     {q:"P(A)=0,5, P(B)=0,4, P(A∩B)=0,2. P(A∪B) = ?",opts:["0,9","0,7","1,1","0,3"],ans:1,exp:"P(A∪B) = P(A)+P(B)−P(A∩B) = 0,5+0,4−0,2 = 0,7."},
     {q:"La médiane d'une série ordonnée est :",opts:["La valeur la plus fréquente","La moyenne","La valeur qui partage la série en deux moitiés égales","La valeur minimale"],ans:2,exp:"Médiane : série ordonnée → valeur du milieu (ou moyenne des deux valeurs centrales si n pair)."},
     {q:"A et B indépendants, P(A)=0,3, P(B)=0,4. P(A∩B) = ?",opts:["0,7","0,12","0,1","0,7"],ans:1,exp:"Indépendants → P(A∩B) = P(A)×P(B) = 0,3×0,4 = 0,12."},
     {q:"L'écart-type σ mesure :",opts:["La valeur centrale","La dispersion des données autour de la moyenne","La valeur maximale","Le nombre total d'observations"],ans:1,exp:"σ élevé = données très dispersées. σ faible = données concentrées autour de μ."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv16",titre:"Fonctions & Dérivées",matiere:"Maths",cat:"maths",
   classe:"1ère-Tle",ico:"📈",color:"#BE185D",gratuit:false,plan:"Sciences",
   desc:"Fonctions usuelles, calcul de dérivées, tableaux de variations et optimisation.",
   theorie:"📐 Dérivée = taux de variation instantané = pente de la tangente.\n(xⁿ)'=nxⁿ⁻¹ ; (√x)'=1/(2√x) ; (eˣ)'=eˣ ; (ln x)'=1/x.\n(sin x)'=cos x ; (cos x)'=-sin x.\n(uv)'=u'v+uv' ; (u/v)'=(u'v-uv')/v².\n\n📊 Tableau de variations : f'>0 → croissante ; f'<0 → décroissante ; f'=0 → extremum.\n\n∫xⁿ dx = xⁿ⁺¹/(n+1)+C. Aire sous courbe = ∫ₐᵇ f(x)dx.",
   experience:[
     "1️⃣ TRACER LA COURBE : prends f(x)=x² sur [-3;3]. Construis le tableau de valeurs (x=-3,-2,-1,0,1,2,3 → f=9,4,1,0,1,4,9). Place les points sur papier millimétré. Trace la parabole en reliant les points.",
     "2️⃣ PENTE D'UNE TANGENTE : sur ta courbe de x², dessine la tangente au point x=1. Mesure sa pente (montée/base). Compare avec la valeur de f'(1)=2×1=2. Est-ce cohérent ?",
     "3️⃣ TABLEAU DE VARIATIONS : f(x)=x²-4x+3 → f'(x)=2x-4. Résous f'(x)=0 → x=2. Signe de f' : négatif sur ]-∞,2[, positif sur ]2,+∞[. Complète le tableau (flèche ↘ puis ↗).",
     "4️⃣ EXTREMUM LOCAL : d'après ton tableau, f est décroissante avant x=2 et croissante après → x=2 est un MINIMUM. Calcule f(2)=4-8+3=-1. C'est la valeur minimale de f.",
     "5️⃣ APPLICATION AU PROBLÈME CONCRET : un agriculteur veut clôturer un jardin rectangulaire de périmètre 40m. Surface S = x×(20-x). Dérive et trouve le max de S → x=10m (carré de 10×10).",
     "6️⃣ CALCUL DE DÉRIVÉES (exercice guidé) : dérive les fonctions suivantes en utilisant les formules : f(x)=3x⁴ → f'=? ; g(x)=5x²+2x → g'=? ; h(x)=√x → h'=? Vérifie tes réponses.",
     "7️⃣ INTÉGRALE (Tle) — AIRE SOUS LA COURBE : sur le graphe de f(x)=x entre 0 et 4, l'aire est un triangle de base 4 et hauteur 4. Aire = ½×4×4=8. Vérifie : ∫₀⁴ x dx = [x²/2]₀⁴ = 8 ✓",
   ],
   quiz:[
     {q:"Dérivée de f(x)=5x³ :",opts:["5x²","15x²","x³","15x³"],ans:1,exp:"(5x³)'=5×3x²=15x²."},
     {q:"Si f'(x)>0 sur un intervalle, f est :",opts:["Décroissante","Constante","Croissante","Convexe"],ans:2,exp:"f'(x)>0 ↔ pente positive ↔ f croissante."},
     {q:"Dérivée de ln(x) :",opts:["x","1/x","ln(x)/x","eˣ"],ans:1,exp:"(ln x)'=1/x pour x>0."},
     {q:"f(x)=x²-4x+3. f'(x)=0 en x=?",opts:["1","2","3","-2"],ans:1,exp:"f'(x)=2x-4=0 → x=2. Minimum (f''=2>0)."},
     {q:"∫₀² x dx = ?",opts:["2","4","1","0"],ans:0,exp:"[x²/2]₀²=4/2-0=2."},
     {q:"Dérivée de eˣ :",opts:["xeˣ⁻¹","eˣ","xeˣ","1/eˣ"],ans:1,exp:"(eˣ)'=eˣ. La fonction exponentielle est sa propre dérivée."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  {id:"lv17",titre:"Trigonométrie & Cercle Unité",matiere:"Maths",cat:"maths",
   classe:"2nde-1ère",ico:"📏",color:"#0891B2",gratuit:true,
   desc:"sin, cos, tan, valeurs remarquables, cercle trigonométrique et équations trigonométriques.",
   theorie:"📐 Triangle rectangle : sin=opp/hyp ; cos=adj/hyp ; tan=opp/adj (SOH-CAH-TOA).\n\n🔵 Cercle unité : M(cos θ, sin θ).\nValeurs : 0°(0,1) ; 30°(1/2,√3/2) ; 45°(√2/2,√2/2) ; 60°(√3/2,1/2) ; 90°(1,0).\n\nIdentité : sin²+cos²=1 ; sin(2x)=2sin x cos x ; cos(2x)=cos²x-sin²x.\n\nConversion : degrés×π/180 = radians. 90°=π/2 ; 180°=π ; 360°=2π.",
   experience:[
     "1️⃣ CONSTRUCTION DU TRIANGLE : sur papier quadrillé, dessine un triangle rectangle. Mesure l'hypoténuse (c), le côté adjacent (a) et le côté opposé (b) à l'angle α. Calcule sin(α)=b/c, cos(α)=a/c, tan(α)=b/a.",
     "2️⃣ TABLE DES VALEURS REMARQUABLES : complète ce tableau à mémoriser — | α | 0° | 30° | 45° | 60° | 90° | sin | 0 | 1/2 | √2/2 | √3/2 | 1 | cos | 1 | √3/2 | √2/2 | 1/2 | 0 |",
     "3️⃣ MESURE D'UNE HAUTEUR inaccessible : mesure la distance au pied d'un arbre (ex. 10m). Avec un rapporteur, mesure l'angle d'élévation (ex. 35°). Hauteur = d×tan(35°) ≈ 10×0,70 = 7m.",
     "4️⃣ CERCLE TRIGONOMÉTRIQUE : trace un cercle de rayon 1. Place le point M correspondant à α=30°. Ses coordonnées sont (cos 30°, sin 30°) = (√3/2, 1/2). Fais de même pour 45°, 60°, 90°.",
     "5️⃣ VÉRIFICATION DE L'IDENTITÉ : pour α=30°, calcule sin²(30°)+cos²(30°) = (1/2)²+(√3/2)² = 1/4+3/4 = 1 ✓. Teste avec α=45°. Cette identité est toujours vraie.",
     "6️⃣ CONVERSION DEGRÉS ↔ RADIANS : 180° = π rad. Complète : 90°=?, 60°=?, 45°=?, 30°=?, 360°=? Sens inverse : π/3 = ? ° ; 3π/2 = ? °.",
     "7️⃣ RÉSOLUTION D'ÉQUATION : dans un triangle rectangle, un angle est 40° et l'hypoténuse est 15cm. Calcule les deux côtés inconnus : côté opposé = 15×sin(40°) ≈ 9,6cm ; côté adjacent = 15×cos(40°) ≈ 11,5cm.",
   ],
   quiz:[
     {q:"sin(30°) = ?",opts:["√3/2","1/2","√2/2","1"],ans:1,exp:"sin(30°)=1/2. Valeur remarquable fondamentale."},
     {q:"tan(α) dans un triangle rectangle :",opts:["adj/hyp","opp/hyp","opp/adj","hyp/adj"],ans:2,exp:"SOH-CAH-TOA : Tan=Opp/Adj."},
     {q:"sin²(x)+cos²(x) = ?",opts:["0","2","sin(2x)","1"],ans:3,exp:"Identité pythagoricienne fondamentale."},
     {q:"90° en radians :",opts:["π/4","π/3","π/2","π"],ans:2,exp:"90°×π/180 = π/2 rad."},
     {q:"cos(π) = ?",opts:["0","1","-1","√2/2"],ans:2,exp:"cos(180°)=-1. Point (-1,0) sur le cercle unité."},
     {q:"Période de sin(x) :",opts:["π","2π","π/2","4π"],ans:1,exp:"sin(x+2π)=sin(x). Période = 2π."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  // ─ GÉOGRAPHIE & HISTOIRE ─
  {id:"lv18",titre:"La Mondialisation",matiere:"Géographie",cat:"geo",
   classe:"Tle",ico:"🌐",color:"#059669",gratuit:false,plan:"Complet",
   desc:"Flux mondiaux, acteurs, inégalités, IDH et place du Cameroun dans la mondialisation.",
   theorie:"🌐 Mondialisation = mise en relation croissante des économies, sociétés et espaces mondiaux.\n\n📦 Flux : marchandises (OMC) ; capitaux (IDE) ; personnes (migrations) ; informations (internet).\n\n🏭 Acteurs : FMN ; États ; OMC/FMI/BM ; ONG ; villes mondiales.\n\n🗺️ Triade (USA-Europe-Japon) + BRICS (Brésil, Russie, Inde, Chine, Afrique du Sud).\n\n📊 IDH : Indice Développement Humain (revenus + santé + éducation). De 0 à 1.\n\n🇨🇲 Cameroun : exportations (cacao, café, bois, pétrole) ; port Douala = hub régional ; IDE chinois.",
   experience:[
     "1️⃣ Trace les grandes routes maritimes : Canal Suez, Canal Panama, détroit Malacca, Cap Bonne Espérance.",
     "2️⃣ FMN Apple : conçu Californie → assemblé Chine → vendu mondialement. Fragmentation chaîne de valeur.",
     "3️⃣ IDH Cameroun 2023 ≈ 0,576 (moyen). Comparer : Norvège (0,97), Niger (0,40).",
     "4️⃣ Migrations camerounaises : diaspora en France, USA, UK. Transferts de fonds ≈ 300M$/an.",
     "5️⃣ Villes mondiales (global cities) : New York, Londres, Tokyo, Shanghai. Critères : CBD, bourse, FMN, hub aérien.",
     "6️⃣ Mondialisation culturelle : 'McDonaldisation' vs résistances locales. Francophonie comme levier.",
     "7️⃣ Débat : mondialisation = opportunité ou menace pour le Cameroun ? Argumentez avec des données.",
   ],
   quiz:[
     {q:"La mondialisation désigne :",opts:["La standardisation de la cuisine","La mise en relation croissante des économies mondiales","La création de l'Union Africaine","La colonisation du Sud"],ans:1,exp:"Mondialisation = intégration des marchés, capitaux, personnes et informations à l'échelle mondiale."},
     {q:"Les BRICS regroupent :",opts:["USA,UK,Inde,Chine,Suisse","Brésil,Russie,Inde,Chine,Afrique du Sud","Bangladesh,Rwanda,Inde,Corée,Suède","Belgique,Russie,Iran,Cameroun,Sénégal"],ans:1,exp:"BRICS = puissances émergentes contestant la domination de la triade USA-Europe-Japon."},
     {q:"L'IDH mesure :",opts:["Uniquement le PIB","La richesse des FMN","Le développement humain (revenus+santé+éducation)","La superficie"],ans:2,exp:"IDH (ONU) : combine espérance de vie, niveau d'éducation et revenu/habitant. Entre 0 et 1."},
     {q:"Le port de Douala est important car :",opts:["1er port d'Afrique","Hub pour pays enclavés d'Afrique centrale","Exporte uniquement du pétrole","Appartient à une FMN américaine"],ans:1,exp:"Douala = hub logistique pour Cameroun, Tchad, RCA — pays sans accès à la mer."},
     {q:"Une firme multinationale (FMN) :",opts:["Emploie > 1000 personnes","Produit et vend dans plusieurs pays","Appartient à l'État","Exporte uniquement"],ans:1,exp:"FMN = entreprise avec filiales de production/commercialisation dans plusieurs pays (Total, Samsung, Dangote)."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Complet"},

  // ─ INFO & LANGUES ─
  {id:"lv19",titre:"Algorithmes & Programmation",matiere:"Info/Maths",cat:"info",
   classe:"3ème-Tle",ico:"💻",color:"#1E3A8A",gratuit:true,
   desc:"Algorithmique, structures de contrôle, fonctions, récursivité et initiation Python.",
   theorie:"💻 Algorithme : suite d'instructions ordonnées pour résoudre un problème.\n\nStructures :\n• Séquence : instructions dans l'ordre\n• Condition : SI ... ALORS ... SINON\n• Boucle : POUR (n fois) ou TANTQUE (condition)\n• Fonction : bloc réutilisable, paramètres + retour\n\nComplexité : O(n) linéaire ; O(n²) quadratique ; O(log n) logarithmique.\n\nPython : indentation obligatoire pour les blocs. Types : int, float, str, bool, list, dict.",
   experience:[
     "1️⃣ Factorielle : f=1 ; POUR i de 1 à n : f=f×i. Résultat : 5!=120 ; 10!=3 628 800.",
     "2️⃣ Maximum dans [5,3,8,2,9,1] : max=tab[0] ; POUR x dans tab : SI x>max : max=x → max=9.",
     "3️⃣ Tri à bulles : compare et échange les paires adjacentes. O(n²) → lent pour n grand.",
     "4️⃣ Récursivité : fib(n)=fib(n-1)+fib(n-2), fib(0)=0, fib(1)=1. fib(7)=13.",
     "5️⃣ Python : if age>=18: print('Majeur') else: print('Mineur'). Test avec input().",
     "6️⃣ Fonction Python : def moyenne(notes): return sum(notes)/len(notes). Test avec [12,14,16,10,18].",
     "7️⃣ Application : algorithme de calcul de mention BAC camerounais (TB/B/AB/P/R) selon la moyenne.",
   ],
   quiz:[
     {q:"Une boucle POUR i de 1 à n s'exécute :",opts:["Jusqu'à une condition","Exactement n fois","Indéfiniment","Une seule fois"],ans:1,exp:"POUR = nombre fixe d'itérations. TANTQUE = s'exécute jusqu'à ce que la condition soit fausse."},
     {q:"En Python, l'indentation sert à :",opts:["Décorer le code","Définir les blocs d'instructions","Commenter le code","Déclarer les variables"],ans:1,exp:"Python utilise l'indentation (pas les {}) pour délimiter les blocs if, for, def, etc."},
     {q:"Complexité O(n²) : si n double, le temps :",opts:["Double","Triple","Quadruple","Reste le même"],ans:2,exp:"O(n²) : (2n)²=4n². Le temps est multiplié par 4."},
     {q:"5! = ?",opts:["25","60","120","720"],ans:2,exp:"5! = 5×4×3×2×1 = 120."},
     {q:"Une fonction récursive :",opts:["Utilise uniquement des boucles","S'appelle elle-même","Ne retourne pas de valeur","Traite uniquement des entiers"],ans:1,exp:"Récursivité = la fonction s'appelle elle-même avec un cas de base pour arrêter."},
     {q:"Structure de condition :",opts:["POUR i de 1 à n","TANTQUE x>0","SI x>0 ALORS","FONCTION f(x)"],ans:2,exp:"SI...ALORS...SINON = condition (branchement). POUR/TANTQUE = boucles."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv27",titre:"Le Système Immunitaire & Vaccination",matiere:"SVT",cat:"svt",
   classe:"Tle D",ico:"🛡️",color:"#16A34A",gratuit:true,
   desc:"Comprendre comment notre corps se défend contre les infections : anticorps, lymphocytes, vaccins. Programme Tle.",
   theorie:"🛡️ IMMUNITÉ INNÉE (1ère ligne) : peau, muqueuses, phagocytose par macrophages. Rapide, non-spécifique.\n\n⚔️ IMMUNITÉ ADAPTATIVE (lente, spécifique) :\n• Lymphocytes B → produisent anticorps (Ig) qui neutralisent l'antigène.\n• Lymphocytes T cytotoxiques → tuent les cellules infectées.\n• Lymphocytes T auxiliaires (CD4) → coordonnent la réponse.\n\n💉 VACCINATION : injection d'antigène atténué ou inactivé → mémoire immunitaire.\nÀ la 2ème exposition, réponse rapide et forte (lymphocytes mémoire). C'est le principe.\n\n🦠 VIH : détruit les LT4 (CD4) → effondrement immunité → SIDA.",
   experience:[
     "1️⃣ OBSERVATION : Une coupure cicatrise. Étape 1 : rougeur + chaleur (vasodilatation). Étape 2 : pus (macrophages morts + bactéries). Étape 3 : croûte (fibrine). Étape 4 : peau neuve.",
     "2️⃣ EXPÉRIENCE PASTEUR (1885) : Pasteur injecte virus rage atténué à un jeune mordu. Il survit ! Première vaccination. Principe : exposer le système immunitaire SANS danger.",
     "3️⃣ ANTIGÈNE-ANTICORPS : modèle clé-serrure. Chaque anticorps reconnaît UN antigène spécifique (variole, grippe, COVID...). Production : ~10 milliards d'anticorps différents possibles.",
     "4️⃣ TYPES DE VACCINS : Atténué (BCG, ROR) — vivant affaibli. Inactivé (grippe) — virus tué. Sous-unité (hépatite B) — protéine du virus. ARNm (Pfizer COVID) — code génétique → cellule produit l'antigène.",
     "5️⃣ TEST ELISA : détecter VIH dans sang. Antigène fixé sur plaque → ajout sang. Si anticorps anti-VIH présents → ils se fixent → coloration → personne séropositive.",
     "6️⃣ GROUPES SANGUINS : A, B, AB, O. Antigène A sur globule = groupe A. Anticorps anti-B dans plasma = groupe A. Transfusion A→B = catastrophe (agglutination).",
     "7️⃣ MÉMOIRE IMMUNITAIRE : graphique. 1ère exposition à un microbe : pic anticorps faible et tardif (~7 jours). 2ème exposition : pic ÉNORME et rapide (~3 jours). C'est pourquoi le rappel vaccinal renforce la protection.",
   ],
   quiz:[
     {q:"Cellules qui produisent les anticorps :",opts:["Lymphocytes T","Lymphocytes B","Macrophages","Globules rouges"],ans:1,exp:"Lymphocytes B (LB) deviennent plasmocytes et sécrètent les anticorps (immunoglobulines)."},
     {q:"Le VIH attaque principalement :",opts:["Globules rouges","Lymphocytes T4 (CD4)","Plaquettes","Neurones"],ans:1,exp:"VIH se fixe sur les récepteurs CD4 des LT4 → les détruit → effondrement de la coordination immunitaire → SIDA."},
     {q:"Principe d'un vaccin :",opts:["Tuer les microbes du corps","Stimuler la mémoire immunitaire avant l'infection","Donner directement des anticorps","Boost générique du système"],ans:1,exp:"Le vaccin expose le système immunitaire à un antigène inoffensif pour créer une mémoire. Lors d'une vraie infection, réponse immédiate."},
     {q:"Personne de groupe sanguin O a :",opts:["Antigène A et B","Aucun antigène A ni B","Antigènes A,B et anti-A,anti-B","Antigène O"],ans:1,exp:"Groupe O = absence d'antigène A et B. Plasma contient anti-A et anti-B. Donneur universel mais receveur que de O."},
     {q:"L'immunité innée est :",opts:["Spécifique et lente","Non-spécifique et rapide","Acquise par vaccination","Limitée aux nouveau-nés"],ans:1,exp:"Immunité innée = barrière universelle (peau, phagocytose) rapide mais non-spécifique. Adaptative = spécifique mais lente."},
     {q:"Sérothérapie consiste à :",opts:["Vacciner","Injecter des anticorps déjà formés","Faire une transfusion","Donner des antibiotiques"],ans:1,exp:"Sérothérapie = injection d'anticorps préformés (rapide mais non durable). Utile contre venin de serpent, rage post-exposition."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv28",titre:"ADN, Gènes & Hérédité",matiere:"SVT",cat:"svt",
   classe:"1ère D-Tle D",ico:"🧬",color:"#6C56A6",gratuit:true,
   desc:"Structure de l'ADN, code génétique, transmission des caractères et lois de Mendel. Programme 1ère-Tle.",
   theorie:"🧬 ADN = double hélice (Watson & Crick 1953) faite de 4 bases : A-T et G-C (complémentaires).\n\n📐 STRUCTURE : 2 brins anti-parallèles enroulés. Sucre (désoxyribose) + phosphate = squelette. Bases à l'intérieur.\n\n⛓️ ARN messager : copie d'un gène (transcription dans noyau). Sort vers ribosome.\n\n🔬 CODE GÉNÉTIQUE : par triplets (codons) de 3 bases → 1 acide aminé. 64 codons → 20 acides aminés (redondance).\n\n👶 LOIS DE MENDEL :\n• 1ère loi : uniformité des hybrides F1.\n• 2ème loi : ségrégation 3:1 dans F2 (dominant : récessif).\n• Sexe humain : XX (♀), XY (♂).",
   experience:[
     "1️⃣ EXTRACTION ADN MAISON : écraser banane, mélanger avec eau salée + savon liquide. Filtrer. Ajouter alcool froid à 90° doucement. Observer : filaments blancs visqueux = ADN ! Vrai expérience accessible.",
     "2️⃣ COMPLÉMENTARITÉ DES BASES : A=T, G=C. Si un brin est ATGCGTAA, l'autre est TACGCATT (lire à l'envers : 5'→3'). Vérifie : A face à T, G face à C.",
     "3️⃣ TRANSCRIPTION : ADN → ARN. Brin codant 'ATGCCC' → ARN 'AUGCCC' (T remplacé par U). Triplet AUG = méthionine = START.",
     "4️⃣ MUTATION : changement de base. ATGCCC (Méthionine-Proline) → ATGCGC (Méthionine-Arginine). Conséquence : protéine modifiée. Ex : drépanocytose (1 mutation = anémie falciforme).",
     "5️⃣ CROISEMENT MENDEL : Pois lisses (LL) × pois ridés (ll) → F1 : 100% Ll lisses (loi 1). F1×F1 → F2 : 1 LL, 2 Ll, 1 ll = 3 lisses : 1 ridé (loi 2).",
     "6️⃣ SEXE DE L'ENFANT : ♂ XY produit spermatozoïdes X (50%) ou Y (50%). ♀ XX produit ovules X (100%). C'est le PÈRE qui détermine le sexe. ♂ XY + X → fille XX. ♂ XY + Y → garçon XY.",
     "7️⃣ ARBRE GÉNÉALOGIQUE : tracer la transmission d'une maladie. Maladie autosomique récessive (mucoviscidose) : sauts de génération, parents porteurs sains. Maladie liée à X (hémophilie) : surtout chez garçons.",
   ],
   quiz:[
     {q:"Bases complémentaires dans l'ADN :",opts:["A-G et T-C","A-T et G-C","A-C et T-G","Aucune règle"],ans:1,exp:"Règle de Chargaff : Adénine s'apparie avec Thymine (2 liaisons H), Guanine avec Cytosine (3 liaisons H)."},
     {q:"Combien d'acides aminés codent les 64 codons ?",opts:["64","32","20","4"],ans:2,exp:"Code génétique = 64 codons → 20 acides aminés. Plusieurs codons peuvent coder le même AA (redondance)."},
     {q:"Croisement Aa × Aa donne :",opts:["100% Aa","25% AA, 50% Aa, 25% aa","50% AA, 50% aa","100% aa"],ans:1,exp:"Loi 2 Mendel : 1/4 AA, 2/4 Aa, 1/4 aa = phénotypes 3:1 (dominant:récessif)."},
     {q:"Génotype d'un garçon hémophile (gène sur X, récessif) :",opts:["X^h Y","X^H X^h","X^H Y","X^h X^h"],ans:0,exp:"X^h Y : un seul X (du côté ♂), donc si le gène hémophile est présent → maladie. Pas de 'compensation' par l'autre X."},
     {q:"L'ARNm est produit dans :",opts:["Cytoplasme","Noyau","Ribosome","Mitochondrie"],ans:1,exp:"Transcription ADN→ARNm se fait dans le NOYAU. Puis l'ARNm sort vers le cytoplasme et le ribosome pour traduction."},
     {q:"Un caryotype humain normal compte :",opts:["46 chromosomes","23 chromosomes","48 chromosomes","2 chromosomes"],ans:0,exp:"46 chromosomes = 23 paires (22 autosomes + 1 paire sexuelle XX ou XY). Trisomie 21 = 3 chromosomes 21 au lieu de 2."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv29",titre:"Probabilités Conditionnelles & Bayes",matiere:"Maths",cat:"maths",
   classe:"Tle C-Tle D",ico:"🎲",color:"#F59E0B",gratuit:true,
   desc:"Probabilités conditionnelles, indépendance, formule de Bayes et arbres pondérés. Programme Tle.",
   theorie:"🎲 P(A|B) = P(A∩B)/P(B) — probabilité de A SACHANT B.\n\n🌳 ARBRE PONDÉRÉ : branches = événements, poids = probabilités. P(chemin) = produit des poids.\n\n🔄 INDÉPENDANCE : A et B indépendants ⇔ P(A∩B) = P(A)×P(B) ⇔ P(A|B) = P(A).\n\n🧠 FORMULE DE BAYES : P(A|B) = P(B|A)×P(A) / P(B).\nApplication clé : test médical. P(malade|test+) ≠ P(test+|malade).",
   experience:[
     "1️⃣ TIRAGE DE BOULES : Urne = 5 rouges + 3 vertes. 2 tirages SANS remise. P(2 rouges) = (5/8)×(4/7) = 20/56 ≈ 0,357. Sans remise = dépendant.",
     "2️⃣ TIRAGE AVEC REMISE : même urne. P(2 rouges avec remise) = (5/8)×(5/8) = 25/64 ≈ 0,391. Avec remise = indépendant.",
     "3️⃣ INTERSECTION : Dans une classe de 30 élèves : 18 font Maths, 12 font Anglais, 6 les deux. P(M∩A) = 6/30 = 0,2. P(M∪A) = (18+12-6)/30 = 0,8.",
     "4️⃣ TEST MÉDICAL : maladie touche 1% pop. Test détecte 99% des malades (sensibilité), faux+ = 5%. Tu es positif. P(malade|+) = ? Bayes : (0,99×0,01)/(0,99×0,01 + 0,05×0,99) ≈ 17%. SURPRENANT !",
     "5️⃣ PARADOXE DU JEU MONTY HALL : 3 portes, 1 voiture. Tu choisis. Le présentateur ouvre une porte vide. Faut-il changer ? OUI ! P(gagner si on change) = 2/3.",
     "6️⃣ LANCERS DE DÉS : 2 dés à 6 faces. P(somme=7) = 6/36 = 1/6. P(somme=12) = 1/36. P(somme=2) = 1/36.",
     "7️⃣ EXPÉRIENCE COVID : taux positivité = 5%, sensibilité du test = 80%, faux+ = 2%. Tu testes positif. P(vraiment infecté) = 0,8×0,05 / (0,8×0,05 + 0,02×0,95) = 67%.",
   ],
   quiz:[
     {q:"P(A|B) = 0,3 et P(B) = 0,4. Alors P(A∩B) =",opts:["0,12","0,75","0,7","0,1"],ans:0,exp:"P(A∩B) = P(A|B)×P(B) = 0,3×0,4 = 0,12."},
     {q:"A et B indépendants. P(A)=0,5 et P(B)=0,4. P(A∪B) =",opts:["0,9","0,2","0,7","0,3"],ans:2,exp:"Indépendants : P(A∩B)=0,5×0,4=0,2. P(A∪B)=P(A)+P(B)-P(A∩B)=0,9-0,2=0,7."},
     {q:"Sur 100 personnes : 30 fument, 20 ont cancer, 15 fument ET ont cancer. P(cancer|fume) =",opts:["0,2","0,5","0,75","0,15"],ans:1,exp:"P(C|F) = P(C∩F)/P(F) = 15/30 = 0,5. Parmi les fumeurs, 50% ont cancer."},
     {q:"Lancer de 2 dés. P(somme = 7) =",opts:["1/36","1/12","1/6","5/36"],ans:2,exp:"Issues : (1,6)(6,1)(2,5)(5,2)(3,4)(4,3) = 6 sur 36 = 1/6."},
     {q:"Pour A et B indépendants, P(A|B) =",opts:["P(B)","P(A)×P(B)","P(A)","0"],ans:2,exp:"Indépendance : la connaissance de B ne change pas P(A). Donc P(A|B) = P(A)."},
     {q:"Test détecte 95% malades. 1% pop malade. Pos test → vraiment malade ?",opts:["≈ 95%","≈ 50%","≈ 16% (paradoxe Bayes)","100%"],ans:2,exp:"P(malade|+) ≈ 0,95×0,01 / (0,95×0,01 + 0,05×0,99) ≈ 16%. La rareté du cas + faux+ fausse l'intuition."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Premium"},

  {id:"lv30",titre:"Énergie Nucléaire : Fission & Fusion",matiere:"Physique",cat:"physique",
   classe:"Tle C-Tle D",ico:"☢️",color:"#AE5353",gratuit:false,plan:"Sciences",
   desc:"Radioactivité, désintégration, fission (centrales), fusion (étoiles, bombe H). Programme Tle.",
   theorie:"⚛️ NOYAU : Z protons + N neutrons. A=Z+N (nombre de masse). Notation : ^A_Z X.\n\n☢️ RADIOACTIVITÉ :\n• α : émission ^4_2 He (noyau hélium). Z↓2, A↓4.\n• β⁻ : neutron→proton + électron. Z↑1, A=cst.\n• γ : photon haute énergie. Z et A inchangés.\n\n⏱️ DEMI-VIE T : temps après lequel 50% des noyaux ont désintégré. N(t) = N₀ × (1/2)^(t/T).\n\n💥 FISSION : noyau lourd (U-235) absorbe neutron → se brise en 2 + 3 neutrons + énergie. Réaction en chaîne. Centrales nucléaires.\n\n☀️ FUSION : 2 noyaux légers (H) → noyau plus lourd (He) + énergie. Source du Soleil. Bombe H.",
   experience:[
     "1️⃣ COMPOSITION U-235 : Z=92 protons, A=235 → N=143 neutrons. Symbole : ^235_92 U. Très instable, fissile.",
     "2️⃣ DÉSINTÉGRATION α : ^238_92 U → ^234_90 Th + ^4_2 He. Vérifier : Z: 92=90+2 ✓ ; A: 238=234+4 ✓.",
     "3️⃣ DÉSINTÉGRATION β⁻ : ^14_6 C → ^14_7 N + e⁻. Un neutron du C devient proton (Z↑1). Datation au C-14 utilise cette propriété (T=5730 ans).",
     "4️⃣ DEMI-VIE : iode-131 (T=8 jours). Après 24 jours = 3 demi-vies. Fraction restante = (1/2)³ = 1/8 = 12,5%. Si N₀=400 atomes → 50 restants.",
     "5️⃣ DATATION C-14 : un fossile contient 25% du C-14 normal. 25% = (1/2)² → 2 demi-vies = 2×5730 = 11 460 ans.",
     "6️⃣ FISSION U-235 : neutron + ^235_92 U → ^141_56 Ba + ^92_36 Kr + 3 neutrons + 200 MeV. Les 3 neutrons fissent d'autres U-235 → réaction en chaîne (bombe A) ou contrôlée (centrale).",
     "7️⃣ FUSION DANS LE SOLEIL : 4 ^1_1 H → ^4_2 He + 2 positrons + 2 neutrinos + énergie. Température requise : 15 millions K (cœur Soleil). Sur Terre : ITER tente la reproduction.",
   ],
   quiz:[
     {q:"L'uranium-235 contient combien de neutrons ?",opts:["92","143","235","327"],ans:1,exp:"^235_92 U : A=235, Z=92 protons. N=A-Z=235-92=143 neutrons."},
     {q:"Désintégration α : Z et A changent comment ?",opts:["Z↑2, A=cst","Z=cst, A↓4","Z↓2, A↓4","Z↓1, A=cst"],ans:2,exp:"α = ^4_2 He éjecté. Le noyau perd 2 protons (Z↓2) et 2 neutrons (A↓4)."},
     {q:"Iode-131 (T=8j). Après 32 jours, fraction restante :",opts:["1/4","1/8","1/16","1/32"],ans:2,exp:"32j = 4 demi-vies. Fraction = (1/2)⁴ = 1/16."},
     {q:"Centrale nucléaire utilise quel phénomène ?",opts:["Fusion","Fission","Combustion","Désintégration alpha"],ans:1,exp:"Centrale = fission de U-235 ou Pu-239 contrôlée. Fusion = pas encore maîtrisée pour énergie."},
     {q:"Énergie du Soleil provient de :",opts:["Combustion","Fusion H→He","Fission","Géothermie"],ans:1,exp:"Au cœur du Soleil (15 millions K), 4 H → 1 He + énergie via fusion. Perte de masse convertie en E selon E=mc²."},
     {q:"Un échantillon : 25% C-14 restant. Âge ?",opts:["5730 ans","11 460 ans","17 190 ans","Indéterminable"],ans:1,exp:"25% = (1/2)² → 2 demi-vies × 5730 = 11 460 ans."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  {id:"lv31",titre:"Chimie Organique : Synthèse d'Ester",matiere:"Chimie",cat:"chimie",
   classe:"1ère D-Tle D",ico:"⚗️",color:"#C07D4F",gratuit:true,
   desc:"Estérification, hydrolyse, parfums et arômes. Mécanismes et déplacement d'équilibre. Programme 1ère-Tle.",
   theorie:"⚗️ ESTÉRIFICATION : Acide carboxylique + Alcool ⇌ Ester + Eau.\nR-COOH + R'-OH ⇌ R-CO-O-R' + H₂O\n\n⚖️ Équilibre LIMITÉ (~67% acide-alcool primaires, 50% secondaires). Lente.\n\n🚀 CATALYSEUR : H₂SO₄ concentré accélère SANS modifier l'équilibre.\n\n⬆️ DÉPLACER vers la droite (Le Chatelier) :\n• Excès d'un réactif (généralement alcool)\n• Élimination de l'eau formée (distillation Dean-Stark)\n\n🌸 ESTERS = PARFUMS : éthanoate d'éthyle = colle nail, éthanoate de pentyle = banane, butanoate d'éthyle = ananas.",
   experience:[
     "1️⃣ SYNTHÈSE BANANE : mélanger 10mL acide éthanoïque + 10mL alcool isopentylique + 2mL H₂SO₄. Chauffer 1h à reflux. Refroidir, laver à l'eau. Odeur intense de banane = éthanoate d'isopentyle.",
     "2️⃣ MONTAGE À REFLUX : ballon + colonne de Vigreux + réfrigérant à eau. La vapeur monte, condense, redescend. Évite la perte de réactifs. Sécurité : pierre ponce contre l'ébullition.",
     "3️⃣ VÉRIFICATION ÉQUILIBRE : 1 mol acide + 1 mol alcool → 0,67 mol ester + 0,33 mol acide non transformé (alcool primaire). Pour atteindre 95% : excès d'alcool (3 mol) ou retirer l'eau.",
     "4️⃣ HYDROLYSE (réaction inverse) : ester + eau (+ H+ catalyseur) → acide + alcool. Même équilibre. Saponification (avec NaOH) = hydrolyse basique → savon !",
     "5️⃣ CHROMATOGRAPHIE CCM : éluant éther/acétate. Déposer acide pur, alcool pur, ester pur, mélange réactionnel. Comparer Rf après révélation iode. Vérifier présence/absence de chaque espèce.",
     "6️⃣ NOMENCLATURE : éthanoate d'éthyle = CH₃-COO-C₂H₅. 'éthan-OATE' = acide éthanoïque. 'éthyle' = éthanol. Acétate (anc.) = éthanoate.",
     "7️⃣ APPLICATION INDUSTRIELLE : arômes alimentaires de synthèse moins chers que les naturels. Glycéride (ester de glycérol) = corps gras, savons. Polyesters = textiles (PET = bouteille plastique).",
   ],
   quiz:[
     {q:"Estérification : produits formés :",opts:["Ester + H₂","Acide + alcool","Ester + H₂O","Alcool + base"],ans:2,exp:"R-COOH + R'-OH ⇌ R-COO-R' + H₂O. Eau est un sous-produit."},
     {q:"Pour déplacer l'équilibre vers l'ester, on peut :",opts:["Augmenter T fortement","Retirer l'eau formée","Ajouter eau","Diminuer alcool"],ans:1,exp:"Le Chatelier : retirer un produit déplace vers la formation. Excès d'alcool aussi."},
     {q:"Rôle du H₂SO₄ dans estérification :",opts:["Réactif","Solvant","Catalyseur","Produit"],ans:2,exp:"H₂SO₄ catalyse la réaction (accélère sans être consommé). Ne change PAS la position de l'équilibre."},
     {q:"Rendement avec alcool PRIMAIRE :",opts:["95%","67%","100%","50%"],ans:1,exp:"~67% pour alcool primaire (RCH₂OH). Secondaire ~50%, tertiaire ~5%."},
     {q:"Éthanoate d'éthyle, formule :",opts:["CH₃CH₂OH","CH₃COOH","CH₃COO-CH₂CH₃","CH₃CHO"],ans:2,exp:"Éthanoate = CH₃-COO-, éthyle = -CH₂CH₃. Donne odeur de colle/dissolvant ongles."},
     {q:"Saponification d'un ester avec NaOH donne :",opts:["Ester + eau","Acide carboxylique + alcool","Ion carboxylate + alcool","Aldéhyde"],ans:2,exp:"Hydrolyse basique : R-COO-R' + NaOH → R-COO⁻Na⁺ (savon) + R'-OH. Irréversible."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv32",titre:"Climat Mondial & Changement Climatique",matiere:"Géographie",cat:"geo",
   classe:"2nde-1ère",ico:"🌍",color:"#0EA5E9",gratuit:true,
   desc:"Climats, biomes, effet de serre, réchauffement, conséquences. Programme 2nde-1ère.",
   theorie:"🌍 5 GRANDS CLIMATS :\n• Équatorial (chaud humide toute l'année — forêt) — Cameroun sud, Amazonie\n• Tropical (saisons sèche/humide — savane) — Cameroun nord, Sahel\n• Désertique (sec extrême) — Sahara, Atacama\n• Tempéré (4 saisons) — Europe, Amérique du nord\n• Polaire (froid extrême) — Arctique, Antarctique\n\n🌡️ EFFET DE SERRE : gaz (CO₂, CH₄, vapeur eau) piègent rayonnement infrarouge → réchauffement. NATUREL : +33°C sinon Terre = -18°C en moyenne.\n\n📈 CHANGEMENT CLIMATIQUE : +1,1°C depuis 1880 dû activité humaine (combustion fossiles, déforestation).\n\n⚠️ CONSÉQUENCES : fonte glaces, montée océans, sécheresses Sahel, événements extrêmes, biodiversité.",
   experience:[
     "1️⃣ MESURE LOCALE : relever T et pluies mensuelles à Yaoundé (1 an). Tracer climogramme. Identifier saisons : grande saison sèche (déc-fév), petite saison pluies (mars-mai), petite saison sèche (juin-août), grande saison pluies (sept-nov).",
     "2️⃣ COMPARAISON CLIMATS : Yaoundé (équatorial) ~25°C cst, 1600mm pluies. Maroua (tropical sahélien) 28°C, 800mm. Paris (tempéré) 12°C, 650mm. Tracer 3 climogrammes côte à côte.",
     "3️⃣ EFFET DE SERRE — MAQUETTE : 2 bouteilles plastique transparentes, une fermée, une ouverte. Mettre au soleil 30min. Mesurer T intérieure. La fermée = +5 à 10°C. Analogie atmosphère terrestre.",
     "4️⃣ COURBE CO₂ MAUNA LOA (1958-2026) : 315 ppm → 425 ppm. Augmentation continue. Causes : combustion fossiles (charbon, pétrole, gaz) + déforestation.",
     "5️⃣ FONTE DE L'ARCTIQUE : photos satellites 1980 vs 2020. Surface banquise été : -40%. Conséquence : albédo (réflexion) ↓ → réchauffement amplifié (rétroaction positive).",
     "6️⃣ CAMEROUN — LAC TCHAD : 1963 = 25 000 km². 2025 = 1 500 km² (-94%). Causes : sécheresse + irrigation excessive. Crise écologique + sécurité (Boko Haram exploite la misère).",
     "7️⃣ SOLUTIONS : transition énergétique (solaire, éolien, hydraulique), reboisement, transports communs, sobriété. Accord de Paris 2015 : limiter à +1,5°C. Aujourd'hui : on est à +1,1°C, trajectoire actuelle +2,7°C en 2100.",
   ],
   quiz:[
     {q:"Climat du sud Cameroun (Yaoundé) :",opts:["Tropical sec","Équatorial","Désertique","Méditerranéen"],ans:1,exp:"Yaoundé = équatorial : chaud (25°C cst), humide toute l'année (1600mm pluies), 2 saisons sèches courtes."},
     {q:"Principal gaz à effet de serre dû à l'homme :",opts:["O₂","CO₂","N₂","H₂"],ans:1,exp:"CO₂ = principal GES anthropique (combustion fossiles). Aussi méthane (élevage), N₂O (engrais), CFC (climatisation)."},
     {q:"Réchauffement climatique observé depuis 1880 :",opts:["+0,1°C","+1,1°C","+5°C","+10°C"],ans:1,exp:"+1,1°C en moyenne globale. Mais +2°C en Arctique. Cameroun : +1,5°C dans certaines régions."},
     {q:"Lac Tchad a perdu :",opts:["10%","50%","94%","Aucune perte"],ans:2,exp:"Surface 1963 : 25 000 km². 2025 : 1 500 km². Perte ~94% : sécheresses + sur-irrigation."},
     {q:"Sans effet de serre naturel, T moyenne Terre serait :",opts:["+15°C","0°C","-18°C","-50°C"],ans:2,exp:"Sans GES naturels, Terre = -18°C (gelée). Avec GES naturels = +15°C. Pratique pour la vie. Le problème = excès anthropique."},
     {q:"Énergie renouvelable la plus utilisée au Cameroun :",opts:["Solaire","Hydraulique","Éolienne","Géothermique"],ans:1,exp:"Cameroun = 75% hydraulique (Edéa, Songloulou, Lom Pangar). Solaire en croissance."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:null},

  {id:"lv33",titre:"Algorithmes : Tri & Complexité",matiere:"Informatique",cat:"info",
   classe:"1ère-Tle TI",ico:"💻",color:"#1E40AF",gratuit:false,plan:"Sciences",
   desc:"Tri à bulles, tri par sélection, complexité O(n²), tri rapide O(n log n). Programme TI.",
   theorie:"💻 ALGO = suite d'instructions pour résoudre un problème.\n\n📊 COMPLEXITÉ = nombre d'opérations en fonction de n.\n• O(1) : constant (accès à tableau[i])\n• O(log n) : logarithmique (recherche dichotomique)\n• O(n) : linéaire (parcours simple)\n• O(n²) : quadratique (tris naïfs)\n• O(n log n) : log-linéaire (tris efficaces)\n• O(2^n) : exponentiel (FORCE BRUTE)\n\n🔢 TRI À BULLES : compare voisins, échange si désordre. Répète. Pire cas O(n²).\n\n⚡ TRI RAPIDE (Quicksort) : choisir pivot, partitionner < et >, récursion. Moyenne O(n log n).",
   experience:[
     "1️⃣ ALGO TRI BULLES (Python-like) :\n  for i de 0 à n-1:\n    for j de 0 à n-i-1:\n      si t[j] > t[j+1]:\n        échanger(t[j], t[j+1])\nDessine les étapes sur [5,3,8,1].",
     "2️⃣ ÉTAPES SUR [5,3,8,1] :\nPassage 1: [3,5,8,1] → [3,5,8,1] → [3,5,1,8]\nPassage 2: [3,5,1,8] → [3,1,5,8] → fini\nPassage 3: [1,3,5,8] → trié !",
     "3️⃣ COMPTER LES COMPARAISONS : pour n=4, max = 4×3 = 12 comparaisons. Pour n=10 = 90. Pour n=1000 = 1 million. Quadratique.",
     "4️⃣ TRI PAR SÉLECTION : trouver le min, le mettre en 1er. Recommencer avec [1:]. Aussi O(n²) mais moins d'échanges.",
     "5️⃣ RECHERCHE DICHOTOMIQUE (tableau trié) : couper en 2 à chaque étape. n=1 000 000 → 20 comparaisons (log₂ 10⁶). C'est pourquoi le tri préalable est utile.",
     "6️⃣ QUICKSORT — PIVOT : choisir t[0]=5 dans [5,3,8,1,4]. Partition : <5 → [3,1,4], =5 → [5], >5 → [8]. Récursion sur chaque partie.",
     "7️⃣ COMPARER PERFORMANCES : n=10⁶ éléments. Tri bulles : 10¹² ops (~17 min). Quicksort : 2×10⁷ ops (~20 ms). Différence x50 000 !",
   ],
   quiz:[
     {q:"Complexité du tri à bulles pire cas :",opts:["O(n)","O(n²)","O(n log n)","O(1)"],ans:1,exp:"Tri à bulles : 2 boucles imbriquées → O(n²). Pour n=1000, ~10⁶ opérations."},
     {q:"Algorithme le plus rapide pour grands n :",opts:["Tri à bulles O(n²)","Tri par sélection O(n²)","Quicksort O(n log n)","Tous équivalents"],ans:2,exp:"Quicksort/Mergesort en O(n log n) sont bien plus rapides pour grands n. Pour n=10⁶ : O(n²)=10¹² vs O(n log n)=2×10⁷."},
     {q:"Recherche dichotomique exige :",opts:["Tableau non trié","Tableau trié","Tableau vide","Récursion"],ans:1,exp:"Dichotomie requiert un tableau trié. Coupe en 2 à chaque étape. Complexité O(log n)."},
     {q:"Pour n=1024, log₂(n) =",opts:["10","100","1024","2"],ans:0,exp:"2¹⁰ = 1024 donc log₂(1024) = 10. Très efficace : dichotomie sur 1024 éléments = 10 comparaisons max."},
     {q:"Complexité de l'accès t[i] dans un tableau :",opts:["O(log n)","O(n)","O(1)","O(n²)"],ans:2,exp:"Accès direct via indice = O(1) = constant. C'est la force des tableaux vs listes chaînées."},
     {q:"Tri sur [3,1,2] avec tri à bulles, 1er échange :",opts:["Aucun","3 et 1","1 et 2","3 et 2"],ans:1,exp:"Compare 3 et 1 → 3>1 donc échange → [1,3,2]. Puis compare 3 et 2 → [1,2,3] trié."},
   ],
   ressource:"https://minesec-distancelearning.cm",pack:"Sciences"},

  // ═══ SECTION ANGLOPHONE (GCE) — labs in English ═══
  {id:"lv40",titre:"Electric Circuits Lab (GCE Physics)",matiere:"Physics",cat:"english",
   classe:"Form 3-5",ico:"🔌",color:"#0891B2",gratuit:true,
   desc:"Build series and parallel circuits. Apply Ohm's Law, measure current, voltage and power. GCE O Level Physics (0580).",
   theorie:"⚡ Ohm's Law: V = I × R (V in volts, I in amperes, R in ohms).\n\n🔴 SERIES circuit: same current everywhere. V_total = V₁ + V₂. R_total = R₁ + R₂.\n🔵 PARALLEL circuit: same voltage across branches. I_total = I₁ + I₂. 1/R_total = 1/R₁ + 1/R₂.\n\n⚙️ Power: P = VI = I²R = V²/R (watts). Energy: E = Pt (joules). 1 kWh = 3.6 × 10⁶ J.\n\nGCE tip: Paper 1 MCQs often test unit conversions and circuit reasoning — show ALL working in Paper 2.",
   experience:[
     "1️⃣ APPARATUS: 4.5 V dry cell, two lamps, connecting wires, switch, ammeter, voltmeter. Close the switch and observe the lamp light up.",
     "2️⃣ SERIES: connect two lamps one after the other. Note both are dimmer; unscrew one — the other goes off. Conclusion: one path only.",
     "3️⃣ PARALLEL: connect the lamps side by side. Each glows at full brightness; unscrew one — the other stays on.",
     "4️⃣ AMMETER: connect IN SERIES. Record the current I in amperes.",
     "5️⃣ VOLTMETER: connect IN PARALLEL across a lamp. Record V and verify V = IR.",
     "6️⃣ Calculate the power of one lamp: P = VI. Express your answer in watts to 2 significant figures.",
   ],
   quiz:[
     {q:"V = 12 V and R = 400 Ω. The current I is:",opts:["0.02 A","0.03 A","0.06 A","0.12 A"],ans:1,exp:"I = V/R = 12/400 = 0.03 A (Ohm's Law)."},
     {q:"Two 100 Ω resistors in parallel give a total resistance of:",opts:["200 Ω","100 Ω","50 Ω","25 Ω"],ans:2,exp:"For two equal resistors in parallel: R/2 = 100/2 = 50 Ω."},
     {q:"In a series circuit, the current:",opts:["splits between components","is the same everywhere","is zero","doubles at each lamp"],ans:1,exp:"Series = one single path, so the same current flows through every component."},
     {q:"A 2 kW heater runs for 3 hours. Energy used:",opts:["6 J","6 kWh","2 kWh","666 kWh"],ans:1,exp:"E = P × t = 2 kW × 3 h = 6 kWh."},
   ],
   ressource:"https://camgceb.org",pack:null},

  {id:"lv41",titre:"Titration Lab — Acids & Bases (GCE Chemistry)",matiere:"Chemistry",cat:"english",
   classe:"Form 4-5 · Lower Sixth",ico:"🧪",color:"#6C56A6",gratuit:true,
   desc:"Neutralise an acid with a base using an indicator. Calculate concentration from titre values. GCE Chemistry (0515/0715).",
   theorie:"🧪 Neutralisation: acid + base → salt + water (e.g. HCl + NaOH → NaCl + H₂O).\n\npH scale: 0-6 acidic, 7 neutral, 8-14 alkaline. Indicators: methyl orange (red→yellow), phenolphthalein (colourless→pink).\n\n📐 Titration formula: (C₁V₁)/n₁ = (C₂V₂)/n₂ where C = concentration (mol/dm³), V = volume, n = mole ratio from the balanced equation.\n\nGCE tip: always read the burette at eye level, record titres to 2 decimal places, and average only CONCORDANT results (within 0.10 cm³).",
   experience:[
     "1️⃣ APPARATUS: burette, pipette (25.0 cm³), conical flask, white tile, NaOH solution (unknown), 0.10 mol/dm³ HCl, phenolphthalein.",
     "2️⃣ Pipette 25.0 cm³ of NaOH into the flask. Add 2-3 drops of phenolphthalein → solution turns pink.",
     "3️⃣ Fill the burette with HCl. Record the initial reading (e.g. 0.00 cm³).",
     "4️⃣ Add acid slowly while swirling. Near the end-point, add DROP BY DROP until the pink JUST disappears.",
     "5️⃣ Record the final reading. Titre = final − initial. Repeat until two concordant titres.",
     "6️⃣ Calculate: moles HCl = C × V/1000, then use the 1:1 ratio to find the NaOH concentration.",
   ],
   quiz:[
     {q:"25.0 cm³ of NaOH needs 20.0 cm³ of 0.10 mol/dm³ HCl. C(NaOH) = ?",opts:["0.05 mol/dm³","0.08 mol/dm³","0.10 mol/dm³","0.125 mol/dm³"],ans:1,exp:"Moles HCl = 0.10 × 0.020 = 0.002. 1:1 ratio → C = 0.002/0.025 = 0.08 mol/dm³."},
     {q:"Phenolphthalein in alkali is:",opts:["red","colourless","pink","blue"],ans:2,exp:"Phenolphthalein: colourless in acid, pink in alkali."},
     {q:"Concordant titres must agree within:",opts:["1.0 cm³","0.5 cm³","0.10 cm³","0.01 cm³"],ans:2,exp:"GCE practical standard: titres within 0.10 cm³ are concordant and may be averaged."},
     {q:"The salt formed from HCl + NaOH is:",opts:["Na₂SO₄","NaCl","NaNO₃","Na₂CO₃"],ans:1,exp:"Hydrochloric acid gives chlorides: NaCl (common salt)."},
   ],
   ressource:"https://camgceb.org",pack:null},

  {id:"lv42",titre:"Cell Division — Mitosis & Meiosis (GCE Biology)",matiere:"Biology",cat:"english",
   classe:"Form 5 · Sixth Form",ico:"🧫",color:"#059669",gratuit:false,plan:"Complet",
   desc:"Observe the stages of mitosis and meiosis, compare both processes and link them to growth and reproduction. GCE Biology (0510/0710).",
   theorie:"🧬 MITOSIS: one division → 2 identical diploid cells (growth, repair, asexual reproduction). Stages: Prophase, Metaphase, Anaphase, Telophase (PMAT).\n\n🧬 MEIOSIS: two divisions → 4 genetically different haploid gametes (sexual reproduction). Crossing-over in Prophase I creates variation.\n\nKey comparison: mitosis keeps the chromosome number (2n→2n); meiosis halves it (2n→n).\n\nGCE tip: examiners reward correctly LABELLED diagrams and the spelling of each phase.",
   experience:[
     "1️⃣ Observe the prepared onion root tip slide: identify cells in interphase (most numerous) and the four mitosis phases.",
     "2️⃣ Draw one cell in METAPHASE: chromosomes aligned on the equator, spindle fibres attached to centromeres.",
     "3️⃣ Count 50 cells and record how many are in each phase → estimate the relative duration of each phase.",
     "4️⃣ Compare with a meiosis diagram: spot crossing-over (chiasmata) in Prophase I.",
     "5️⃣ Build the comparison table: number of divisions, daughter cells, chromosome number, genetic identity.",
   ],
   quiz:[
     {q:"Mitosis produces:",opts:["4 haploid cells","2 identical diploid cells","2 haploid cells","4 different diploid cells"],ans:1,exp:"Mitosis = one division, two genetically identical diploid daughter cells."},
     {q:"Crossing-over happens during:",opts:["Metaphase II","Prophase I","Anaphase II","Telophase I"],ans:1,exp:"Crossing-over (exchange between homologous chromatids) occurs in Prophase I of meiosis."},
     {q:"In humans (2n = 46), a gamete contains:",opts:["46 chromosomes","92 chromosomes","23 chromosomes","12 chromosomes"],ans:2,exp:"Meiosis halves the number: n = 23 chromosomes in sperm and egg cells."},
     {q:"The phase where chromosomes line up at the equator:",opts:["Prophase","Metaphase","Anaphase","Telophase"],ans:1,exp:"Metaphase = Middle: chromosomes align on the metaphase plate."},
   ],
   ressource:"https://camgceb.org",pack:null},

  // ═══ ENSEIGNEMENT TECHNIQUE — labos pratiques ═══
  {id:"lv43",titre:"Compta OHADA : du Journal au Bilan",matiere:"Comptabilité",cat:"technique",
   classe:"2nde-Tle CG/G2 · STT",ico:"📒",color:"#B45309",gratuit:true,
   desc:"Enregistre les opérations d'une PME de Douala, monte la balance et établis le bilan OHADA. Série CG/G2, Probatoire et BAC STT.",
   theorie:"📒 PARTIE DOUBLE : tout enregistrement a un DÉBIT = un CRÉDIT.\n\nClasses de comptes OHADA : 1 capitaux ; 2 immobilisations ; 3 stocks ; 4 tiers (clients 411, fournisseurs 401) ; 5 trésorerie (521 banque, 571 caisse) ; 6 charges ; 7 produits.\n\n🧾 TVA Cameroun : 19,25 %. TVA collectée (4431) sur ventes ; TVA récupérable (4452) sur achats.\n\nChaîne comptable : pièce justificative → JOURNAL → GRAND-LIVRE → BALANCE → BILAN + COMPTE DE RÉSULTAT.\nÉquilibre du bilan : ACTIF = PASSIF, toujours.",
   experience:[
     "1️⃣ Une PME de Douala achète des marchandises à 500 000 F HT à crédit. Calcule la TVA (19,25 %) et passe l'écriture : 601 Achats (D), 4452 TVA (D), 401 Fournisseurs (C).",
     "2️⃣ Vente de marchandises 800 000 F HT, encaissée en banque. Passe l'écriture : 521 (D 954 000), 701 (C 800 000), 4431 (C 154 000).",
     "3️⃣ Paiement du loyer 150 000 F en espèces : 622 Locations (D), 571 Caisse (C).",
     "4️⃣ Reporte chaque compte au grand-livre et calcule les soldes.",
     "5️⃣ Monte la balance : total des débits = total des crédits, sinon cherche l'erreur.",
     "6️⃣ Établis le bilan simplifié OHADA et vérifie ACTIF = PASSIF.",
   ],
   quiz:[
     {q:"TVA sur un achat de 500 000 F HT (19,25 %) :",opts:["75 000 F","96 250 F","100 000 F","192 500 F"],ans:1,exp:"500 000 × 0,1925 = 96 250 F."},
     {q:"Le compte 411 enregistre :",opts:["Les fournisseurs","Les clients","La banque","Le capital"],ans:1,exp:"411 = Clients (classe 4, tiers). Les fournisseurs sont au 401."},
     {q:"Dans la partie double, tout débit a :",opts:["Un solde","Un crédit équivalent","Une TVA","Un report"],ans:1,exp:"Principe fondamental : total débits = total crédits pour chaque écriture."},
     {q:"L'équilibre du bilan s'écrit :",opts:["Charges = Produits","Actif = Passif","Débit > Crédit","Capital = Trésorerie"],ans:1,exp:"Le bilan est TOUJOURS équilibré : Actif = Passif."},
   ],
   ressource:"https://officedubac.cm",pack:null},

  {id:"lv44",titre:"Câblage Industriel : Démarrage Étoile-Triangle (F3)",matiere:"Électrotechnique",cat:"technique",
   classe:"1ère-Tle F3",ico:"⚙️",color:"#0E7490",gratuit:true,
   desc:"Câble le circuit de puissance et de commande d'un démarrage étoile-triangle d'un moteur asynchrone triphasé. Série F3, BAC industriel.",
   theorie:"⚙️ Moteur asynchrone triphasé : le démarrage direct appelle 6 à 8 × In → le démarrage ÉTOILE-TRIANGLE réduit le courant de démarrage à ~1/3.\n\nPrincipe : démarrage en ÉTOILE (chaque enroulement sous U/√3) puis passage en TRIANGLE (pleine tension) après quelques secondes.\n\nCircuit de PUISSANCE : sectionneur Q1, contacteurs KM1 (ligne), KM2 (étoile), KM3 (triangle), relais thermique F1.\nCircuit de COMMANDE : BP marche S2, BP arrêt S1, temporisateur KA1, verrouillage électrique KM2/KM3 (jamais fermés ensemble !).\n\n⚠️ Sécurité : consignation, VAT (vérification d'absence de tension), EPI obligatoires.",
   experience:[
     "1️⃣ Identifie les bornes U1-V1-W1 / U2-V2-W2 de la plaque à bornes du moteur.",
     "2️⃣ Schéma de puissance : trace Q1 → KM1 → F1 → moteur ; KM2 court-circuite U2-V2-W2 (étoile) ; KM3 relie U1-W2, V1-U2, W1-V2 (triangle).",
     "3️⃣ Schéma de commande : S1 (NC) → S2 (NO) → KM1 auto-maintenu ; KA1 temporise 5 s puis ouvre KM2 et ferme KM3.",
     "4️⃣ VERROUILLAGE : place les contacts NC de KM2 et KM3 croisés — justifie pourquoi (court-circuit sinon).",
     "5️⃣ Simule la séquence : marche → étoile 5 s → triangle. Note le courant relevé à chaque phase.",
     "6️⃣ Liste les EPI et les étapes de consignation avant toute intervention.",
   ],
   quiz:[
     {q:"Le démarrage étoile-triangle réduit le courant de démarrage à environ :",opts:["1/2","1/3","1/√3","2/3"],ans:1,exp:"En étoile, chaque enroulement reçoit U/√3 → couple et courant divisés par 3."},
     {q:"KM2 (étoile) et KM3 (triangle) ne doivent JAMAIS être fermés ensemble car :",opts:["le moteur s'arrête","cela crée un court-circuit","le thermique déclenche","la tension chute"],ans:1,exp:"Fermés ensemble = court-circuit franc entre phases → verrouillage électrique ET mécanique obligatoire."},
     {q:"Le relais thermique F1 protège contre :",opts:["les courts-circuits","les surcharges prolongées","la foudre","l'inversion de phases"],ans:1,exp:"Le thermique protège des SURCHARGES ; les courts-circuits relèvent des fusibles/disjoncteur."},
     {q:"Avant d'intervenir sur l'armoire, la 1ère étape est :",opts:["mettre les gants","la consignation + VAT","démonter le moteur","appeler le chef"],ans:1,exp:"Consignation (séparation, condamnation) puis Vérification d'Absence de Tension : la base de la sécurité électrique."},
   ],
   ressource:"https://officedubac.cm",pack:null},

  {id:"lv45",titre:"Dessin Technique : Projections Orthogonales",matiere:"Dessin Technique",cat:"technique",
   classe:"1ère-4e année · 2nde-Tle F",ico:"📐",color:"#475569",gratuit:false,plan:"Complet",
   desc:"Représente une pièce mécanique en vues de face, dessus et gauche (méthode européenne). Toutes séries industrielles, CAP et BAC technique.",
   theorie:"📐 PROJECTION ORTHOGONALE (méthode européenne, symbole du tronc de cône) : la pièce est entre l'observateur et le plan de projection.\n\nDisposition : vue de FACE (principale) ; vue de DESSUS en dessous ; vue de GAUCHE à droite.\n\nTraits normalisés : fort continu (arêtes vues) ; interrompu fin (arêtes cachées) ; mixte fin (axes) ; fin continu (cotation).\n\n✏️ COTATION : ligne d'attache, ligne de cote, flèches, valeur en mm SANS unité. Jamais de cote répétée, jamais de cote sur trait caché si évitable.",
   experience:[
     "1️⃣ Observe la pièce en perspective (cale étagée percée). Choisis la vue de face = la plus représentative.",
     "2️⃣ Trace le cadre et le cartouche aux instruments (format A4, échelle 1:1).",
     "3️⃣ Dessine la vue de face : arêtes vues en trait fort, perçage caché en interrompu fin, axes en mixte fin.",
     "4️⃣ Déduis la vue de dessus par correspondance verticale (lignes de rappel).",
     "5️⃣ Déduis la vue de gauche par correspondance horizontale (utilise la ligne à 45°).",
     "6️⃣ Cote la pièce : longueur, largeur, hauteur, position et diamètre du perçage (Ø).",
   ],
   quiz:[
     {q:"En méthode européenne, la vue de dessus se place :",opts:["au-dessus de la vue de face","en dessous de la vue de face","à gauche","à droite"],ans:1,exp:"Méthode E : l'objet est entre l'œil et le plan → la vue de dessus se projette EN DESSOUS."},
     {q:"Les arêtes cachées se tracent en :",opts:["trait fort continu","trait interrompu fin","trait mixte fin","trait fin continu"],ans:1,exp:"Arêtes cachées = trait interrompu fin (pointillés)."},
     {q:"Un diamètre se cote avec le symbole :",opts:["R","Ø","D","⌀⌀"],ans:1,exp:"Ø devant la valeur (ex. Ø12) ; R est réservé aux rayons."},
     {q:"Le trait mixte fin sert à représenter :",opts:["les contours vus","les axes de symétrie","les hachures","le cartouche"],ans:1,exp:"Axes et plans de symétrie = trait mixte fin (tiret-point)."},
   ],
   ressource:"https://officedubac.cm",pack:null},
];
