/* Textes VERBATIM — enrichissement « Textes argumentatifs frais » (thème du mariage / condition de la femme + rapport Afrique-Occident). NE PAS RETOUCHER. */
const fraisDiouf = {
  source:"Fatou Diouf et Charles-Arnaud Ghosn, Le Scandale des mariages forcés, Éditions du Rocher, 2009",
  paras:[
    "Doit-on accepter, au nom du respect d’une culture, d’une identité, cette pratique qui impose un compagnon pour la vie à une femme, en faisant fi de ses sentiments ? L’amour au Mali, au Yémen, au Pakistan, est sous-tendu par le même désir, la même attirance que dans les pays occidentaux et « dans le monde blanc ». Prétendre que, au nom d’une prétendue culture, on aimerait différemment selon le pays est une insulte à la dignité humaine. C’est pourquoi le relativisme culturel, selon lequel « c’est ainsi depuis des siècles et ça ne changera jamais parce que c’est inscrit dans les gènes », représente à nos yeux un non-sens, l’affirmation d’un pseudo-droit à la différence culturelle aussi stupide que l’ethnocentrisme qui impose le principe de la supériorité d’une culture sur toutes les autres. Ce sentiment de supériorité, nous l’avons rencontré auprès de certaines « élites occidentales ». Ces dernières, prétendument ouvertes et tolérantes, s’indigneraient si on les accusait de mépris envers les cultures étrangères. Pourtant, elles révèlent leur vraie nature à travers ces petites phrases égrenées çà et là, au fil de nos entretiens, généralisant souvent des cas particuliers. Elles aiment ainsi évoquer l’exemple de ces filles qui se marient pour permettre à un compatriote expatrié de régulariser sa situation. Certains prétendent avec aplomb que « les familles africaines, maghrébines, turques et autres n’hésitaient pas à vendre leurs filles pour quelques euros et à transformer ces dernières en marchandise et en passeport vivant ». Même si pareils cas existent, ils nous apparaissent comme exceptionnels, car c’est d’abord pour préserver l’identité du groupe, et convaincus qu’ils agissent donc pour le bien de leurs filles, que les parents les marient. La régularisation pour les papiers n’est souvent qu’une conséquence. Ce sont sur ces exemples que s’appuient les nationalistes, défenseurs de l’uniformisation culturelle, pour stigmatiser des peuples et des pays, à leurs yeux sous-développés.",
    "Il y a peu encore, en Europe, les mariages étaient en grande partie arrangés. Molière en son temps avait d’ailleurs dénoncé cette pratique dans l’une de ses pièces   . Si aujourd’hui cette tradition se perpétue dans certaines contrées, les hommes sont capables d’évolution. C’est pourquoi il nous paraît capital de préserver des relations entre les anciennes générations, gardiennes de la coutume, et leurs enfants victimes. Ne jamais couper les ponts entre le Sud et le Nord, continuer coûte que coûte à maintenir le lien parents-enfants. Même conflictuel, il est porteur d’espérance et de changement.",
  ]};
const dTobner = {
  source:"Odile Tobner, « La vision de l’Afrique chez les présidents de la Cinquième République française », in L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Les six présidents qu’a connus la Cinquième République française se sont tous dits amis de l’Afrique. Mais l’examen de leurs propos et de leurs actes nous instruit sur le véritable rapport entretenu par la France avec ceux qu’elle a tenus si longtemps sous le joug de la colonisation. Le moins qu’on puisse dire, c’est que ce rapport est loin d’être clair. Il y a encore du chemin à faire pour parvenir au respect, qui vaut beaucoup mieux dans les relations entre États que l’amitié. N’est-ce pas le plus prestigieux de ces présidents, le général de Gaulle, qui a dit qu’un État digne de ce nom n’a pas d’amis ?",
  ]};
const dDioufChiffres = {
  source:"Fatou Diouf et Charles-Arnaud Ghosn, Le Scandale des mariages forcés, Éditions du Rocher, 2009",
  paras:[
    "Chaque jour, dans le monde, trois mille cinq cents jeunes filles de moins de quinze ans se marient. Ce chiffre hallucinant provient du rapport de l’une des plus grandes ONG de la planète, World Vision (vingt-trois mille permanents, deux cent vingt mille bénévoles) dont le siège est aux ÉtatsUnis. Publié en septembre 2008, il est le fruit d’un travail collectif émanant des différents correspondants de cette association, répartis dans le monde entier : Afghanistan, Bangladesh, Tchad, Éthiopie, Guatemala, Inde, Kenya... Intitulé « Before she’s ready » (« Avant qu’elle ne soit prête »), le document fournit des pourcentages qui font froid dans le dos : plus de 52 % des filles se marient avant quinze ans au Bangladesh, 37,6 % au Niger, 34,9 % au Tchad, 31,4 % en Éthiopie, 30,9 % en Inde, 30,6 % au Nigeria, 29,3 % en Mauritanie, 14,8 % au Nicaragua, etc.",
  ]};
const dCastanou = {
  source:"Yvan Castanou, 4 secrets d’un mariage réussi, Métanoia & Vie, 2024",
  paras:[
    "On attend du président qu’il soit toujours humain, toujours à l’écoute, impartial, généreux, courtois. Pourquoi ? Parce que ce sont les vertus exigées par l’institution de la présidence ! Le président doit être irréprochable et exemplaire parce qu’il incarne une institution, faute de quoi il la déshonore. Un président ne peut donc pas parler ou se comporter en public comme le citoyen lambda : il ne peut pas injurier les gens en public, parler avec légèreté, etc. il a l’obligation de se comporter d’une manière digne de la fonction de président de la République qu’il occupe.",
  ]};
module.exports = { fraisDiouf, dTobner, dDioufChiffres, dCastanou };