/* Textes VERBATIM extraits automatiquement de « Textes argumentatifs frais.docx » (répertoire de contraction). NE PAS RETOUCHER LE TEXTE. */
const fraisGassama431 = { // ~431 mots (tokens)
  source:"Makhily Gassama et All, L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Nos gouvernants ont trahi leurs peuples ; par incompétence, par cupidité, par couardise ou par insouciance, ils bradent nos ressources et nous affament ; ils tremblent encore devant l’ancienne puissance coloniale, qui n’a rien perdu de sa superbe et de son hégémonie, alors que, par ailleurs, ils broient, quotidiennement, la fragile dignité de leur peuple.",
    "Notre responsabilité est grande dans la balkanisation du continent et dans les guerres barbares qui retardent son développement, car nous n’avons pas su écouter et protéger les plus vaillants de nos hommes politiques. Kwame Nkrumah, le panafricaniste intransigeant, a été chassé de son pays comme un bandit de grand chemin ; Patrice Lumumba a été immolé comme un agneau de sacrifice pour le bien-être de la nation colonisatrice de son pays. Il était farouchement patriote, le jeune et vaillant Congolais ; si seulement il avait eu le soutien des nations, des prétendues « patries des droits de l’homme », des organisations internationales, pour empêcher le colonisateur de « souiller l’indépendance » de sa patrie ! Soutien des nations ? Que non ! Ce n’était qu’un Africain, un nègre, un sous-homme, un colonisé – le méritait-il ? Le téméraire Thomas Sankara a payé par le sang son amour pour son pays et son continent ; ainsi que sa haine implacable envers l’œuvre destructrice de ses aînés. Il n’était pas tendre, le jeune Burkinabé, devant l’insouciance des « pères de la nation » ; si seulement on lui avait laissé la chance de « pédaler jusqu’au sommet de la montagne », belle et virile image qu’il adorait5… Les exemples abondent et l’on rencontrera d’autres grandes figures du continent à travers les pages de cet ouvrage collectif. Ces martyrs ont été piégés tout comme leurs peuples, qui vont de surprises en surprises, devant les gestes irresponsables de ceux qui les dirigent depuis « les soleils des indépendances maléfiques » qui, « comme une nuée de sauterelles, tombèrent sur l’Afrique6 ». Il faut ressasser le passé pour sauver notre dignité. Le passé, levain du présent, truelle pour bâtir l’avenir ! Pourtant, c’est précisément au moment où le nouveau président de France, sous les menaces de la mondialisation, angoissé par les fractures les plus insidieuses qui fragilisent sa vieille société, au moment où il ne cesse d’évoquer la mémoire des grandes figures de la politique française pour tenter un sursaut national, au moment où il cherche à imposer la lecture de la lettre du jeune résistant français, Guy Môquet, dans toutes les écoles de la République, c’est bien à ce moment-là qu’il nous invite à cesser de ressasser notre histoire !",
  ]};
const fraisDembele364 = { // ~364 mots (tokens)
  source:"Demba Moussa Dembélé, Méconnaissance ou provocation délibérée ? in Makhily Gassama et All, L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Les quelques « réalisations » dont se targuent les apologistes du colonialisme, comme M. Sarkozy, étaient destinées à consolider la mainmise sur les colonies et à mieux organiser le pillage de leurs ressources au bénéfice de la métropole. Ces « réalisations » avaient également pour but la destruction systématique de la culture et de la mentalité des colonisés, au nom d’une prétendue « supériorité » de la civilisation des colons. Si bien que pratiquement aucune structure précoloniale majeure n’avait été épargnée par la détermination et la furie des colons à faire « table rase » de tout ce qu’ils avaient trouvé dans les pays conquis. Ainsi, la désarticulation et le caractère extraverti des économies africaines, l’État, les institutions monétaires et financières, sont-ils de purs produits de la colonisation. Par conséquent, comme le soutient à juste titre Samir Amin, l’échec du « développement » postcolonial traduit à la fois l’échec de la « décolonisation » et la faillite du capitalisme imposé à la périphérie du système91.",
    "Si l’on peut comprendre que M. Sarkozy ignore l’histoire de l’Afrique, par contre, il est difficile de comprendre sa méconnaissance – feinte ou réelle – des causes profondes et véritables des problèmes de développement économique et social auxquels l’Afrique fait face. M. Sarkozy et d’autres comme lui pensent que les Africains sont les principaux responsables de l’échec du développement postcolonial. Ils préfèrent mettre l’accent sur leurs coupables  favoris  comme  la  «  corruption  »,  la  «  prévarication  »,  la",
    "« mauvaise gouvernance », entre autres. Certes, comme le dit M. Sarkozy,",
    "« la colonisation n’est pas responsable de toutes les difficultés actuelles de l’Afrique » mais l’héritage colonial reste parmi les causes premières de la crise que traverse le continent africain, comme le confirme l’analyse qui suit.",
    "Dans cet héritage, on trouve la division internationale du travail imposée à l’Afrique et qui a fait d’elle un continent fournisseur de matières premières et de produits de base. Et le système dominant, les anciennes puissances coloniales en particulier, a tout fait pour maintenir cette division du travail. Les politiques néolibérales, surtout celles imposées par les institutions financières internationales, ont accentué cette division, rendant ainsi les économies africaines plus vulnérables aux chocs exogènes.",
  ]};
const fraisSakho538 = { // ~538 mots (tokens)
  source:"Bamba Sakho,  Entre ruse et archaïsme in Makhily Gassama et All, L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "De nombreux économistes du continent, pourtant bardés de diplômes, occultent volontairement la question fondamentale de l’asservissement monétaire des pays de la zone CFA pour se livrer à des dissertations oiseuses sur un développement économique impossible. Peu courageux, leur cadre de réflexion est tracé par les institutions de Bretton Woods, dont toutes les nations ambitieuses et résolument tournées vers le développement cherchent à s’éloigner, à l’instar des Sud-Américains qui viennent de porter sur les fonts baptismaux la Banque du Sud, qui a pour vocation de se substituer au FMI et à la Banque mondiale. Les perspectives économiques et financières développées par Joseph Tchundjang Pouemi, aujourd’hui reprises par des économistes comme Kako Nubukpo, sont délaissées au profit d’une servitude",
    "assumée.",
    "De nombreux historiens africains, formés par leurs maîtres africanistes, ne peuvent penser l’Afrique dans son entièreté, préférant adopter le paradigme d’une Afrique éclatée, morcelée, sans aucune continuité historique alors que la réalité des liens historiques singuliers des peuples du continent est clairement attestées par la linguistique, la toponymie, l’histoire des civilisations, etc. Le retard de l’intégration africaine tient en grande partie de la survivance de la vision ethniciste et tribaliste élaborée par l’ethnologie coloniale et encore aujourd’hui transmise de génération en génération par le canal éducatif.",
    "Les systèmes éducatifs sont viciés à la base par l’usage même des langues étrangères comme uniques médiums d’enseignement dans la plupart des pays africains et également par l’absence d’une vision prospective de développement de l’éducation qui intègre, dans un cadre cohérent, les réalités sociales, historiques et économiques du continent.",
    "La complicité des politiques, dont la survie dépend très souvent des soutiens multiformes dont ils bénéficient en retour, et leur discours elliptique ont favorisé la survivance du système de domination que subissent les pays africains.",
    "Dans tous les domaines, la mentalité d’assistanat est encouragée, parfois avec la complicité de nombreuses organisations et institutions internationales, au détriment d’un développement réel des compétences et des capacités nationales. La novlangue alimentée par des concepts misérabilistes (pays pauvre très endetté, aide, coopération, etc.) et leurs déclinaisons multiples, adoptées par les Africains eux-mêmes, contribuent puissamment à développer et maintenir des mentalités de subordination.",
    "Le peu de considération apparente et fallacieuse, dont pouvait bénéficier toute cette élite docile, s’évapore au fur et à mesure que le dispositif de domination se craquelle, laissant apparaître la vraie nature implacable de tout système d’oppression et d’asservissement : le mépris, exprimé dans une forme exquise par Sarkozy. C’est là une de ses prouesses, celle de faire comprendre à cette élite africaine frappée de surdité et de cécité intellectuelle toute l’importance que le système qu’il représente pouvait accorder à l’Afrique. Malgré cette performance, des voix africaines s’élèvent encore pour acclamer le maître.",
    "Face aux forces de régression, existe heureusement une dynamique de",
    "pensée africaine de progrès, animée par une génération d’hommes et de femmes patriotiques, certes minoritaires au sein de l’élite dirigeante, mais dont la puissance des convictions et la justesse des engagements finiront inexorablement par triompher. Elle s’appuie sur les jalons posés par les aînés, à l’image de Cheikh Anta Diop, dont la posture intellectuelle et l’intégrité, le courage et la persévérance, le travail de déconstruction et de démystification méticuleux mais aussi de refondation ont fini par triompher des thèses de l’africanisme raciste définitivement vaincu.",
  ]};
const fraisNgom507 = { // ~507 mots (tokens)
  source:"Abdoulaye NGOM, Mobilisations familiales et migrations intercontinentales, L’Harmattan, 2019",
  paras:[
    "La Casamance est l’une des régions où les enfants sont mis à contribution, dès leur plus jeune âge, dans la production des ressources des familles en raison de la pauvreté. Dans les villages, les enfants sont très tôt intégrés dans le système de production agricole, contrairement à leurs pairs qui sont en ville. Cette situation tient au fait qu’en raison de l’appartenance de leur père à une position particulière dans la sphère sociétale (agriculteur ou paysan), il est tout à fait naturel qu’ils doivent contribuer à la production agricole afin de perpétuer la tradition. Le rôle des enfants dans la production est également important car très tôt le matin, ils accompagnent leurs parents dans les champs et lorsqu’ils arrivent à un âge assez avancé, ils disposent même d’une parcelle de terre. Benoit Ferry (1976) montre que très tôt les enfants s’efforcent de participer à la production des ressources et aux activités domestiques. En milieu rural, certains enfants ne vont pas à l’école et constituent de fait une valeur ajoutée en termes de bras dans la production domestique. Mettant en évidence cette forte implication des enfants dans la production agricole, Daniel Bertaux (1977) montre que « la famille paysanne se distingue des petits producteurs urbains : la production agricole peut utiliser le travail des enfants, et ce travail lui est nécessaire. On sait que les rapports institués de transmission de la terre ont une influence considérable sur la production anthroponomique en milieu paysan. » Par contre, dans les familles où les parents ont une certaine aisance financière, tout comme dans les familles moyennes, plutôt que de mettre à contribution les enfants dans la production des ressources, les parents veillent à leur donner de bonnes conditions afin qu’ils puissent étudier. Face aux difficultés et à l’incapacité des chefs de famille à assurer la survie du ménage, on observe que les enfants sont mis à profit dans la production et jouent même dans certains cas un rôle important dans la prise en charge des dépenses quotidiennes.",
    "L’économie domestique dans les familles en milieu urbain",
    "À la différence du mode de production des familles en milieu rural, les familles qui vivent en milieu urbain adoptent diverses stratégies dans la production des ressources nécessaires. Ceci dans la mesure où la diversité des activités en milieu urbain permet une large marge de manœuvre aux membres des familles, contrairement aux campagnes où il n'y a que l’agriculture et l’élevage. Dans le mode de production de la famille en ville, tous les membres de la famille participent à la diversification des ressources. Même si le chef de famille occupe un emploi qui génère des revenus, cela n’empêche en aucun cas la femme de s’atteler à des activités qui lui permettent de contribuer aux charges familiales. Les dépenses en ville (loyer, factures d’eau et d’électricité...) étant plus nombreuses qu'à la campagne, les charges familiales sont plus lourdes et il y a ainsi nécessité pour l’ensemble des membres - du moins pour ceux ayant un emploi - de contribuer activement à la génération des ressources du ménage.",
  ]};
const fraisNgom526 = { // ~526 mots (tokens)
  source:"Abdoulaye NGOM, Migration clandestine sénégalaise vers l’Europe, L’Harmattan, 2020",
  paras:[
    "Les discours politiques tenus sur les migrations clandestines",
    "Dans les pays d’immigration ou d’accueil des migrants (Espagne, Italie, France, Grèce, Allemagne...), la migration est le plus souvent utilisée à des fins de campagne politique, ce qui du reste peut constituer à la longue un handicap dans la résolution de la crise des migrants qui est au cœur de l’actualité mondiale, notamment depuis que de nombreux réfugiés syriens et d’autres nationalités ont commencé à fouler le sol de certains pays européens. En France par exemple, les opinions et les avis sont partagés entre les partis de gauche et ceux de droite et d’extrême droite, qui n’ont pas les mêmes points de vue concernant la question des migrants, des réfugiès et de la gestion des migrations dans son ensemble. Dans le contexte actuel de crise, au sein d’un environnement économique difficile dans tous les pays européens qui font face à de multiples stratégies afin de gérer les problèmes auxquels sont confrontées leurs populations, évoquer le problème de la migration clandestine revient à susciter aussi bien dans le camp des hommes politiques que dans celui de la population locale des prises de positions hostiles à ces milliers de candidats à la migration qui tentent depuis plusieurs années maintenant à rejoindre la forteresse Europe à bord de pirogues, et dont les arrivées massives à un moment donné sur le territoire peut constituer un problème qui vient s’ajouter aux maux déjà existants.",
    "L’instrumentalisation politique des migrations clandestines est dû au fait que de nombreux chefs de partis politiques et de dirigeants savent que c’est une problématique qui peut leur permettre de gagner quelques voix lors des élections en prônant la préférence nationale, comme c’est le cas du Front National (FN). Mais il y a également la volonté de parler d’une question qui depuis longtemps constitue un problème et un enjeu de société, puisqu’il ne s’agit pas, loin de là, d’une question nouvelle : les migrations ont de tout temps existé dans presque toutes les sociétés du monde. Elles ont juste pris de l’envergure ces dernières années avec les migrants qui proviennent de l’autre côte de la rive méditerranéenne, par l’entremise de pirogues, ce qui a propulsé la migration clandestine au devant de la scène médiatique internationale. Concernant la tendance à coupler la migration avec d’autres problèmes sociaux, Abdelmalek Sayad (2006) rappelle que celle-ci apparait comme «produit, le plus souvent, d’une problématique imposée de l’extérieur, et à laquelle il n’est toujours pas facile d’échapper, le discours (scientifique ou non) tenu sur l’immigré et sur l’immigration se condamne, pour pouvoir parler de son objet, à le coupler avec toute une série d’autres objets ou d’autres problèmes». Dans les pays de départ des candidats à la migration, on constate moins cette préoccupation à propos des migrations clandestines. En effet, nombre de dirigeants africains, même s’ils sont au courant de l’ampleur du phénomène et du nombre de décès, semblent être dépassés par la situation de ces jeunes. Ils n’arrivent pas à empêcher leur exil, malgré les moyens coercitifs mis en œuvre le long des côtes de l’atlantique (surveillance maritime, campagnes de sensibilisation, lutte contre les passeurs et toutes personnes impliquées dans ces voyages par pirogue...).",
  ]};
const fraisSiribie606 = { // ~606 mots (tokens)
  source:"Mahamadou Siribié, Violence symbolique d’un discours crépusculaire in Makhily Gassama et All, L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Combien de temps va-t-on entretenir l’illusion que l’Aide Publique au Développement (APD) qui, parfois, se confond avec l’aide humanitaire, sortira le continent africain du sous-développement ? Les dirigeants africains n’ont encore pas compris que cette aide, au même titre que les dettes qu’ils contractent depuis les indépendances et qui lient les générations futures, est un instrument de domination politique, économique et idéologique de l’Occident. Il y a vingt ans, Thomas Sankara, le révolutionnaire burkinabé, assassiné en 1987 par ses frères d’armes, faisait le lien entre remboursement et néocolonialisme. « La dette sous sa forme actuelle est une reconquête savamment organisée de l’Afrique, pour que sa croissance et son développement obéissent à des paliers, à des normes qui nous sont totalement étrangers, faisant en sorte que chacun de nous devienne l’esclave financier, c’est-à-dire esclave tout court, de ceux qui ont eu l’opportunité, la ruse, la fourberie de placer les fonds chez nous avec l’obligation de les rembourser », dénonça-t-il dans son discours prononcé lors d’un sommet de la défunte Organisation de l’Unité Africaine (OUA), à Addis-Abeba, en juillet 1987. Le temps semble lui donner raison. Car, en 2002, dans son rapport intitulé « Le développement économique en Afrique. Endettement viable : oasis ou mirage ? », la Conférence des Nations Unies pour le Commerce Et le",
    "Développement (CNUCED) présentait des arguments économiques pertinents en faveur d’une annulation totale de la dette de l’Afrique. Selon ce rapport, entre 1970 et 2002, l’Afrique a reçu 540 milliards de dollars environ en prêts, mais, bien qu’elle ait remboursé près de 550 milliards de dollars en principal et intérêts, elle affichait encore un encours de dette de 295 milliards de dollars fin 2002. Le rapport conclut en ces termes : « Pour que l’Afrique puisse réduire la pauvreté de moitié d’ici à 2015, conformément aux objectifs du Millénaire pour le développement, il faut à tout le moins que les niveaux de croissance doublent pour s’établir à environ 7 ou 8 % par an pour la prochaine décennie, ce qui est financièrement incompatible avec les niveaux de service de la dette, actuels ou projetés289. » Même le montant des remises de dette, qui s’élèvent à environ 43 milliards de dollars pour les pays pauvres très endettés, parmi lesquels quatorze pays africains, accordées lors du sommet du G8290 à Gleneagles en Écosse, ne suffit pas à desserrer l’étau de la dette africaine. Comme on peut le constater, ce discours d’un révolutionnaire visionnaire reste toujours d’actualité : il est à l’antipode de celui de Nicolas Sarkozy.",
    "Il faudrait se poser la question de savoir pourquoi « l’Afrique a toujours faim » alors qu’elle est riche. Les causes du « mal de l’Afrique » ne sont pas celles relevées dans le discours de Nicolas Sarkozy. Les causes du mal africain sont profondes, elles sont endogènes et exogènes. La supposée « mission civilisatrice » de l’Occident a inculqué dans le mental de l’Africain la notion de la « différence » avec l’homme blanc. Pour Albert Memmi, « l’utilisation de la différence contre autrui, et afin de trouver profit dans cette stigmatisation, a légitimé la colonisation. Les colonisateurs ont expliqué, légitimé leur présence dans les colonies par les soi-disant carences du colonisé. Cette colonisation fut un système de rapines291 ». Le président français a valorisé cette « différence » dans son discours de Dakar en affirmant que « la civilisation musulmane, la chrétienté, la colonisation, au- delà des crimes et des fautes qui furent commises en leur nom et qui ne sont pas excusables, ont ouvert les cœurs et les mentalités africaines à l’universel et à l’histoire ». Comme si l’Afrique n’avait pas connu de grandes civilisations.",
  ]};
const dGassamaConcession = { // ~96 mots (tokens)
  source:"Makhily Gassama et al., L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Certes nous ne sommes pas innocents dans les souffrances intolérables que continuent d’endurer nos populations : guerres fratricides, violences génocidaires, dictatures, corruptions, gaspillage et pillage de nos ressources, malgouvernance, persistance du pacte colonial, etc. Nous ne sommes pas innocents dans les désastres causés par la Françafrique, même si ces maux sont souvent suscités, provoqués et entretenus par des forces extérieures, par des individus et des groupes d’intérêts étrangers, prêts à tous les crimes pour consolider, élargir et sauver les privilèges – que nos gouvernants leur ont sciemment accordés – au détriment du développement de nos pays.",
  ]};
const dGassamaDemande = { // ~112 mots (tokens)
  source:"Makhily Gassama et al., L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Ce que nous sommes en droit de demander à la France, à ses élites politiques et économiques, à ses intellectuels, à ses hommes et femmes des médias, c’est le respect qu’on doit, sans hypocrisie, à tout homme, le respect qu’ils doivent à nos mérites, à ce que nous leur avons apporté militairement, car nos pères furent braves ; matériellement, car nos matières premières sont abondantes et s’épuisent de jour en jour, tandis que nous demeurons pauvres ; intellectuellement, car nous sommes en train de sauver leur langue, épuisée, languissante, d’une mort programmée. Il paraît qu’une grande nation, qui a traversé des siècles avec panache, déchiffre difficilement les signes précurseurs de son déclin.",
  ]};
const dDembeleCapitalisme = { // ~115 mots (tokens)
  source:"Demba Moussa Dembélé, « Méconnaissance ou provocation délibérée ? », in L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Si M. Sarkozy avait un peu étudié l’histoire du capitalisme, il aurait su que la naissance et le développement de ce processus se sont faits avec le sang, la sueur et les ressources des peuples africains. Dans le livre I du Capital, Karl Marx explique comment l’esclavage transatlantique avait contribué à ce qu’il a appelé l’« accumulation primitive du capital ». Cette tragédie, que Joseph Ndiaye, conservateur de la Maison des esclaves de Gorée, qualifie à juste titre de « plus grand génocide de l’Histoire », a privé l’Afrique de plusieurs dizaines de millions de ses meilleurs enfants83. Cette hécatombe a eu des conséquences profondes qui continuent d’affecter le développement économique et social de l’Afrique84.",
  ]};
const dDembeleHeritage = { // ~73 mots (tokens)
  source:"Demba Moussa Dembélé, « Méconnaissance ou provocation délibérée ? », in L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "Dans cet héritage, on trouve la division internationale du travail imposée à l’Afrique et qui a fait d’elle un continent fournisseur de matières premières et de produits de base. Et le système dominant, les anciennes puissances coloniales en particulier, a tout fait pour maintenir cette division du travail. Les politiques néolibérales, surtout celles imposées par les institutions financières internationales, ont accentué cette division, rendant ainsi les économies africaines plus vulnérables aux chocs exogènes.",
  ]};
const dDembeleOCDE = { // ~124 mots (tokens)
  source:"Demba Moussa Dembélé, « Méconnaissance ou provocation délibérée ? », in L’Afrique répond à Sarkozy, Philippe Rey, 2008",
  paras:[
    "On estime que les pays de l’OCDE, le club des pays « les plus riches », dépensent plus d’un milliard de dollars sous forme de subventions agricoles par jour. Les dépenses annuelles au titre de ces subventions sont plus de six fois supérieures à l’« aide » accordée aux pays du Sud. En outre, elles ont entraîné des pertes massives de recettes d’exportation pour les pays du Sud estimées à plusieurs centaines de milliards de dollars, surtout dans les produits à forte intensité de main-d’œuvre94. Ce qui a fait dire au Pnud (Programme des Nations Unies pour le Développement) que la part d’un pays dans le commerce mondial dépend moins de l’« avantage comparatif » que de l’« accès comparatif aux subventions »95 !",
  ]};
const dNgomEntreprises = { // ~120 mots (tokens)
  source:"Abdoulaye Ngom, Mobilisations familiales et migrations intercontinentales, L’Harmattan, 2019",
  paras:[
    "De petites entreprises familiales se constituent, notamment dans le domaine de l’artisanat, du commerce, de la mécanique... Par exemple, un père peut gérer une entreprise familiale pendant plusieurs années et au fil des années insérer ses enfants, en leur apprenant notamment les ficelles du métier, pour qu’un jour ils puissent relayer les parents et perpétuer ainsi la petite entreprise familiale. Cette situation que nous venons de décrire vaut surtout pour des activités de caste. En réponse aux difficultés de la vie quotidienne et aux incertitudes du lendemain auxquelles sont confrontées de nombreuses familles, qu’elles soient en milieu rural ou urbain, les familles adoptent diverses stratégies de survie parmi lesquels l’envoi d’un des membres à l’étranger, notamment vers les pays européen.",
  ]};
const dNgomTontines = { // ~131 mots (tokens)
  source:"Abdoulaye Ngom, Mobilisations familiales et migrations intercontinentales, L’Harmattan, 2019",
  paras:[
    "En milieu rural, l’inexistence de banques et de structures financières d’épargne poussent les individus, en particulier les femmes, à avoir recours aux tontines. La tontine est de manière générale dirigée par un gérant qui se charge de recevoir les cotisations. Il a en sa possesssion le plus souvent un petit carnet sur lequel sont mentionnés les noms des différents membres et les dates de versement des cotisations. C’est le gérant qui, en même temps qu'il essaie de coordoner le fonctionnement de la tontine, se charge d’être le trésorier. Dans d’autres tontines par contre, il y a absence de tout document écrit, la seule règle d’or repose sur la confiance mutuelle entre les membres et le gérant, dans la mesure où l’ensemble des membres se connaissent bien avant leur regroupement en association.",
  ]};
const dNgomVoieTerrestre = { // ~146 mots (tokens)
  source:"Abdoulaye Ngom, Migration clandestine sénégalaise vers l’Europe, L’Harmattan, 2020",
  paras:[
    "Cependant, le passage par voie terrestre est aussi très dangereux. Les candidats à la migration risquent en cours de route d’être humiliés et malmenés par les passeurs, sur qui ils comptent pour se rendre d’un lieu à un autre jusqu’à leur destination finale. « Certains passeurs n’hésitent pas à donner rendez-vous à une heure tardive, à la sortie de la ville. Ils empochent alors l’argent, tuent et enterrent le migrant ». Les candidats à la migration qui optent pour le passage par voie terrestre sont donc confrontés à beaucoup de risques  et de souffrances, y compris le risque d’être tués au cours de leur voyage. Certains d’entre eux sont enlevés et détenus dans des sortes de prisons, sur le territoire libyen, qui sont sous l’emprise des passeurs, et ils y sont retenus, parfois durant des mois, tant que leur famille n’a pas payé la rançon exigée.",
  ]};
const dNgomMedias = { // ~115 mots (tokens)
  source:"Abdoulaye Ngom, Migration clandestine sénégalaise vers l’Europe, L’Harmattan, 2020",
  paras:[
    "Enfin le fait que les médias se soient entichés des migrations clandestines fait que très souvent un certain nombre de stéréotypes et de fausses idées sont véhiculées sur les candidats à la migration. En effet l’évolution rapide de la technologie des communications au cours du dernier siècle et le rôle croissant des médias audiovisuels dans la plupart des contrées de ce monde permettent la couverture des événements et l’accès à l’information de manière rapide. Il va donc sans dire que le traitement de la question migratoire dans les médias va nécessairement évoluer à la lumière de ces changements et de l’influence grandissante des nouveaux « outils » médiatiques électroniques et du développement des réseaux sociaux.",
  ]};
module.exports = { fraisGassama431, fraisDembele364, fraisSakho538, fraisNgom507, fraisNgom526, fraisSiribie606, dGassamaConcession, dGassamaDemande, dDembeleCapitalisme, dDembeleHeritage, dDembeleOCDE, dNgomEntreprises, dNgomTontines, dNgomVoieTerrestre, dNgomMedias };