/* Textes VERBATIM extraits automatiquement de _corpus2ndcycle.txt (textes référencés tirés du net). NE PAS RETOUCHER LE TEXTE. */
const ebongue = {
  titre:"La génération TikTok",
  source:"Amélie Ebongue, Génération TikTok, DUNOD, 2021",
  paras:[
    "TikTok est disponible dans 75 langues et couvre plus de 150 pays. Pour commencer, il suffit de s’inscrire sur le site. Facile à prendre en main, l’outil permet de gérer un ou plusieurs comptes publicitaires qui sont eux-mêmes associés à différentes campagnes publicitaires. Sous la forme d’un graphique, les campagnes sont regroupées en « groupe d’annonces » puis « annonces ».",
    "TikTok propose sur sa plateforme cinq objectifs publicitaires explicitement définis. Ils correspondent au traditionnel parcours client d’un utilisateur :",
    "– la portée : augmenter la notoriété de votre marque ou de votre produit pour faire adhérer votre audience à votre marque ;",
    "– l’installation d’application : inciter les internautes à installer votre application en les dirigeant vers la boutique de Téléchargement ou directement sur la page d’accueil de votre application ;",
    "– le trafic : orienter les internautes vers votre site ;",
    "– l’affichage de la vidéo : augmenter le nombre de personnes qui visionnent votre vidéo ;",
    "– la conversion : inciter les internautes à entreprendre une action concrète sur votre site web (acheter un produit ou télécharger votre application par exemple). Il est possible de cibler les internautes qui ont déjà interagi avec votre site web par le biais des audiences personnalisées.",
  ]};
const djarmailaMonnayage = {
  titre:"Services publics : la maladie du monnayage",
  source:"Grégoire Djarmaila, « Services publics : la maladie du monnayage in Cameroon tribune n°12686/ 8885 du 19 septembre 2022.",
  paras:[
    "Plusieurs noms de codes sont attribués à ces pratiques qui sont aussi vieilles que le monde : « gombo », « tchoko », « réseau », « geste », « blé », « enveloppe », « whisky ». Aucun service n’est épargné.",
    "Les arnaqueurs ont investi toute la chaîne administrative partant de l’accès aux grandes écoles en passant par les concours administratifs jusqu’au circuit des affectations en passant par les prises en solde des nouveaux agents publics, les avancements et les nominations. L’arnaque et le monnayage des services sont devenus tellement banals aujourd’hui que « la mercuriale » pour l’accès dans certaines grandes écoles ou dans un établissement d’enseignement secondaire est connue dans certains milieux. Il en est de même pour les sommes qui sont exigées à certains usagers pour le paiement de leurs rappels ou de leurs factures. L’avènement de la téléphonie mobile est venu faciliter la tâche à certains « racketeurs » impliqués dans la chaîne de traitement des dossiers. Ainsi, l’usager dont la demande de mutation, ou le dossier d’avancement ou encore de rappel en mémoire se trouve dans le circuit administratif, reçoit un coup de fil lui demandant de « motiver » ou de « mouiller la barbe » pour faire avancer son dossier.",
  ]};
const bonifaceIA = {
  titre:"Géopolitique de l’intelligence artificielle",
  source:"Pascal BONIFACE, Géopolitique de l’intelligence artificielle, Eyrolles, 2021",
  paras:[
    "Pour les plus optimistes, l’intelligence artificielle pourrait produire un tel développement de l’activité, de la production et de la satisfaction des besoins que le vieux rêve de Karl Marx se réaliserait enfin. Le développement des forces productives permettrait de passer au communisme où s’appliquerait la règle « à chacun selon ses besoins », en grillant l’étape du socialisme régi par la formule « à chacun selon son travail ». Marx voyait dans les progrès techniques une avancée pour les humains : « On ne peut abolir l’esclavage sans la machine à vapeur et la mule-jenny, ni abolir le servage sans améliorer l’agriculture : plus généralement, on ne peut libérer les hommes tant qu’ils ne sont pas en état de se procurer complètement nourriture et boissons, logement et vêtements en qualité et en quantité parfaite» Pour lui, « dans la société communiste, où chacun n’a pas une sphère d’activité exclusive, mais peut se perfectionner dans la branche qui lui plaît, la société réglemente la production générale ce qui crée pour moi la possibilité de faire aujourd’hui telle chose, demain telle autre, de chasser le matin, de pêcher l’après-midi, de pratiquer l’élevage le soir, de faire de la critique après le repas, selon mon bon plaisir, sans jamais devenir chasseur, pêcheur ou critique».",
    "L’IA serait une corne d’abondance qui assurerait un accès quasi illimité aux biens de consommation tout en libérant l’humanité des tâches les plus pénibles et rébarbatives. (237 mots)",
  ]};
const gelin = {
  titre:"Parlons IA",
  source:"Rodolphe Gelin, Parlons IA en 30 questions, Paris, 2024",
  paras:[
    "Ces dernières années, l’intelligence artificielle était dans tous les esprits en grande partie à cause des fantasmes qu’entretiennent des œuvres de fiction autour de la prise du pouvoir par les machines mais aussi parce que, dans l’industrie et la recherche, les progrès du machine learning, des « réseaux de neurones » et du deep learning, donnaient accès à des résultats jusque-là inespérés dans divers domaines : l’exploration spatiale, l’interprétation des images médicales, le déchiffrement de manuscrits anciens, l’amélioration de la précision des prévisions météorologiques. Toutes ces applications semblaient concerner des systèmes complexes pour lesquels l’informatique permettait au cerveau humain de résoudre des problèmes qui dépassaient ses capacités.",
    "L’IA était un outil sophistiqué, manipulé par des spécialistes pour traiter des problèmes très pointus. La révélation de ChatGPT, en novembre 2022, a changé la nature de l’engouement pour cette technologie. En réalisant que l’IA « parlait » comme nous, comprenait (quasiment) comme nous, le grand public a pris conscience des capacités de l’IA. Curieusement, c’est quand l’IA s’est mise à faire ce que chacun sait faire (comprendre des requêtes exprimées en langage naturel et les exécuter) que le plus grand nombre a évalué le potentiel de cette technologie pourtant quasiment octogénaire. Du fait de sa grande facilité d’utilisation et de la capacité de chacun à juger de la pertinence de ses réponses, ChatGPT a permis à l’IA d’acquérir la notoriété des autres grandes innovations technologiques de notre histoire : le feu, la roue, l’électricité, Internet.",
    "Pourtant, avant même l’arrivée de ChatGPT, l’intelligence artificielle était déjà omniprésente dans notre vie mais, à l’instar de l’électricité, nous ne la manipulions pas en tant que telle mais accédions à des services qui eux-mêmes l’utilisaient. Les moteurs de recherche sur Internet, les filtres antispams de nos boîtes courriel, les systèmes de recommandation de produits sur les sites de vente en ligne, les logiciels de navigation dans nos véhicules, la reconnaissance vocale qui permet de dicter des SMS à haute voix, la reconnaissance de visage qui déverrouille nos smartphones… tous ces services du quotidien, avec lesquels nous vivons depuis des années, reposent sur des algorithmes d’IA. ChatGPT n’est donc qu’une nouvelle expression de l’IA mais elle est mise à notre disposition sans véritable usage. A priori, elle ne fait qu’écrire des textes en réponse à des demandes. Chacun peut utiliser cette capacité brute à en faire ce qu’il veut : écrire du code informatique, résumer des articles, composer des chansons, comparer des textes… C’est un peu la même différence qu’entre donner un poisson à quelqu’un ou lui enseigner la pêche.",
  ]};
const fozing = {
  titre:"L’éducation au Cameroun",
  source:"Innocent Fozing, L’Education  au Cameroun, entre crises et ajustements économiques, L’Harmattan, 2014",
  paras:[
    "On peut remarquer qu'au début de la crise économique des années 1980, les salaires dans le secteur privé ont connu une apparente rigidité à la baisse qui peut s'expliquer par deux phénomènes. D’abord, jusqu’au début des années 1990, la grille salariale dans tous les secteurs (primaire, secondaire et tertiaire) était fixée de façon rigide par le Gouvernement de la République. Ensuite, dès l'apparition des premières difficultés en 1986'87, les entreprises privées ont procédé à des licenciements massifs, leur permettant de continuer à verser aux travailleurs ayant conservé leur emploi un salaire nominal acceptable.",
    "Au Cameroun, l'équilibre du marché du travail urbain et rural est réalisé grâce à l'auto - emploi, notamment dans le secteur informel qui assure près des deux tiers des emplois urbains (Fodzo, 2004). L'accès aux emplois de la fonction publique a été réglementé en fixant des quotas par ethnie lors du recrutement des fonctionnaires et des agents de l'État. Ces quotas, fixés au prorata du poids des populations de chaque ethnie, ont pour but de s'assurer que toutes les ethnies ont équitablement accès aux emplois de la fonction publique. Cette politique d'intégration dans la fonction publique a montré ses limites, les recrutements, notamment pour les emplois subalternes, étant fortement dépendants de lobbies ethniques et autres associations tribales, pour rappeler la théorie du capital social. De plus, l'État a fixé des salaires minima, par rapport au diplôme obtenu, avec le souci d'assurer à toutes les populations un accès au bien-être dans une économie dominée dans les premiers temps de l'industrialisation par le capital étranger.",
    "Afin d’apporter une solution durable aux exclus5 du marché du travail, le Gouvernement de la République a entrepris un certain nombre d’actions, dont sur le plan institutionnel, la mise en place en 1990 du Fonds national de l'emploi (FNE) dans le cadre de la Dimension Sociale de F Ajustement (DSA). Cette structure vise un certain nombre d’objectifs à savoir : accroître les possibilités d'emploi ; diffuser les informations aux chercheurs d'emploi favoriser l'insertion, dans le circuit de production, des jeunes à la recherche d'un premier emploi ; favorise la réinsertion des travailleurs licenciés pour des raisons économiques des entreprises du secteur public ou privé ; concevoir, financer et suivre des programmes ayant trait à la formation sur le tas et à l'apprentissage, la formation formelle, l'auto - création d'emploi, l'appui à la création des micro entreprises et éventuellement, tout autre programme en fonction des besoins du marché de l'emploi et offrir également la possibilité d'accès à un crédit pour la réalisation de micro et petits projets pour les jeunes diplômés et les demandeurs d'emploi dotés d'un esprit d'entreprise.",
  ]};
const nganang = {
  titre:"La révolte anglophone",
  source:"Patrice Nganang, La Révolte Anglophone, Essais de liberté, de prison et d’exil, Teham, 2018",
  paras:[
    "L’écrivain n'est pas seulement une machine à écrire des livres, c'est aussi une fonction publique. Cette fonction a une histoire qui n'est plus à réinventer, car chaque écrivain, quelles que soient ses impulsions, à un moment devrait répondre de ses appels, de ses obligations en fait. C'est comme un fonctionnaire qui, dans son bureau, malgré ses propres humeurs, devrait bien faire le travail qui s'accumule sur sa table de dossier en dossier. Les dossiers qui s'accumulent sur la table de l’écrivain, ce sont des histoires, les histoires des citoyens. Et elles lui sont racontées ainsi, simplement, s'accumulent donc sur sa table, à cause de ses écrits. La particularité de l'écriture est qu'elle touche le lecteur dans son intimité, et lui donne l'assurance que la personne qui a écrit le livre, le texte, le comprendrait. C'est sur la base de cette intimité entre personnes qui ne se connaissent pas, que le lecteur confie son histoire à l'écrivain. Cette relation entre inconnus est importante ici, car elle est le noyau de la république, le cœur de celle-ci, la république étant, dans toutes ses manifestations, une communauté de gens qui ne se connaissent pas. C'est cette communauté qui lie l'écrivain au lecteur, et qui fait que ce dernier le transforme en réceptacle de son histoire. C'est dire que de l'infrastructure de !'écrivain, seules les apparitions publiques sont visibles, et elles le sont parce que classiquement, .ce sont les livres qui sont la manifestation publique de l' écrivain, ou alors les articles, les textes courts, les interviews. En souterrain cependant, et cela est sa fonction publique la plus universelle, l’écrivain est un collectionneur d'histoires qui lui sont confiées comme on confierait un dossier à un fonctionnaire. […]",
    "Seul Mongo Beti a rempli chez nous cette fonction publique de l’écrivain avec brio, et sa mort en 2001 a marqué une césure violente dans l'occupation de l'espace public par l'écriture. C'est qu'il faut bien se rendre compte que la fonction de l’écrivain est l'une des plus respectées au Cameroun. En fait, beaucoup plus que de nombreux pays africains, le Cameroun est de ceux où la parole de l'écrivain pèse, et est prise très au sérieux. C'est que le magistère fondé par Njoya n'a jamais quitté la république, la scène publique donc, et dans l'attente des Camerounais, celui-ci doit toujours être occupé. En fait l'attente est si forte que notre peuple, pris en otage par une dictature des plus vicieuses et la plus vieille d'Afrique en plus, dans la précipitation croit reconnaître des écrivains dans des gens qui, au final, ne sont que des faussaires de l'alphabet, et des tueurs d'ailleurs. Car comme il y a des juristes de la tyrannie, il y a aussi des plumitifs de l'assassinat.",
  ]};
const djarmailaDiscipline = {
  titre:"Il faut repenser la discipline scolaire",
  source:"Grégoire Djarmaila, « Il faut repenser la discipline scolaire », in Cameroon tribune n°12580 du 14 avril 2022.",
  paras:[
    "Trois cas de violences ont tristement retenu l’attention de la communauté éducative ces dernières semaines. Après s’être empoignée avec sa Surveillante Générale, une élève a été exclue de son établissement et ce, à quelques mois de l’examen du baccalauréat pour lequel elle est inscrite. Quelques jours après, un autre apprenant a failli mettre fin, à l’aide d’un poignard, à la vie du responsable d’une institution scolaire privée à Yaoundé. Le dernier cas en date est celui d’un jeune élève sur qui une arme blanche a été découverte. Même si les réseaux sociaux constituent, à n’en pas douter, des facteurs amplificateurs de ces scènes de violence qui ont pour cadre les enceintes scolaires, les rixes, les altercations et les propos irrévérencieux rythment désormais les cours de récréation et les salles de classe et sont en train de devenir des faits banals. Dans les cas suscités, on a tôt fait de stigmatiser l’élève et d’hystériser la situation. Or, appréhender le problème avec une posture sentencieuse complexifie davantage sa compréhension et n’aide pas à mieux cerner les facteurs qui le produisent. Il ne faut pas perdre de vue que la violence en milieu scolaire met en cause deux acteurs : l’élève et l’enseignant. Il y a quelques semaines, un enseignant d’une école primaire à Douala a été interpellé pour avoir infligé une horrible bastonnade à son apprenant. Dans la même ville, un autre encadreur a été écroué parce que soupçonné de viols sur ses élèves filles.",
    "Les cas de violence qui prennent de l’ampleur ces dernières années dans les milieux scolaires et qui sont abondamment relayés par les médias classiques et les réseaux sociaux, affichent au grand jour les failles dans l’encadrement et l’éducation de nos enfants, mais aussi reflètent le caractère violent de l’environnement dans lequel baigne actuellement notre société. L’apprenant et l’enseignant ne vivent pas sur une autre planète que nous. Ils subissent parfois dans leur chair les frustrations et le mal-être de leur environnement et qui constituent des facteurs aggravants de la violence. Le chemin qui mène à l’école n’est pas pavé de roses. Sur la voie publique, dans les marchés et les gares routières, les stades et les lieux de grande concentration humaine, les comportements violents foisonnent. Las de chercher une solution dans le cadre familial ou scolaire, l’enfant développe un comportement agressif parfois dans l’illusion de se protéger ou de se valoriser auprès de ses camarades. Ce phénomène se nourrit par ailleurs du délaissement parental.",
    "Dans les zones urbaines difficiles, l’école est une sorte d’éponge, ou tout au moins, elle est poreuse à l’égard de son environnement. Si la plupart des enceintes scolaires fonctionnent dans un cadre clos, elles restent connectées à leur environnement immédiat. Les commerces, les débits de boissons, les lieux de loisirs, les structures d’hébergement entretiennent une dangereuse proximité avec les milieux scolaires. C’est ici que sont promus et vendus toutes sortes de produits forts (drogues, alcools, chichia, cannabis, tabac, tramadol) et dont les élèves constituent une « clientèle » de choix. De telles activités riveraines ont eu pour conséquence de produire un affaissement du consensus comportemental et le développement d’une résistance à l’observation de la discipline scolaire.",
    "Les solutions à toutes ces déviances interpellent à la fois la famille, l’institution scolaire et tous les autres acteurs de la chaîne éducative. La socialisation de l’enfant incombe d’abord à la famille. Mais aujourd’hui avec les bouleversements qui affectent aussi bien la famille que l’école, on assiste à une sorte de délaissement quant aux responsabilités que chaque institution devrait jouer.",
  ]};
const hebga = {
  titre:"Afrique de la raison, Afrique de la foi",
  source:"Meinrad Hebga, Afrique de la raison, Afrique de la foi, Karthala, 1995.",
  paras:[
    "Soulignons tout d'abord que la résistance non-violente n'est pas destinée aux peureux ; c’est une véritable résistance ! Quiconque y aurait recours par lâcheté ou par manque d'armes véritables, ne serait pas un vrai non-violent. C'est pourquoi, Gandhi a si souvent répété que, si l'on n'avait le choix qu'entre la lâcheté et la violence, mieux valait choisir la violence. La voie de la résistance non-violente est d'ailleurs le choix des forts, car elle ne consiste pas à rester dans un immobilisme passif. L'expression « résistance passive » peut faire croire à tort à une attitude de « laisser-faire » qui revient à subir le mal en silence. […]",
    "En second lieu, la non-violence ne cherche pas à vaincre ni à humilier l'adversaire, mais à conquérir sa compréhension et son amitié. Le résistant non-violent est souvent forcé à s'exprimer par le refus de coopérer ou les boycotts, mais il sait que ce ne sont pas là des objectifs en soi. Ce sont simplement des moyens pour susciter chez l'adversaire un sentiment de honte. Il veut engendrer une communauté de frères, alors que la violence n'engendre que haine et amertume.",
    "Troisièmement, c'est une méthode qui s'attaque aux forces du mal et non aux personnes qui se trouvent être les instruments du mal. Car c'est le mal lui-même que le non-violent cherche à vaincre, et non les hommes qui en sont atteints.",
    "Martin Luther-KING, Combats pour la liberté, Payot, 1975.\tTexte 2 :",
    "La condition sine qua non de tout décollage et progrès économique est liée à la volonté farouche de tout le peuple, et non point du seul appareil étatique. Et pour que naisse cette volonté, il ne faut rien de moins que la conversion de sa mentalité ancestrale, et l’arrachement volontariste à tout ce qui, dans l’approche du monde, constitue un frein et une pesanteur. Encore faut-il que nous prenions conscience de ces obstacles devenus pour nous comme une seconde nature. Qui va donc donner cette conscience au peuple et lui apprendre à se libérer ? L’école, l’entreprise, l’administration, les églises, la famille, toutes les institutions capables d’agir sur la mentalité collective ? Malgré les apparences, beaucoup de dirigeants et de décideurs africains qui maîtrisent les techniques de l’économie moderne, la croissance des circuits monétaires, de la productivité et de la croissance, ne sont pas nécessairement affranchis de la mentalité atavique : chez eux prime l’intérêt personnel, clanique ou tribal sur l’intérêt communal, provincial ou national. La corruption érigée en système, ainsi que la fuite organisée des fonds publics relèvent d’une même conception magique des choses : « je peux saigner à blanc l’organisme économique de mon pays, semblent-t-ils penser, mais avec un peu de chance, on s’en sortira quand même ».",
  ]};
const ngugi = {
  titre:"Décoloniser l’esprit",
  source:"Ngugi Wa Thiongo’o, Décoloniser l’esprit, La Fabrique, 2016",
  paras:[
    "J’ai commencé à écrire en kikuyu en 1977, après dix-sept ans à produire de la littérature afro-européenne et plus précisément afro-anglaise. Mon premier texte en kikuyu fut la pièce de théâtre Ngaahika Ndeenda (Je me marierai quand je voudrai), écrite en collaboration avec Ngugi wa Mirii. J’ai depuis écrit en kikuyu un roman, Caitaani Mutharabaini (Le Diable sur la croix), un drame musical, Maitu Njugira (Mère, chante pour moi), trois livres pour enfants et un second roman, Matigari.",
    "Partout où je suis allé, en Europe notamment, j’ai dû affronter la question : « Pourquoi écrivez-vous désormais en kikuyu ? Pourquoi écrire dans une langue africaine ? » Dans certains cercles académiques j'ai même essuyé des reproches : « Pourquoi nous avoir abandonnés ? » C’était partout comme si, en décidant d’écrire en kikuyu, j’avais fait quelque chose d’anormal. Mais le kikuyu est ma langue maternelle ! Le seul fait qu’on puisse adresser ce genre de questions à un écrivain africain en dit long sur les dégâts causés par l’impérialisme. Il a déformé la réalité et l’a mise sens dessus dessous : l’anormal est devenu normal et inversement. L’Afrique enrichit quotidiennement l’Europe ; mais on a persuadé l’Afrique qu’elle ne pouvait s’en tirer sans que l’Europe vole à son secours contre la pauvreté. Les ressources naturelles et humaines de l’Afrique continuent de profiter au développement de l’Europe et des ÉtatsUnis ; mais on a persuadé l’Afrique qu’elle devait remercier ces puissances pour leur aide. Pire : l’Afrique elle-même produit à présent des intellectuels qui s’appliquent à relayer ce genre de raisonnements !",
    "Je crois qu’écrire en kikuyu, langue kenyane, langue africaine, est une façon de contribuer, à ma modeste échelle, au combat des peuples kenyans et africains contre l’impérialisme. Dans les écoles et les universités, nos langues locales, celles des nombreuses nations qui forment le Kenya, étaient associées à l’arriération et au sous-développement. Nous qui allâmes à l’école, apprîmes avec le temps à mépriser ces langues qui nous valaient tous les jours humiliations et châtiments. Je ne veux pas que les enfants du Kenya d’aujourd’hui héritent de cette tradition impérialiste qui consiste à mépriser les formes de communication développées par leurs communautés au long de l’histoire. Je veux qu’ils s’affranchissent de l’aliénation coloniale.",
  ]};
const taubira = {
  titre:"L’esclavage raconté à ma fille",
  source:"Christiane Taubira, L’esclavage racontée à fille, Paris, Éditions Philippe Rey, 2015",
  paras:[
    "Quoi donc ? La paix nous fuira-t-elle toujours ? Et la clameur des hommes, toujours forcenés et toujours déçus, continuera-t-elle à monter vers les étoiles d’or, des capitales modernes incendiées par les obus, comme de l’antique palais de Priam incendié par les torches ? Non ! Non ! Et malgré ces conseils de prudence que nous donnent ces grandioses déceptions, j’ose dire, avec des millions d’hommes, que maintenant la grande paix humaine est possible, et si nous le voulons, elle est prochaine. Des forces neuves y travaillent : la démocratie, la science méthodique, l’universel prolétariat solidaire. La guerre devient plus difficile, parce qu’avec les gouvernements libres des démocraties modernes, elle devient à la fois le péril de tous par le service universel, le crime de tous par le suffrage universel. La guerre devient plus difficile parce que la science enveloppe tous les peuples dans un réseau multiplié, dans un tissu plus serré tous les jours de relations, d’échanges, de conventions ; et si le premier effet des découvertes qui abolissent les distances est parfois d’aggraver les froissements, elles créent à la longue une solidarité, une familiarité humaine qui font de la guerre un attentat monstrueux et une sorte de suicide collectif.",
    "Jean JAURÈS, l’Esprit du socialisme, six études et discours, Éditions Gonthier, Paris, 1964.",
    "L’esclavage, appelons-le esclavage-viol, assorti de la traite (comme je l’ai expliqué, pour la première fois ces deux fléaux étaient à ce point imbriqués), cet esclavage-là relève d’une Activité organisée, systématique, à grande échelle, du commerce et de l’exploitation d’êtres humains. Je t’ai raconté comment les puissances européennes avaient officiellement structuré, codifié, rationalisé le commerce triangulaire et l’esclavage, comment l’Église avait donné sa bénédiction, comment les sciences prétendues humaines lui avaient trouvé des motifs et des justifications. Les pratiques arabo-musulmanes, qui ont décimé les mêmes populations, ne doivent être ni absoutes ni sous-estimées ; cependant par les asientos, bulles papales, doctrines philosophiques, codes noirs et autres supports, l’Europe propulse à une autre échelle, méthodique, planifiée, rationnelle, ce qui relevait plutôt du rapt, du banditisme, du brigandage, de la flibuste, tout en étant déjà lucratif. Le Coran n’interdit pas l’esclavage, pas plus que la Bible ou les traités philosophiques d’Aristote ou de saint Augustin, qui suggèrent tous que cette condition relève d’un ordre social naturel, plaidant, certains, pour une domination bienveillante, exhortant les maîtres à traiter leurs esclaves sans trop de rigueur, pour que cette condition soit acceptable.",
  ]};
const frisch = {
  titre:"La coopération au développement",
  source:"Dieter FRISCH, LE COURRIER n°158. Juillet-Août 1996.",
  paras:[
    "La corruption, définie comme « abus de pouvoir public à des fins personnelles », a toujours existé. Mais au cours des dernières décennies, elle s’est étendue géographiquement et s’est amplifiée en intensité. Depuis le milieu des années 70, elle a atteint la quasi-totalité des pays du monde.",
    "On pouvait espérer que la libéralisation politique et économique qui marque les années 90 depuis la fin de la guerre froide, réduirait ce phénomène. Grâce à la transparence accrue issue du pluralisme politique et la liberté de la presse, le processus de démocratisation devrait normalement mobiliser des forces contre la corruption. Mais les jeunes démocraties restent fragiles et ont apparemment du mal à s’attaquer aux intérêts établis. Pour sa part, la Libéralisation économique, en réduisant les interventions étatiques et, partant, les occasions de corruption, devrait, elle aussi l’atténuer. Or, dans le court terme, nous observons plutôt le contraire : des structures d’État affaiblies, l’absence d’une législation adéquate, l’insuffisante capacité de l’appareil judiciaire à s’attaquer à la corruption, la recherche du gain facile, que d’aucuns confondent avec l’économie de marché, conclurent toutes à aggraver le phénomène, du moins dans une phase de transition. Cette évolution ne peut laisser indifférents ceux qui s’occupent et se préoccupent du développement",
    "Certes, on peut aborder la corruption et ses effets sous divers angles. On peut le faire par le biais éthique. Mais alors qu’est-ce qui nous autorise à prêcher la morale au Sud et à l’Est, alors que la corruption sévit aussi au Nord et que, s’agissant de corruption dans les relations économiques internationales, il y a, presque par définition, un corrupteur au Nord et un corrompu au Sud et à l’Est ? La seule réponse, moralement contestable et économiquement correcte, serait que le Nord riche peut se permettre de gaspiller une partie des ressources alors que, dans les Pays en Voie de Développement, les rares ressources doivent être utilisées de façon optimale. D’autres mettent en exergue les distorsions que la corruption provoque dans te jeu loyal des conditions de concurrence, en défavorisant les entreprises performantes, mais honnêtes.",
    "En effet, une longue expérience professionnelle m’amène à conclure que la corruption est un des obstacles majeurs au développement, que ses effets sur le développement sont désastreux.",
    "Pour ma part, je l’aborderai quant à ses effets sur le développement. Certains opposeraient à cette affirmation l’argument « culturel » qui veut faire croire que, dans certaines cultures, la corruption serait usuelle et normalement acceptée. Or, nulle part au monde, l’enrichissement par la corruption n’est licite ou moralement admis. Je citerai à ce sujet Olusegun Obasanjo, l’ancien président du Nigeria : « Dans la conception africaine de l’estime et de l’hospitalité, un don est un symbole, un signe. Sa valeur est dans l’esprit de donner, non dans sa valeur matérielle. Le don est fait ouvertement, jamais dans le secret, pour que tous le voient Lorsqu’un don est excessif, il suscite de l’embarras et est même rendu au donneur. La corruption a perverti les aspects positifs de cette tradition ».",
    "Ensuite, il y a les cyniques, et parmi eux des professeurs réputés, qui prétendent que la corruption graisse la machine du développement et la fait fonctionner. Encore convient-il, à cet égard, tout aspect éthique à nouveau mis à part, de distinguer entre le petit bakchich qui peut accélérer certaines procédures administratives (« accélération fées ») et la grande corruption qui, elle, pervertit le processus de développement. Sans sous-estimer pour autant l’effet destructeur, même de la petite corruption, sur la société.",
  ]};
const legoux = {
  titre:"Le progrès en question",
  source:"CLAUDE LEGOUX, Le Monde, 5 septembre 1980.",
  paras:[
    "La technologie moderne est en train de fabriquer une multitude d’esclaves mécaniques, qui vont, dans tous les domaines de la production et des services, concurrencer avantageusement les travailleurs humains. Rares seront les Activités qu’un automate, commandé par un ordinateur, ne pourra pas assumer.",
    "Les prototypes à l’essai d’usines presse-boutons ne sont que l’avant-garde qui ne laissera subsister que quelques ingénieurs et quelques balayeurs. Toute la gestion des entreprises et des administrations sera informatisée. L’agriculture elle-même deviendra une industrie automatisée. Et ce n’est pas de la science- fiction. Tout cela, on sait déjà le faire. Il ne s’agit que de mettre au point la standardisation.",
    "Tout geste répétitif, aussi précis et délicat soit-il, peut être exécuté par un robot. Or la fabrication de n’importe quel objet courant, du verre à boire à l’automobile, depuis la matière première jusqu’au conditionnement, n’est qu’une suite plus ou moins complexe de gestes répétitifs. Naturellement, plus la chaîne est longue, plus elle comporte de sous-ensembles et plus elle nécessite d’investissements, et doit donc s’amortir sur un plus grand nombre d’unités. Un robot, d’ailleurs, n’aura que peu de rapports avec les silhouettes humanoïdes popularisées par les romans, car il se définit comme un couple : machine- ordinateur.",
    "Il en sera des opérations mentales répétitives comme des gestes répétitifs. Elles seront effectuées par des robots intellectuels, qui, rivalisant déjà avec les meilleurs joueurs d’échecs, remplaceront fort bien la plupart des employés de bureau, et pas seulement ceux de la base. Une bonne part des décisions leur seront confiées.",
    "Il restera toutefois quelques problèmes importants à résoudre. En tout premier lieu, il faudra absorber la production des esclaves-mécaniques. Car il est évident que, si le propriétaire, privé ou collectif, d’une usine travaillant pratiquement toute seule ne paye aucun salarié, et si la plupart des autres usines sont dans le même cas, personne ne pourra plus acheter les marchandises produites. Il faudra donc que la collectivité verse à chacun des citoyens une rente, perçue sur la production des robots. La population sera constituée d’une masse d’oisifs, percevant une sorte de minimum vital, et d’une minorité de travailleurs aux confortables émoluments. Car ne travailleront que ceux qui en seront capables, et qui seront motivés, soit par l’attrait intrinsèque de leur tâche, soit par un salaire élevé.",
    "Mais alors un second problème découlera de la solution du premier. Que feront les oisifs de leur temps ? Ce sera, sur une plus grande échelle, le problème qui se posait aux aristocraties de naguère. Il est probable qu’un bon nombre de ces nouveaux rentiers sombreront dans l’alcool, la drogue, la débauche, la délinquance, ou simplement la folie. Mais d’autres se livreront à des Activités artistiques ou ludiques, qui suffiront à meubler leur existence. De toute façon, la production des génies et des imbéciles ne devrait pas beaucoup varier. Quant à la proportion des asociaux, elle croîtra ou s’amenuisera, dans la mesure où l’organisation politique se montrera plus ou moins répressive.",
    "Le dernier problème sera celui des rapports avec le tiers-monde. La prise en charge par l’Occident de l’intégration progressive de ces peuples à la civilisation des loisirs serait parfaitement concevable. Mais il y faudrait un grand courage, une grande abnégation et une grande lucidité. Toutes qualités qui ne sont pas à la hauteur de l’intelligence des civilisés. Bien rares seront ceux qui envisageront avec sang- froid de passer leur temps et de risquer leur vie, sans le moindre espoir de gratitude, pour faire le bonheur, malgré eux, de gens qui ne les comprendront pas.",
  ]};
const montassier = {
  titre:"Le fait culturel",
  source:"Gérard Montassier, Le fait culturel, Fayard 1980",
  paras:[
    "📌Texte:                                    TEXTE  : TELEVISION ET CULTURE DE MASSE.",
    "Aujourd'hui, nous sommes entrés dans l’époque de la culture de masse, de la culture présente dans tous les foyers grâce à la télévision et à '’audiovisuel. Mais si ces appareils sont porteurs de création, s’ils ont enrichi notre patrimoine de films de cinéma et de télévision qui n’ont rien à envier aux chefs-d’œuvre des autres arts, ils sont avant tout des moyens de diffusion ; cela signifie que, pour l’essentiel, les sources de culture sont ailleurs r qu’en eux : dans les sciences, dans la littérature dans les arts, dans l’histoire, et dans la vie sociale, pour l’ensemble des pratiques culturelles. La culture étant l’effort de l’homme pour comprendre le monde et s’adapter, à lui, l’audiovisuel est le témoignage offert à tous de cet effort.",
    "Mais cette offre ne constitue pas à elle seule un accès à la culture : elle est un pas de géant qui ne débouche sur rien s’il n’y a pas apprentissage préalable ou concomitant. C’est la raison pour laquelle il faut se résigner à accepter le fait que la télévision par elle-même ne changera jamais dans les proportions importantes le niveau de culture des téléspectateurs. Son effet est quantitatif qui ferait passer les niveaux de culture à un aute. Précisément parce que l’apprentissage préalable est indispensable et qu’il se pratique ailleurs que devant, l’écran familial. L'audiovisuel est un merveilleux instrument d’appoint, d’illustration, de commentaire, ' parce que l’image est présente, parce qu’elle parle aux sens et à l’imagination lui est donnée par un savoir qui vient d’ailleurs. Celui que nous possédons déjà er nous- mêmes, ou celui que nous possédons déjà, en nous-mêmes, ou celui qui nous est communiqué par une voix extérieure à l’image.",
    "De là vient que la télévision est toujours contestée. Elle nous enferme, en effet dans une alternative ou bien elle s’adapte au niveau moyen, évalué par sondage, d’une public massif, mais alors elle renonce au vertement à être un instrument de progrès et elle engendre la frustration dans la partie de la nation la plus cultivée. Ou bien la télévision choisit de satisfaire les goûts de l’élite : la frustration cette fois s’installe chez ceux qui ressentent leur insuffisance et le dédain dans lequel on les tient. Le bon sens commande donc une solution de compromis et que l’on battisse des programmes diversifiés des programmes diversifiés pour des publics différents. Mais quelle que soit la formule adoptée, on observera qu’elle agit comme un révélateur : elle renvoie toujours à une réalité qui se situe en dehors et au-delà de la télévision, et cette réalité n’est autre que le niveau de culture du téléspectateur. L’avènement de l’audiovisuel ne change donc rien au fait qu’aujourd’hui comme hier nous nous trouvons confrontés au problème éternel de la formation des hommes, c’est-à- dire de l’acquisition.\t_",
  ]};
const duverger579 = {
  titre:"Les inégalités sociales",
  source:"Maurice DUVERGER, Introduction à la politique, Éditions Gallimard, 1968.",
  paras:[
    "La situation de pénurie engendre, en règle générale, l’inégalité : une minorité privilégiée vit dans l’abondance, tandis que la masse supporte des privations graves. Souvent, plus la pauvreté générale est grande, plus s’étale la richesse des oligarchies. Dans les pays de famine endémique, l’embonpoint est un signe de puissance. Quand le peuple va en guenilles, les privilégiés s’habillent de brocart et d’or ; quand on loge dans des taudis misérables ou couche à la belle étoile, ils font construire des palais fastueux. La richesse et le luxe d’un petit nombre, au milieu d’une foule misérable : cette situation est explosive, par nature. L’inégalité développe des antagonismes très profonds. À la haine des masses contre les privilégiés répond la peur des privilégiés. La politique est faite de la violence des masses, en situation de révolte endémique, et de la violence des privilégiés qui se protègent contre elles. D’ailleurs, la pénurie fait que seule l’exploitation des masses par les privilégiés permet de développer la civilisation. Dans les sociétés de pénurie, si l’égalité régnait, tous les hommes seraient obligés de peiner tout le jour pour arriver juste à survivre. A ce stade de la science, la pensée, la culture, l’art, ne sont possibles que si certains hommes disposent des loisirs indispensables, en imposant aux autres une peine accrue.",
    "Le progrès technique ne supprime pas les inégalités, mais il les rend moins sensibles. Dans les sociétés modernes, la diversité des fonctions et leur importance entraînent l’inégalité des revenus et des conditions du travail. Encore faudrait-il s’entendre à cet égard. On peut présenter deux images opposées de l’évolution des sociétés industrielles. D’un côté, on peut montrer qu’elles tendent à une stratification sociale complexe, à une diversification des situations ; de l’autre, on peut décrire un processus inverse. Beaucoup d’Américains disent que les États-Unis sont une société sans classe, la ressemblance des genres de vie y est frappante, en effet. Le développement économique tend à réduire l’écart des niveaux d’existence, à resserrer l’éventail des revenus. Entre Rockefeller1 et le manœuvre américain, la distance est moins grande qu’entre le baron médiéval et son serf. Les sociétés industrielles paraissent évoluer vers la disparition de la très grande richesse et de la très grande misère. Elles marchent vers l’égalisation relative des conditions de vie.",
    "D’autre part, les sources de l’inégalité y sont différentes. Dans les sociétés sous- développées, la jouissance de privilèges dépend essentiellement de la naissance ; dans les sociétés surdéveloppées, elle dépend de plus en plus des capacités. D’un point de vue philosophique, la différence n’est pas très grande : naître intelligent ou naître aristocrate, c’est toujours bénéficier d’un avantage inné. Les imbéciles aussi portent le poids d’un hasard originel. Le même raisonnement vaut pour la force ou la faiblesse physique, la santé ou la maladie, la beauté ou la laideur, le talent ou la médiocrité. Pratiquement, l’inégalité de naissance tient à la situation sociale, laquelle répartit les hommes en classes antagonistes. Or l’inégalité subjective engendre des oppositions et des conflits plus que l’inégalité objective. L’opinion publique admet en général que les plus habiles, les mieux doués, les plus intelligents réussissent mieux que les autres ; elle comprend en même temps la nécessité de cette règle pour assurer le progrès collectif.",
    "Surtout, l’élévation générale du niveau de vie, l’accroissement du bien-être matériel et du confort, le développement des loisirs et de leur agrément : tous ces faits qui caractérisent l’abondance économique due au progrès technique, réduisent l’importance accordée aux inégalités et les antagonismes qui en résultent.",
  ]};
const kelman539 = {
  titre:"Pour en finir avec l’alibi racial",
  source:"Gaston KELMAN, Pour en finir avec l’alibi racial. Éditions Ifrikiya. 2007",
  paras:[
    "📌Texte : L’Afrique : malade de ses dirigeants ?",
    "La libération effective des peuples africains comme de tous les peuples dominés, ne viendra jamais de la volonté du maître. Cette logique est totalement absente de son mode de fonctionnement. Il ne sert à rien d’essayer de quérir sa collaboration. Mais une fois vaincu par la force qu’il croyait maîtriser, le dominant comprend que désormais, seule la ruse lui permettra de maintenir sa mainmise sur ceux qu’il ne veut pas lâcher.",
    "La France a choisi la méthode qui consiste à endormir son ancien sujet, à se positionner comme l’ami sans lequel on ne peut rien. Chaque candidat français à la présidence de la république se sent obliger d’aller en Afrique –c’est-à-dire au Sénégal et/ou au Mali, mais l’Afrique n’est-elle pas un simple village – Pour rassurer ses amis africains qu’il ne va pas les abandonner. Je ne me souviens pas que les candidats anglais se soumettent au même exercice.",
    "Si quelqu’un prétend entendre dans mes propos un dédouanement de l’Occident de ses responsabilités sur les crises africaines, c’est que je ne me suis pas bien fait comprendre. Seulement, le dominant n’a jamais libéré le dominé. Il appartient au dominé de conquérir sa liberté. Au cours d’un récent colloque en Belgique, j’ai entendu avec un grand plaisir – Ce discours est si rare – un intervenant interpeller les congressistes africains et leur dire que l’Occident avec sa pollution sa science sans conscience et sa technologie sans humanisme, courait à sa propre perte ; qu’aujourd’hui, en Occident, quand vous vous mettez à table, on ne vous dit plus bon appétit mais bonne chance, car vous ne savez même pas ce que vous avez dans votre assiette, entre le ruminant carnivore et la plante transgénique. Cet Occident qui s’empêtre dans ses contractions, n’a donc pas les moyens de s’occuper de l’Afrique.",
    "Dans toutes les civilisations, c’est la pensée qui a dressé le peuple contre les dirigeants ou qui lui a ouvert les yeux sur ses propres tares. Le philosophe sud-américain José Marti disait en substance qu’un peuple qui est sous la dictature, la mérite. Malcom X, Martin Luther King, Nelson Mandela, Gandhi, Socrate, Jésus-Christ, Karl Marx, Moumié, Oum-Nyobe, tous appartenaient au monde la pensée, étaient donc des intellectuels. La révolution française a été conduite par les intellectuels. C’est tout le monde noir qui est gangrené par des atavismes dont certains, mais peut-être pas tous, sont le fruit de son contact avec le Blanc. Il faut donc y retourner pour en guérir et ça, c’est le travail de l’intellectuel : réveiller la conscience de son peuple. Les pères de la négritude : Senghor, Césaire, Damas étaient des intellectuels qui ont fait comprendre au Noir qu’il était un homme. L’intellectuel d’aujourd’hui doit faire son travail. Ce n’est pas son implantation géographique qui est importante. Ce sont ses idées. L’ayatollah Khomeiny a dirigé la révolution irakienne à partir de la France…",
    "Il est faux de penser que les dirigeants sont les seuls responsables de la situation dans les pays d’Afrique. C’est tout le peuple qui en est responsable. Les dirigeants ne sont pas des martiens parachutés par un esprit malin pour nuire au Noir. Le dirigeant est l’enfant du peuple, il est le produit du peuple.",
  ]};
const malapa = {
  titre:"Un nègre qui parle yiddish",
  source:"Benny Malapa, Un nègre qui parle Yiddish, Fayard, Août 2025",
  paras:[
    "« Je m'appelle Tony, moi aussi je suis camerounais, j’avais un club nie Sainte-Anne près de T Opéra, après la guerre et pendant les années 50. Tous les Africains de Paris, tous les Antillais, tous les noirs américains y venaient. C’est là que j’ai connu ton père !» Il a jeté en vrac des noms de personnes, des lieux, des situations déjà évoquées par mon père ou que nous avions vécues directement. Je me demandais comment il pouvait en savoir autant et j’écoutais, fasciné.« J’ai été professeur puis danseur après j’ai tenu un night-chib, aujourd’hui je n’ai plus un rond.  Même pas de quoi te payer ce repas auquel je t’invite, mais je t’invite parce que je suis Tony et ton père c’est Paul, Paul Malapa ! Nous avons été les rois de Paris et lui, c’est un Banlio, le seul roi vivant des Batangas. »",
    "Puis brusquement il s’est tu, ses yeux noirs brillant d’une lueur un peu folle. Pour me prouver qu’il ne racontait pas n’importe quoi. Tony a interpellé avec autorité un client qui dînait quelques tables plus loin : « Frédéric ! Frédéric ! Viens ici ! » L’homme a obtempéré sans aucune hésitation et nous a rejoints.",
  ]};
const delors506 = {
  titre:"L’éducation, un trésor est caché dedans",
  source:"Jacques DELORS, L’Éducation, un trésor est caché dedans, 1996.",
  paras:[
    "L’objectif de pure croissance économique se révèle insuffisant pour garantir le développement humain. Il se trouve en quelque sorte doublement remis en question : non seulement en raison de son caractère inégalitaire, mais à cause des coûts élevés qu’il induit, notamment en matière d’environnement et d’emploi.",
    "Au rythme de production actuel, les ressources dites non reproductibles risquent en effet de se raréfier, qu’il s’agisse des ressources énergétiques ou des terres arables. En outre, les industries greffées sur les sciences physiques, chimiques et biologiques sont à l’origine de pollutions, elles aussi destructrices ou perturbatrices de la nature. Enfin de manière plus générale, les conditions de vie sur notre planète se trouvent menacées : la raréfaction de l’eau potable, la déforestation, « l’effet de serre », la transformation des océans en une poubelle géante sont autant de manifestations inquiétantes d’une irresponsabilité générale de nos générations à l’égard de l’avenir, dont la Conférence des Nations Unies sur l’environnement et le développement, tenue à Rio de Janeiro en 1992, a souligné la gravité.",
    "D’autre part, l’extension rapide du chômage, au cours de ces dernières années, dans un nombre important de pays, constitue à bien des égards un phénomène structurel lié au progrès technologique. A trop systématiquement substituer à la main-d’œuvre un capital technique novateur qui accroît sans cesse la productivité du travail, on contribue au sous-emploi d’une partie de la main-d’œuvre. Le phénomène a d’abord touché le travail d’exécution ; il atteint désormais certaines tâches de conception ou de calcul. La généralisation de l’intelligence artificielle risque de le faire remonter le long de la chaîne de qualification. Il ne s’agit plus seulement de l’exclusion de l’emploi, voire de la société, de groupes d’individus mal préparés, mais d’une évolution qui pourrait modifier la place, voire la nature même du travail dans les sociétés de demain. Il est difficile d’établir, dans l’état actuel des choses, un diagnostic sûr, mais la question mérite d’être posée.",
    "On observera que dans les sociétés industrielles, cimentées par la valeur intégratrice du travail, ce problème constitue d’ores et déjà une source d’inégalité : certains ont du travail, les autres en sont exclus et deviennent des assistés ou des laissés-pour-compte. Faute d’avoir trouvé un modèle nouveau de structuration du temps de la vie humaine, ces sociétés sont en crise : le travail y devient un bien rare que les nations s’arrachent par toutes sortes de protectionnismes et de « dumping » social. Le problème du chômage menace aussi très gravement la stabilité des pays en développement. Le risque est donc présent partout : de nombreux jeunes sans emploi, livrés à eux-mêmes dans les grandes agglomérations urbaines, courent tous les dangers liés à l’exclusion sociale. Une telle évolution se révèle très coûteuse socialement et risque, à l’extrême, de compromettre la solidarité nationale. On peut alors considérer, dans une formulation qui se veut prudente, que le progrès technique avance plus vite que notre capacité à imaginer les solutions aux problèmes nouveaux qu’il pose aux individus et aux sociétés modernes. Il faut repenser la société en fonction de cette évolution inéluctable.",
  ]};
module.exports = { ebongue, djarmailaMonnayage, bonifaceIA, gelin, fozing, nganang, djarmailaDiscipline, hebga, ngugi, taubira, frisch, legoux, montassier, duverger579, kelman539, malapa, delors506 };